Repository elastic/observability-docs, pull requests merged in 2020-09, with the labels that each got.

#123 [7.x] Make troubleshooting and FAQ separate topics (#120)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.10.0, backport, docs

#124 [7.9] Make troubleshooting and FAQ separate topics (#120)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.9.0, backport, docs

#122 Document how to set the ES host and Kibana URLs in Ingest Manager
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/kibana-ingest-manager-settings.png
Labels: 7.10.0, 7.9.0, 8.0.0, docs

#125 [7.x] Document how to set the ES host and Kibana URLs in Ingest Manager (#122)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/kibana-ingest-manager-settings.png
Labels: 7.10.0, backport

#126 [7.9] Document how to set the ES host and Kibana URLs in Ingest Manager (#122)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/kibana-ingest-manager-settings.png
Labels: 7.9.0, backport

#129 Add logs monitoring content
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/fields-reference.asciidoc
  docs/en/observability/images/action-type-logs.png
  docs/en/observability/images/anomalies-chart.png
  docs/en/observability/images/contextual-logs.png
  docs/en/observability/images/log-categories.png
  docs/en/observability/images/log-event-details.png
  docs/en/observability/images/log-threshold-alert.png
  docs/en/observability/images/logs-app.png
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/tail-logs.asciidoc
Labels: 7.10.0, docs

#131 [7.x] Add logs monitoring content (#129)
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/fields-reference.asciidoc
  docs/en/observability/images/action-type-logs.png
  docs/en/observability/images/anomalies-chart.png
  docs/en/observability/images/contextual-logs.png
  docs/en/observability/images/log-categories.png
  docs/en/observability/images/log-event-details.png
  docs/en/observability/images/log-threshold-alert.png
  docs/en/observability/images/logs-app.png
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/tail-logs.asciidoc
Labels: backport

#133 Strengthen language about ingest management upgrade restriction in 7.8
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.8.0, docs

#138 docs: link to APM Server ref
  docs/en/observability/install-observability.asciidoc
Labels: 7.9.0

#140 [7.9] docs: link to apm server ref (#138)
  docs/en/observability/install-observability.asciidoc
Labels: backport

#139 [7.x] docs: link to apm server ref (#138)
  docs/en/observability/install-observability.asciidoc
Labels: backport

#142 [7.x] [Metrics UI] Add docs for alerting context variables (#20)
  docs/en/metrics/images/metrics-alert-message.png
  docs/en/metrics/metrics-alerting.asciidoc
Labels: backport

#143 Add FAQ topics about how agent accesses integrations
  docs/en/ingest-management/faq.asciidoc
Labels: 7.10.0, 8.0.0, docs, needs_backport

#145 [7.x] Add FAQ topics about how agent accesses integrations (#143)
  docs/en/ingest-management/faq.asciidoc
Labels: 7.10.0, backport

#147 Remove old reviewer notes
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: 8.0.0

#146 [7.9] Add FAQ topics about how agent accesses integrations (#143)
  docs/en/ingest-management/faq.asciidoc
Labels: 7.9.0, backport

#134 Add metrics monitoring content
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/explore-metrics.asciidoc
  docs/en/observability/fields-reference.asciidoc
  docs/en/observability/images/action-type-metrics.png
  docs/en/observability/images/add-custom-metric.png
  docs/en/observability/images/alert-preview-metric.png
  docs/en/observability/images/alert-preview.png
  docs/en/observability/images/inventory-alert.png
  docs/en/observability/images/kubernetes-filter.png
  docs/en/observability/images/metrics-alert.png
  docs/en/observability/images/metrics-app.png
  docs/en/observability/images/metrics-explorer-filter.png
  docs/en/observability/images/metrics-explorer.png
  docs/en/observability/images/metrics-time-series.png
  docs/en/observability/images/pod-metrics.png
  docs/en/observability/index.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-aws-services.asciidoc
  docs/en/observability/monitor-docker-containers.asciidoc
  docs/en/observability/monitor-kubernetes-pods.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/monitor-servers.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
Labels: 7.10.0, docs

#150 [7.x] Add metrics monitoring content (#134)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/explore-metrics.asciidoc
  docs/en/observability/fields-reference.asciidoc
  docs/en/observability/images/action-type-metrics.png
  docs/en/observability/images/add-custom-metric.png
  docs/en/observability/images/alert-preview-metric.png
  docs/en/observability/images/alert-preview.png
  docs/en/observability/images/inventory-alert.png
  docs/en/observability/images/kubernetes-filter.png
  docs/en/observability/images/metrics-alert.png
  docs/en/observability/images/metrics-app.png
  docs/en/observability/images/metrics-explorer-filter.png
  docs/en/observability/images/metrics-explorer.png
  docs/en/observability/images/metrics-time-series.png
  docs/en/observability/images/pod-metrics.png
  docs/en/observability/index.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-aws-services.asciidoc
  docs/en/observability/monitor-docker-containers.asciidoc
  docs/en/observability/monitor-kubernetes-pods.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/monitor-servers.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
Labels: backport

#69 Add Content: Observability for java applications
  docs/en/observability/images/monitor-java-app-apm-architecture-cloud.png
  docs/en/observability/images/monitor-java-app-apm-transactions.png
  docs/en/observability/images/monitor-java-app-apm-ui-javalin-app.png
  docs/en/observability/images/monitor-java-app-apm-ui-javalin-with-transaction-names.png
  docs/en/observability/images/monitor-java-app-apm-ui-javalin-wttr-1.png
  docs/en/observability/images/monitor-java-app-apm-ui-javalin-wttr-2.png
  docs/en/observability/images/monitor-java-app-apm-ui-logging-trace.png
  docs/en/observability/images/monitor-java-app-cloud-after-login.png
  docs/en/observability/images/monitor-java-app-cloud-deployment-1.png
  docs/en/observability/images/monitor-java-app-cloud-deployment-2.png
  docs/en/observability/images/monitor-java-app-cloud-deployment-finished.png
  docs/en/observability/images/monitor-java-app-cloud-deployment-ongoing.png
  docs/en/observability/images/monitor-java-app-introduction-diagram-observability.svg
  docs/en/observability/images/monitor-java-app-kibana-discover.png
  docs/en/observability/images/monitor-java-app-kibana-expand.png
  docs/en/observability/images/monitor-java-app-kibana-login.gif
  docs/en/observability/images/monitor-java-app-kibana-single-document.png
  docs/en/observability/images/monitor-java-app-kibana-streaming.png
  docs/en/observability/images/monitor-java-app-metrics-kibana-create-visualization-log-rate.png
  docs/en/observability/images/monitor-java-app-metrics-kibana-create-visualization-open-files.png
  docs/en/observability/images/monitor-java-app-metrics-metricbeat-system-dashboard.png
  docs/en/observability/images/monitor-java-app-metrics-ui-prometheus-event-counter.png
  docs/en/observability/images/monitor-java-app-metrics-ui-prometheus-file-handles.png
  docs/en/observability/images/monitor-java-app-uptime-overview.png
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: 7.10.0, docs

#141 Expand documentation for log threshold alerts
  docs/en/observability/images/log-threshold-alert-chart-previews.png
  docs/en/observability/images/log-threshold-alert-es-query-grouped.png
  docs/en/observability/images/log-threshold-alert-es-query-ungrouped.png
  docs/en/observability/images/log-threshold-alert-group-by.png
  docs/en/observability/logs-threshold-alert.asciidoc
Labels: 7.10.0, 8.0.0

#153 [7.x] Expand documentation for log threshold alerts (#141)
  docs/en/observability/images/log-threshold-alert-chart-previews.png
  docs/en/observability/images/log-threshold-alert-es-query-grouped.png
  docs/en/observability/images/log-threshold-alert-es-query-ungrouped.png
  docs/en/observability/images/log-threshold-alert-group-by.png
  docs/en/observability/logs-threshold-alert.asciidoc
Labels: backport

#156 Add screenshot role to screen captures in the java tutorial
  docs/en/observability/monitor-java-app.asciidoc
Labels: 7.10.0, docs, needs_backport

#157 [7.x] Add screenshot role to screens (#156)
  docs/en/observability/monitor-java-app.asciidoc
Labels: 7.10.0, backport
