Repository elastic/observability-docs, pull requests merged in 2020-10, with the labels that each got.

#155 [Logs UI] Update log threshold alert docs
  docs/en/observability/images/log-threshold-alert-chart-previews.png
  docs/en/observability/images/log-threshold-alert-es-query-grouped.png
  docs/en/observability/images/log-threshold-alert-es-query-ungrouped.png
  docs/en/observability/images/log-threshold-alert-group-by.png
  docs/en/observability/images/log-threshold-alert-ratio.png
  docs/en/observability/images/log-threshold-alert.png
  docs/en/observability/logs-threshold-alert.asciidoc
Labels: 7.10.0, 8.0.0

#158 [7.x] [Logs UI] Update log threshold alert docs (#155)
  docs/en/observability/images/log-threshold-alert-chart-previews.png
  docs/en/observability/images/log-threshold-alert-es-query-grouped.png
  docs/en/observability/images/log-threshold-alert-es-query-ungrouped.png
  docs/en/observability/images/log-threshold-alert-group-by.png
  docs/en/observability/images/log-threshold-alert-ratio.png
  docs/en/observability/images/log-threshold-alert.png
  docs/en/observability/logs-threshold-alert.asciidoc
Labels: backport

#152 Add docs for metric context vars and pre-population
  docs/en/observability/images/advanced-variables.png
  docs/en/observability/images/basic-variables.png
  docs/en/observability/images/inventory-create-alert.png
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: 7.10.0

#159 [7.x] Add docs for metric context vars and pre-population (#152)
  docs/en/observability/images/advanced-variables.png
  docs/en/observability/images/basic-variables.png
  docs/en/observability/images/inventory-create-alert.png
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#161 Fix URL for Elastic Package Registry
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.9.0, docs

#162 Add Uptime monitoring content
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/explore-metrics.asciidoc
  docs/en/observability/images/alert-connector.png
  docs/en/observability/images/cert-expiry-settings.png
  docs/en/observability/images/heartbeat-indices.png
  docs/en/observability/images/inspect-uptime-duration-anomalies.png
  docs/en/observability/images/monitor-duration-chart.png
  docs/en/observability/images/monitor-status-alert.png
  docs/en/observability/images/monitors-chart.png
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/pings-over-time.png
  docs/en/observability/images/response-durations-alert.png
  docs/en/observability/images/tls-alert.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-alert-connectors.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-connector-duration.png
  docs/en/observability/images/uptime-connector-variables.png
  docs/en/observability/images/uptime-filter-bar.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/images/uptime-status-variables.png
  docs/en/observability/index.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/install-observability.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: 7.10.0, docs, needs_backport

#173 [7.x] Add Uptime monitoring content (#162)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/explore-metrics.asciidoc
  docs/en/observability/images/alert-connector.png
  docs/en/observability/images/cert-expiry-settings.png
  docs/en/observability/images/heartbeat-indices.png
  docs/en/observability/images/inspect-uptime-duration-anomalies.png
  docs/en/observability/images/monitor-duration-chart.png
  docs/en/observability/images/monitor-status-alert.png
  docs/en/observability/images/monitors-chart.png
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/pings-over-time.png
  docs/en/observability/images/response-durations-alert.png
  docs/en/observability/images/tls-alert.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-alert-connectors.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-connector-duration.png
  docs/en/observability/images/uptime-connector-variables.png
  docs/en/observability/images/uptime-filter-bar.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/images/uptime-status-variables.png
  docs/en/observability/index.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/install-observability.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#174 [7.10] Add Uptime monitoring content (#162)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/explore-metrics.asciidoc
  docs/en/observability/images/alert-connector.png
  docs/en/observability/images/cert-expiry-settings.png
  docs/en/observability/images/heartbeat-indices.png
  docs/en/observability/images/inspect-uptime-duration-anomalies.png
  docs/en/observability/images/monitor-duration-chart.png
  docs/en/observability/images/monitor-status-alert.png
  docs/en/observability/images/monitors-chart.png
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/pings-over-time.png
  docs/en/observability/images/response-durations-alert.png
  docs/en/observability/images/tls-alert.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-alert-connectors.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-connector-duration.png
  docs/en/observability/images/uptime-connector-variables.png
  docs/en/observability/images/uptime-filter-bar.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/images/uptime-status-variables.png
  docs/en/observability/index.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/install-observability.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#167 Add metrics anomaly detection content
  docs/en/observability/images/metrics-history-chart.png
  docs/en/observability/index.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
  docs/en/observability/inspect-metric-anomalies.asciidoc
Labels: 7.10.0, docs, needs_backport

#175 [7.x] Add metrics anomaly detection content (#167)
  docs/en/observability/images/metrics-history-chart.png
  docs/en/observability/index.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
  docs/en/observability/inspect-metric-anomalies.asciidoc
Labels: backport

#172 Update links to Uptime app content
  docs/en/uptime/install.asciidoc
  docs/en/uptime/overview.asciidoc
Labels: 7.10.0

#177 [7.x] Update links (#172)
  docs/en/uptime/install.asciidoc
  docs/en/uptime/overview.asciidoc
Labels: backport

#178 [7.10] Update links (#172)
  docs/en/uptime/install.asciidoc
  docs/en/uptime/overview.asciidoc
Labels: backport

#171 add observer.geo.name for maps and machine learning
  docs/en/observability/ingest-uptime.asciidoc
Labels: docs

#181 [7.10] add observer.geo.name for maps and machine learning (#171)
  docs/en/observability/ingest-uptime.asciidoc
Labels: backport

#180 [7.x] add observer.geo.name for maps and machine learning (#171)
  docs/en/observability/ingest-uptime.asciidoc
Labels: backport

#160 Update endpoint-related terminology
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.10.0, docs, needs_backport

#184 [7.x] Update endpoint-related terminology (#160)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#185 [7.10] Update endpoint-related terminology (#160)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.10.0, backport, docs

#183 Update Readme
  README.md
Labels: docs

#188 Fixes Instrument APM + Adds what's new
  docs/en/observability/index.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/whats-new.asciidoc
Labels: 7.10.0

#190 [7.x] Fixes Instrument APM + Adds what's new (#188)
  docs/en/observability/index.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/whats-new.asciidoc
Labels: backport

#191 [7.10] Fixes Instrument APM + Adds what's new (#188)
  docs/en/observability/index.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/whats-new.asciidoc
Labels: backport

#165 Apply name changes to Fleet docs
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet-overview.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/datasets.png
  docs/en/ingest-management/images/fleet.png
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-enable.png
  docs/en/ingest-management/images/kibana-fleet-enroll.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-yaml.png
  docs/en/ingest-management/images/kibana-fleet-settings.png
  docs/en/ingest-management/images/kibana-fleet-start.png
  docs/en/ingest-management/images/kibana-ingest-manager-configurations-default-with-nginx.png
  docs/en/ingest-management/images/kibana-ingest-manager-datastreams.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-agents.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-enable.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-enrol.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-add-datasource.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-settings.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx.png
  docs/en/ingest-management/images/kibana-ingest-manager-settings.png
  docs/en/ingest-management/images/kibana-ingest-manager-start.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.10.0, 7.11.0, 8.0.0, docs, needs_backport

#194 [7.10] Apply name changes to Fleet docs (#165)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet-overview.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/datasets.png
  docs/en/ingest-management/images/fleet.png
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-enable.png
  docs/en/ingest-management/images/kibana-fleet-enroll.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-yaml.png
  docs/en/ingest-management/images/kibana-fleet-settings.png
  docs/en/ingest-management/images/kibana-fleet-start.png
  docs/en/ingest-management/images/kibana-ingest-manager-configurations-default-with-nginx.png
  docs/en/ingest-management/images/kibana-ingest-manager-datastreams.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-agents.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-enable.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-enrol.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-add-datasource.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-settings.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx.png
  docs/en/ingest-management/images/kibana-ingest-manager-settings.png
  docs/en/ingest-management/images/kibana-ingest-manager-start.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport, docs

#193 [7.x] Apply name changes to Fleet docs (#165)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet-overview.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/datasets.png
  docs/en/ingest-management/images/fleet.png
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-enable.png
  docs/en/ingest-management/images/kibana-fleet-enroll.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-yaml.png
  docs/en/ingest-management/images/kibana-fleet-settings.png
  docs/en/ingest-management/images/kibana-fleet-start.png
  docs/en/ingest-management/images/kibana-ingest-manager-configurations-default-with-nginx.png
  docs/en/ingest-management/images/kibana-ingest-manager-datastreams.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-agents.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-enable.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet-enrol.png
  docs/en/ingest-management/images/kibana-ingest-manager-fleet.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-add-datasource.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx-settings.png
  docs/en/ingest-management/images/kibana-ingest-manager-integrations-nginx.png
  docs/en/ingest-management/images/kibana-ingest-manager-settings.png
  docs/en/ingest-management/images/kibana-ingest-manager-start.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport, docs

#195 Update internal links
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/tail-logs.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: 7.10.0, needs_backport

#197 [7.10] Update links (#195)
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/tail-logs.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#196 [7.x] Update links (#195)
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/tail-logs.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#198 Rename sections in observability guide
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
Labels: 7.10.0, docs

#200 [7.x] Rename sections in observability guide (#198)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
Labels: backport, docs

#201 [7.10] Rename sections in observability guide (#198)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
Labels: backport, docs

#187 Add User Experience docs
  docs/en/observability/images/js-errors.png
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/images/visitor-breakdown.png
  docs/en/observability/images/web-dev-vitals.png
  docs/en/observability/index.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: 7.10.0

#202 [7.x] Add User Experience docs (#187)
  docs/en/observability/images/js-errors.png
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/images/visitor-breakdown.png
  docs/en/observability/images/web-dev-vitals.png
  docs/en/observability/index.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#203 [7.10] Add User Experience docs (#187)
  docs/en/observability/images/js-errors.png
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/images/visitor-breakdown.png
  docs/en/observability/images/web-dev-vitals.png
  docs/en/observability/index.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport
