Repository elastic/observability-docs, pull requests merged in 2020-11, with the labels that each got.

#205 Update get started content
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/install-observability.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/tab-widgets/code.asciidoc
  docs/en/observability/tab-widgets/deploy-ess-stack-widget.asciidoc
  docs/en/observability/tab-widgets/deploy-ess-stack.asciidoc
Labels: 7.10.0

#213 [7.x] Update get started content (#205)
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/install-observability.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/tab-widgets/code.asciidoc
  docs/en/observability/tab-widgets/deploy-ess-stack-widget.asciidoc
  docs/en/observability/tab-widgets/deploy-ess-stack.asciidoc
Labels: backport

#214 [7.10] Update get started content (#205)
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/install-observability.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/tab-widgets/code.asciidoc
  docs/en/observability/tab-widgets/deploy-ess-stack-widget.asciidoc
  docs/en/observability/tab-widgets/deploy-ess-stack.asciidoc
Labels: backport

#219 [7.10] Add a note about Cloud ID (#211)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#218 [7.x] Add a note about Cloud ID (#211)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#217 Fix broken link
  docs/en/observability/monitor-java-app.asciidoc
Labels: 7.10.0, docs

#220 [7.x] Fix broken link (#217)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#221 [7.10] Fix broken link (#217)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#216 Add What's new content for 7.10 release
  docs/en/observability/images/alert-chart-preview.png
  docs/en/observability/images/anomaly-detect-alert.png
  docs/en/observability/images/anomaly-detect-host.png
  docs/en/observability/images/fleet-agents.png
  docs/en/observability/images/log-category-warn.png
  docs/en/observability/images/log-ratio-alerting.png
  docs/en/observability/images/multi-cloud-billing.png
  docs/en/observability/images/obs-overview-ue.png
  docs/en/observability/images/service-inventory.png
  docs/en/observability/images/service-map.png
  docs/en/observability/images/service-maps.png
  docs/en/observability/images/stack-alerts.png
  docs/en/observability/images/synthetic-monitoring.png
  docs/en/observability/whats-new.asciidoc
Labels: 7.10.0, docs

#223 docs: add whats new tagged region
  docs/en/observability/whats-new.asciidoc
Labels: 7.11.0

#224 [7.x] docs: add tagged region (#223)
  docs/en/observability/whats-new.asciidoc
Labels: backport

#226 [7.10] Update what's new links
  docs/en/observability/whats-new.asciidoc
Labels: 7.10.0

#212 Update installation and standalone agent content
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
Labels: 7.10.0, docs

#229 [7.x] Update installation and standalone agent content (#212)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport, docs

#230 [7.10] Update installation and standalone agent content (#212)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport, docs

#207 Update Fleet quick start guide
  docs/en/ingest-management/agent-standalone.asciidoc
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet-limitations.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/host-metrics.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.10.0, docs, needs_backport

#232 [7.10] Update Fleet quick start guide (#207)
  docs/en/ingest-management/agent-standalone.asciidoc
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet-limitations.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/host-metrics.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#231 [7.x] Update Fleet quick start guide (#207)
  docs/en/ingest-management/agent-standalone.asciidoc
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet-limitations.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/host-metrics.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#234 [7.10] docs: add CWV release date
  docs/en/observability/whats-new.asciidoc
Labels: 7.10.0

#209 docs: Synthetics monitoring
  docs/en/observability/images/obs-overview-ue.png
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/synthetic-app-error.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/images/synthetic-app-overview.png
  docs/en/observability/images/synthetics-overview.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: 7.10.0

#236 [7.x] docs: Synthetic monitoring (#209)
  docs/en/observability/images/obs-overview-ue.png
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/synthetic-app-error.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/images/synthetic-app-overview.png
  docs/en/observability/images/synthetics-overview.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#237 [7.10] docs: Synthetic monitoring (#209)
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/synthetic-app-error.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/images/synthetic-app-overview.png
  docs/en/observability/images/synthetics-overview.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#228 [7.10] Update limits based on effort for 7.10 (#225)
  docs/en/ingest-management/fleet-limitations.asciidoc
Labels: backport

#233 Cleanup Fleet and Agent docs
  docs/en/ingest-management/agent-standalone.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.10.0, docs

#242 [7.x] Cleanup Fleet and Agent docs (#233)
  docs/en/ingest-management/agent-standalone.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport, docs

#243 [7.10] Cleanup Fleet and Agent docs (#233)
  docs/en/ingest-management/agent-standalone.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport, docs

#244 Fix problems in Fleet docs found during testing
  docs/en/ingest-management/getting-started.asciidoc
Labels: 7.10.0, docs

#246 [7.x] Fix problems in Fleet docs found during testing (#244)
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport, docs

#247 [7.10] Fix problems in Fleet docs found during testing (#244)
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport, docs

#250 docs: update UE discuss link
  docs/en/observability/user-experience.asciidoc
Labels: 7.10.0, bug

#251 [7.x] docs: update UE discuss link (#250)
  docs/en/observability/user-experience.asciidoc
Labels: backport

#252 [7.10] docs: update UE discuss link (#250)
  docs/en/observability/user-experience.asciidoc
Labels: backport

#249 [DOCS] Adds note on how to update custom rules of Metric anomaly jobs
  docs/en/observability/images/ml-custom-rules.jpg
  docs/en/observability/inspect-metric-anomalies.asciidoc
Labels: 7.10.0, 7.11.0, 8.0.0, docs

#253 [7.x] [DOCS] Adds note on how to update custom rules of Metric anomaly jobs (#249)
  docs/en/observability/images/ml-custom-rules.jpg
  docs/en/observability/inspect-metric-anomalies.asciidoc
Labels: 7.11.0, backport, docs

#254 [7.10] [DOCS] Adds note on how to update custom rules of Metric anomaly jobs (#249)
  docs/en/observability/images/ml-custom-rules.jpg
  docs/en/observability/inspect-metric-anomalies.asciidoc
Labels: 7.10.0, backport, docs

#227 [7.x] Update limits based on effort for 7.10 (#225)
  docs/en/ingest-management/fleet-limitations.asciidoc
Labels: backport

#248 Apply fixes found during MacOS testing
  docs/en/ingest-management/fleet-overview.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
Labels: 7.10.0, docs

#255 [7.x] Apply fixes found during MacOS testing (#248)
  docs/en/ingest-management/fleet-overview.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
Labels: 7.11.0, backport, docs

#256 [7.10] Apply fixes found during MacOS testing (#248)
  docs/en/ingest-management/fleet-overview.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
Labels: 7.10.0, backport, docs

#238 Add security and comms info to agent docs
  docs/en/ingest-management/faq.asciidoc
Labels: 7.10.0, docs

#261 [7.x] Add security and comms info to agent docs (#238)
  docs/en/ingest-management/faq.asciidoc
Labels: backport, docs

#262 [7.10] Add security and comms info to agent docs (#238)
  docs/en/ingest-management/faq.asciidoc
Labels: backport, docs

#257 Remove redirects
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.10.0, docs

#264 [7.x] Remove redirects (#257)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#265 [7.10] Remove redirects (#257)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#263 Add fixes from deb/rpm testing
  docs/en/ingest-management/getting-started.asciidoc
Labels: 7.10.0, docs

#267 [7.10] Add fixes from deb/rpm testing (#263)
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport

#266 [7.x] Add fixes from deb/rpm testing (#263)
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport

#260 Update synthetics quickstart
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: 7.10.0

#269 [7.10] Update synthetics quickstart (#260)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#268 [7.x] Update synthetics quickstart (#260)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport
