Repository elastic/observability-docs, pull requests merged in 2020-12, with the labels that each got.

#279 Use un-authenticated git URL for synthetics examples
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: 7.10.0

#281 [7.10] Use un-authenticated git URL for synthetics examples (#279)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#280 [7.x] Use un-authenticated git URL for synthetics examples (#279)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#283 docs: make it clear that docker is the only option for synthetics
  docs/en/observability/synthetic-monitoring.asciidoc
Labels: 7.10.0

#286 [7.10] docs: make it clear that docker is the only option (#283)
  docs/en/observability/synthetic-monitoring.asciidoc
Labels: backport

#285 [7.x] docs: make it clear that docker is the only option (#283)
  docs/en/observability/synthetic-monitoring.asciidoc
Labels: backport

#291 Add settings info for metrics alerts
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: 7.10.0, docs

#296 [7.10] Add settings info (#291)
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#295 [7.x] Add settings info (#291)
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#289 Clarify where to run examples
  docs/en/observability/synthetics-create-test.asciidoc
Labels: enhancement

#298 [7.10] Clarify where to run examples (#289)
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport

#297 [7.x] Clarify where to run examples (#289)
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport

#302 docs: add APM landing page & update arch diagram
  docs/en/observability/apm.asciidoc
  docs/en/observability/images/apm-app-landing.png
  docs/en/observability/images/observability.png
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-introduction.asciidoc
Labels: 7.10.0

#305 [7.10] docs: add APM landing page & update arch diagram (#302)
  docs/en/observability/apm.asciidoc
  docs/en/observability/images/apm-app-landing.png
  docs/en/observability/images/observability.png
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-introduction.asciidoc
Labels: backport

#304 [7.11] docs: add APM landing page & update arch diagram (#302)
  docs/en/observability/apm.asciidoc
  docs/en/observability/images/apm-app-landing.png
  docs/en/observability/images/observability.png
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-introduction.asciidoc
Labels: backport

#303 [7.x] docs: add APM landing page & update arch diagram (#302)
  docs/en/observability/apm.asciidoc
  docs/en/observability/images/apm-app-landing.png
  docs/en/observability/images/observability.png
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-introduction.asciidoc
Labels: backport

#307 Move Elastic Agent docs to the observability-docs repo
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-dynamic-inputs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-reference-yaml.yml
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/redirects.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
  docs/en/ingest-management/elastic-agent/start-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/stop-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/unenroll-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/fleet-agents.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/tab-widgets/download-widget.asciidoc
  docs/en/ingest-management/tab-widgets/download.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout-widget.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
  docs/en/ingest-management/tab-widgets/install-widget.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
  docs/en/ingest-management/tab-widgets/run-standalone-widget.asciidoc
  docs/en/ingest-management/tab-widgets/run-standalone.asciidoc
  docs/en/ingest-management/tab-widgets/start-widget.asciidoc
  docs/en/ingest-management/tab-widgets/start.asciidoc
  docs/en/ingest-management/tab-widgets/stop-widget.asciidoc
  docs/en/ingest-management/tab-widgets/stop.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall-widget.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Labels: docs

#308 Move v7.8 Elastic Agent docs to the observability-docs repo
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration-example.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent_configuration_example.yml
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/stop-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: 7.8.0, docs

#312 Move 7.10 Elastic Agent docs to the observability-docs repo
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-dynamic-inputs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-reference-yaml.yml
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/redirects.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
  docs/en/ingest-management/elastic-agent/start-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/stop-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/unenroll-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/fleet-agents.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/tab-widgets/download-widget.asciidoc
  docs/en/ingest-management/tab-widgets/download.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout-widget.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
  docs/en/ingest-management/tab-widgets/install-widget.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
  docs/en/ingest-management/tab-widgets/run-standalone-widget.asciidoc
  docs/en/ingest-management/tab-widgets/run-standalone.asciidoc
  docs/en/ingest-management/tab-widgets/start-widget.asciidoc
  docs/en/ingest-management/tab-widgets/start.asciidoc
  docs/en/ingest-management/tab-widgets/stop-widget.asciidoc
  docs/en/ingest-management/tab-widgets/stop.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall-widget.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Labels: 7.10.0, docs

#310 [7.x] Move Elastic Agent docs to the observability-docs repo (#307)
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-dynamic-inputs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-reference-yaml.yml
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/redirects.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
  docs/en/ingest-management/elastic-agent/start-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/stop-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/unenroll-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/fleet-agents.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/tab-widgets/download-widget.asciidoc
  docs/en/ingest-management/tab-widgets/download.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout-widget.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
  docs/en/ingest-management/tab-widgets/install-widget.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
  docs/en/ingest-management/tab-widgets/run-standalone-widget.asciidoc
  docs/en/ingest-management/tab-widgets/run-standalone.asciidoc
  docs/en/ingest-management/tab-widgets/start-widget.asciidoc
  docs/en/ingest-management/tab-widgets/start.asciidoc
  docs/en/ingest-management/tab-widgets/stop-widget.asciidoc
  docs/en/ingest-management/tab-widgets/stop.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall-widget.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Labels: backport, v7.12.0

#311 [7.11] Move Elastic Agent docs to the observability-docs repo (#307)
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-dynamic-inputs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-reference-yaml.yml
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/redirects.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
  docs/en/ingest-management/elastic-agent/start-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/stop-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/unenroll-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/fleet-agents.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/tab-widgets/download-widget.asciidoc
  docs/en/ingest-management/tab-widgets/download.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout-widget.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
  docs/en/ingest-management/tab-widgets/install-widget.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
  docs/en/ingest-management/tab-widgets/run-standalone-widget.asciidoc
  docs/en/ingest-management/tab-widgets/run-standalone.asciidoc
  docs/en/ingest-management/tab-widgets/start-widget.asciidoc
  docs/en/ingest-management/tab-widgets/start.asciidoc
  docs/en/ingest-management/tab-widgets/stop-widget.asciidoc
  docs/en/ingest-management/tab-widgets/stop.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall-widget.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Labels: backport, v7.12.0

#313 docs: Create shared directory and add APM Kubernetes info
  README.md
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/shared/configure-apm-agents/content.asciidoc
  docs/en/shared/configure-apm-agents/widget.asciidoc
  docs/en/shared/configure-apm-server/content.asciidoc
  docs/en/shared/configure-apm-server/widget.asciidoc
  docs/en/shared/install-apm-agents-kube/dotnet.asciidoc
  docs/en/shared/install-apm-agents-kube/go.asciidoc
  docs/en/shared/install-apm-agents-kube/java.asciidoc
  docs/en/shared/install-apm-agents-kube/nodejs.asciidoc
  docs/en/shared/install-apm-agents-kube/python.asciidoc
  docs/en/shared/install-apm-agents-kube/ruby.asciidoc
  docs/en/shared/install-apm-agents-kube/widget.asciidoc
  docs/en/shared/install-apm-agents/content.asciidoc
  docs/en/shared/install-apm-agents/widget.asciidoc
  docs/en/shared/open-kibana/content.asciidoc
  docs/en/shared/open-kibana/widget.asciidoc
  docs/en/shared/spin-up-the-stack/content.asciidoc
  docs/en/shared/spin-up-the-stack/widget.asciidoc
  docs/en/shared/tab-widget-code/code.asciidoc
  docs/en/templates/tutorial-template.asciidoc
Labels: docs

#317 docs: APM kubernetes feedback feedback
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s.asciidoc
  docs/en/shared/install-apm-agents-kube/java.asciidoc
Labels: docs

#314 [7.x] docs: Create shared directory and add APM Kubernetes info (#313)
  README.md
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/shared/configure-apm-agents/content.asciidoc
  docs/en/shared/configure-apm-agents/widget.asciidoc
  docs/en/shared/configure-apm-server/content.asciidoc
  docs/en/shared/configure-apm-server/widget.asciidoc
  docs/en/shared/install-apm-agents-kube/dotnet.asciidoc
  docs/en/shared/install-apm-agents-kube/go.asciidoc
  docs/en/shared/install-apm-agents-kube/java.asciidoc
  docs/en/shared/install-apm-agents-kube/nodejs.asciidoc
  docs/en/shared/install-apm-agents-kube/python.asciidoc
  docs/en/shared/install-apm-agents-kube/ruby.asciidoc
  docs/en/shared/install-apm-agents-kube/widget.asciidoc
  docs/en/shared/install-apm-agents/content.asciidoc
  docs/en/shared/install-apm-agents/widget.asciidoc
  docs/en/shared/open-kibana/content.asciidoc
  docs/en/shared/open-kibana/widget.asciidoc
  docs/en/shared/spin-up-the-stack/content.asciidoc
  docs/en/shared/spin-up-the-stack/widget.asciidoc
  docs/en/shared/tab-widget-code/code.asciidoc
Labels: backport

#315 [7.11] docs: Create shared directory and add APM Kubernetes info (#313)
  README.md
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/shared/configure-apm-agents/content.asciidoc
  docs/en/shared/configure-apm-agents/widget.asciidoc
  docs/en/shared/configure-apm-server/content.asciidoc
  docs/en/shared/configure-apm-server/widget.asciidoc
  docs/en/shared/install-apm-agents-kube/dotnet.asciidoc
  docs/en/shared/install-apm-agents-kube/go.asciidoc
  docs/en/shared/install-apm-agents-kube/java.asciidoc
  docs/en/shared/install-apm-agents-kube/nodejs.asciidoc
  docs/en/shared/install-apm-agents-kube/python.asciidoc
  docs/en/shared/install-apm-agents-kube/ruby.asciidoc
  docs/en/shared/install-apm-agents-kube/widget.asciidoc
  docs/en/shared/install-apm-agents/content.asciidoc
  docs/en/shared/install-apm-agents/widget.asciidoc
  docs/en/shared/open-kibana/content.asciidoc
  docs/en/shared/open-kibana/widget.asciidoc
  docs/en/shared/spin-up-the-stack/content.asciidoc
  docs/en/shared/spin-up-the-stack/widget.asciidoc
  docs/en/shared/tab-widget-code/code.asciidoc
Labels: backport

#316 [7.10] docs: Create shared directory and add APM Kubernetes info (#313)
  README.md
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/shared/configure-apm-agents/content.asciidoc
  docs/en/shared/configure-apm-agents/widget.asciidoc
  docs/en/shared/configure-apm-server/content.asciidoc
  docs/en/shared/configure-apm-server/widget.asciidoc
  docs/en/shared/install-apm-agents-kube/dotnet.asciidoc
  docs/en/shared/install-apm-agents-kube/go.asciidoc
  docs/en/shared/install-apm-agents-kube/java.asciidoc
  docs/en/shared/install-apm-agents-kube/nodejs.asciidoc
  docs/en/shared/install-apm-agents-kube/python.asciidoc
  docs/en/shared/install-apm-agents-kube/ruby.asciidoc
  docs/en/shared/install-apm-agents-kube/widget.asciidoc
  docs/en/shared/install-apm-agents/content.asciidoc
  docs/en/shared/install-apm-agents/widget.asciidoc
  docs/en/shared/open-kibana/content.asciidoc
  docs/en/shared/open-kibana/widget.asciidoc
  docs/en/shared/spin-up-the-stack/content.asciidoc
  docs/en/shared/spin-up-the-stack/widget.asciidoc
  docs/en/shared/tab-widget-code/code.asciidoc
Labels: backport
