Repository elastic/observability-docs, pull requests merged in 2021-02, with the labels that each got.

#360 Update images for 7.11 release
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/synthetics-visualize.asciidoc
Labels: 7.11.0, docs

#364 [7.x] Update images (#360)
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/synthetics-visualize.asciidoc
Labels: backport

#365 [7.11] Update images (#360)
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/synthetics-visualize.asciidoc
Labels: backport

#363 Update Fleet quick start steps and screens for 7.11
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/host-metrics.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
Labels: 7.11.0, docs

#368 [7.11] Update Fleet quick start steps and screens for 7.11 (#363)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/host-metrics.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
Labels: 7.11.0, backport, docs

#367 [7.x] Update Fleet quick start steps and screens for 7.11 (#363)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/host-metrics.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
Labels: backport, docs, v7.12.0

#366 Add What's new content for 7.11 release
  docs/en/observability/images/apm-logs.png
  docs/en/observability/images/apm-service-overview.png
  docs/en/observability/images/aws-fargate-metrics.png
  docs/en/observability/images/elastic-agent-logs.png
  docs/en/observability/images/elastic-agent.png
  docs/en/observability/images/enhanced-host-metrics.png
  docs/en/observability/images/runtime-fields.png
  docs/en/observability/images/synthetics-waterfall-chart.png
  docs/en/observability/whats-new.asciidoc
Labels: 7.11.0, docs

#370 Remove sync time across apps content from What's new
  docs/en/observability/whats-new.asciidoc
Labels: 7.11.0, docs

#375 [master] docs: fix Filebeat config step 5 (#373)
  docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
Labels: backport

#376 [7.x] docs: fix Filebeat config step 5 (#373)
  docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
Labels: backport

#374 Add troubleshooting problem about telemetry issue in 7.11
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: 7.11.0, docs

#377 [7.x] Add troubleshooting problem about telemetry issue in 7.11 (#374)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport, docs

#378 [7.11] Add troubleshooting problem about telemetry issue in 7.11 (#374)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport, docs

#372 Adds short blurb with pointer about agent self-protection
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: 7.11.0, docs

#381 [7.11] Adds short blurb with pointer about agent self-protection (#372)
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: backport, docs

#380 [7.x] Adds short blurb with pointer about agent self-protection (#372)
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: backport, docs

#390 Synthetics: Add 7.12 updates
  docs/en/observability/images/synthetics-waterfall.png
  docs/en/observability/images/url-link-icon.png
  docs/en/observability/images/waterfall-filter.png
  docs/en/observability/synthetics-visualize.asciidoc
Labels: docs, v7.12.0

#392 [7.x] Synthetics: Add 7.12 updates (#390)
  docs/en/observability/images/synthetics-waterfall.png
  docs/en/observability/images/url-link-icon.png
  docs/en/observability/images/waterfall-filter.png
  docs/en/observability/synthetics-visualize.asciidoc
Labels: backport

#396 Update backports to auto-merge after checks pass
  .backportrc.json
Labels: docs, enhancement

#393 docs: add PHP agent info to k8s tutorial
  docs/en/shared/install-apm-agents-kube/php.asciidoc
  docs/en/shared/install-apm-agents-kube/widget.asciidoc
Labels: docs, v7.12.0

#398 [7.x] docs: add PHP agent info to k8s tutorial (#393)
  docs/en/shared/install-apm-agents-kube/php.asciidoc
  docs/en/shared/install-apm-agents-kube/widget.asciidoc
Labels: backport

#399 [7.12] docs: add PHP agent info to k8s tutorial (#393)
  docs/en/shared/install-apm-agents-kube/php.asciidoc
  docs/en/shared/install-apm-agents-kube/widget.asciidoc
Labels: backport

#407 [7.x] Small FAQ updates for Fleet / Agent based on recent feature work (#403)
  docs/en/ingest-management/faq.asciidoc
Labels: backport

#408 [7.12] Small FAQ updates for Fleet / Agent based on recent feature work (#403)
  docs/en/ingest-management/faq.asciidoc
Labels: backport

#409 [7.11] Small FAQ updates for Fleet / Agent based on recent feature work (#403)
  docs/en/ingest-management/faq.asciidoc
Labels: backport

#404 Metrics app alerts: 7.12 updates
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/alert-action-types.png
  docs/en/observability/images/anomaly-variables.png
  docs/en/observability/images/infra-anomaly-conditions.png
  docs/en/observability/images/inventory-alert.png
  docs/en/observability/images/inventory-create-alert.png
  docs/en/observability/images/metrics-alert.png
  docs/en/observability/images/run-when-selection.png
  docs/en/observability/infrastructure-anomaly-alert.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
Labels: docs, v7.12.0

#412 [7.12] Metrics app alerts: 7.12 updates (#404)
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/alert-action-types.png
  docs/en/observability/images/anomaly-variables.png
  docs/en/observability/images/infra-anomaly-conditions.png
  docs/en/observability/images/inventory-alert.png
  docs/en/observability/images/inventory-create-alert.png
  docs/en/observability/images/metrics-alert.png
  docs/en/observability/images/run-when-selection.png
  docs/en/observability/infrastructure-anomaly-alert.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
Labels: backport

#411 [7.x] Metrics app alerts: 7.12 updates (#404)
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/alert-action-types.png
  docs/en/observability/images/anomaly-variables.png
  docs/en/observability/images/infra-anomaly-conditions.png
  docs/en/observability/images/inventory-alert.png
  docs/en/observability/images/inventory-create-alert.png
  docs/en/observability/images/metrics-alert.png
  docs/en/observability/images/run-when-selection.png
  docs/en/observability/infrastructure-anomaly-alert.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
Labels: backport

#414 [DOCS] Updates Kibana path for Metricbeat
  docs/en/observability/ingest-metrics.asciidoc
Labels: docs, v7.11.0

#413 [DOCS] Updates Kibana path for Filebeat
  docs/en/observability/ingest-logs.asciidoc
Labels: docs, v7.11.0

#420 [7.12] [DOCS] Updates Kibana main menu path (#413)
  docs/en/observability/ingest-logs.asciidoc
Labels: backport

#415 [master] [DOCS] Updates Kibana path for Metricbeat (#414)
  docs/en/observability/ingest-metrics.asciidoc
Labels: backport

#416 [7.x] [DOCS] Updates Kibana path for Metricbeat (#414)
  docs/en/observability/ingest-metrics.asciidoc
Labels: backport

#417 [7.12] [DOCS] Updates Kibana path for Metricbeat (#414)
  docs/en/observability/ingest-metrics.asciidoc
Labels: backport

#418 [master] [DOCS] Updates Kibana main menu path (#413)
  docs/en/observability/ingest-logs.asciidoc
Labels: backport

#419 [7.x] [DOCS] Updates Kibana main menu path (#413)
  docs/en/observability/ingest-logs.asciidoc
Labels: backport
