Repository elastic/observability-docs, pull requests merged in 2021-06, with the labels that each got.

#756 [7.13] Update troubleshooting.asciidoc (#734)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#755 [7.x] Update troubleshooting.asciidoc (#734)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#754 [7.13] Document Agent/Fleet Server environment variables (#671)
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Labels: backport

#753 [7.x] Document Agent/Fleet Server environment variables (#671)
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Labels: backport

#759 update name to Elastic Cloud agent
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: v7.13.1, v7.14.0

#744 Adds 7.13.1 Elastic Agent and Fleet release notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: Team:Agent, Team:Fleet, v7.13.1

#742 Add note about removing system extension during uninstall
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
Labels: docs, v7.13.0

#763 [7.x] Adds 7.13.1 Elastic Agent and Fleet release notes (#744)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#766 [7.13] Add note about removing system extension during uninstall (#742)
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
Labels: backport

#765 [7.x] Add note about removing system extension during uninstall (#742)
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
Labels: backport

#764 [7.13] Adds 7.13.1 Elastic Agent and Fleet release notes (#744)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#725 Logs app: Add index pattern content
  docs/en/observability/configure-logs-sources.asciidoc
Labels: docs, v7.13.0

#767 [7.13] Logs app: Add index pattern content (#725)
  docs/en/observability/configure-logs-sources.asciidoc
Labels: backport

#768 [7.x] Logs app: Add index pattern content (#725)
  docs/en/observability/configure-logs-sources.asciidoc
Labels: backport

#777 [7.13] Update monitor-aws.asciidoc (#652)
  docs/en/observability/monitor-aws.asciidoc
Labels: backport

#776 [7.x] Update monitor-aws.asciidoc (#652)
  docs/en/observability/monitor-aws.asciidoc
Labels: backport

#772 Fleet troubleshooting: update Kibana config file settings
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: docs, v7.13.0

#781 [7.13] Fleet troubleshooting: update Kibana config file settings (#772)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#780 [7.x] Fleet troubleshooting: update Kibana config file settings (#772)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#761 [7.x] update name to Elastic Cloud agent (#759)
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: backport

#762 [7.13] update name to Elastic Cloud agent (#759)
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: backport

#785 [7.x] Update troubleshooting.asciidoc (ef5a03de)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#787 Add Fleet and Agent release notes for 7.13.2
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: v7.13.2

#779 [Docs] Update cross-document links to Kibana Alerting docs
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/observability-ui.asciidoc
Labels: v7.13.0

#790 [7.x] [Docs] Update cross-document links to Kibana Alerting docs (#779)
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#789 [7.13] Add release notes for 7.13.2 (#787)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#788 [7.x] Add release notes for 7.13.2 (#787)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#778 Add ECE 2.10 requirements for Fleet Server
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: Team:Fleet, docs, v7.13.0

#796 [7.13] Add ECE 2.10 requirements for Fleet Server (#778)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#797 Fix formatting error caused by addition of tagged region
  docs/en/ingest-management/getting-started.asciidoc
Labels: bug, docs

#800 [7.x] Fix formatting error (#797)
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport

#801 [7.13] Fix formatting error (#797)
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport

#798 Document how to use custom certs with Fleet Server
  docs/en/ingest-management/images/ca.png
  docs/en/ingest-management/images/fleet-server-certs.png
  docs/en/ingest-management/images/fleet-settings-ssl.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
Labels: Team:Fleet

#810 [7.13] Document how to use custom certs with Fleet Server (#798)
  docs/en/ingest-management/images/ca.png
  docs/en/ingest-management/images/fleet-server-certs.png
  docs/en/ingest-management/images/fleet-settings-ssl.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
Labels: backport

#809 [7.x] Document how to use custom certs with Fleet Server (#798)
  docs/en/ingest-management/images/ca.png
  docs/en/ingest-management/images/fleet-server-certs.png
  docs/en/ingest-management/images/fleet-settings-ssl.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
Labels: backport

#812 [7.x] [Logs] Add some performance recommendations for the log threshold rule type (#804)
  docs/en/observability/logs-threshold-alert.asciidoc
Labels: backport

#813 [7.x] Hide docs for mamanaged agent on k8s (#799)
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: backport

#814 [7.13] Hide docs for mamanaged agent on k8s (#799)
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: backport

#816 [Uptime] Update TLS alert documentation to reflect current action variable image
  docs/en/observability/images/uptime-status-variables.png
Labels: Team:Uptime, docs, v7.14.0

#818 [7.x] [Uptime] - TLS certificate status alert - update TLS action variable image (#816)
  docs/en/observability/images/uptime-status-variables.png
Labels: backport

#806 [Synthetics] Docs on secrets and params
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
Labels: Team:Uptime, enhancement, v7.14.0

#822 Fix uninstall commands
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Labels: Team:Docs, docs, v7.13.2, v7.14.0

#828 [7.13] Fix uninstall commands (#822)
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Labels: backport

#827 [7.14] Fix uninstall commands (#822)
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Labels: backport
