Repository elastic/observability-docs, pull requests merged in 2021-01, with the labels that each got.

#148 Add info about namespace length limit
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: 7.10.0, 8.0.0, docs

#322 [7.10] Add info about namespace length limit (#148)
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: backport

#321 [7.11] Add info about namespace length limit (#148)
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: backport

#320 [7.x] Add info about namespace length limit (#148)
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: backport

#151 Add Kubernetes monitoring docs
  docs/en/observability/monitor-k8s/diagnose-k8s-bottlenecks.asciidoc
  docs/en/observability/monitor-k8s/images/apm-app-kubernetes-filter.png
  docs/en/observability/monitor-k8s/images/k8s-monitoring-architecture.png
  docs/en/observability/monitor-k8s/images/k8s-overview.png
  docs/en/observability/monitor-k8s/images/log-stream.png
  docs/en/observability/monitor-k8s/images/metadata-processors.png
  docs/en/observability/monitor-k8s/images/metrics-explorer.png
  docs/en/observability/monitor-k8s/images/metrics-inventory.png
  docs/en/observability/monitor-k8s/images/spring-apm-app-2.png
  docs/en/observability/monitor-k8s/images/system-overview.png
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-metrics.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-network.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-overview.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-uptime.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s.asciidoc
  docs/en/observability/tutorials.asciidoc
  docs/en/shared/install-apm-agents-kube/dotnet.asciidoc
  docs/en/shared/install-apm-agents-kube/java.asciidoc
Labels: 7.10.0, docs

#324 docs: Add quickstart videos
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: 7.10.0, 7.11.0

#326 [7.x] Add Kubernetes monitoring docs (#151)
  docs/en/observability/monitor-k8s/diagnose-k8s-bottlenecks.asciidoc
  docs/en/observability/monitor-k8s/images/apm-app-kubernetes-filter.png
  docs/en/observability/monitor-k8s/images/k8s-monitoring-architecture.png
  docs/en/observability/monitor-k8s/images/k8s-overview.png
  docs/en/observability/monitor-k8s/images/log-stream.png
  docs/en/observability/monitor-k8s/images/metadata-processors.png
  docs/en/observability/monitor-k8s/images/metrics-explorer.png
  docs/en/observability/monitor-k8s/images/metrics-inventory.png
  docs/en/observability/monitor-k8s/images/spring-apm-app-2.png
  docs/en/observability/monitor-k8s/images/system-overview.png
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-metrics.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-network.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-overview.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-uptime.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s.asciidoc
  docs/en/observability/tutorials.asciidoc
  docs/en/shared/install-apm-agents-kube/dotnet.asciidoc
  docs/en/shared/install-apm-agents-kube/java.asciidoc
Labels: backport, v7.12.0

#327 [7.11] Add Kubernetes monitoring docs (#151)
  docs/en/observability/monitor-k8s/diagnose-k8s-bottlenecks.asciidoc
  docs/en/observability/monitor-k8s/images/apm-app-kubernetes-filter.png
  docs/en/observability/monitor-k8s/images/k8s-monitoring-architecture.png
  docs/en/observability/monitor-k8s/images/k8s-overview.png
  docs/en/observability/monitor-k8s/images/log-stream.png
  docs/en/observability/monitor-k8s/images/metadata-processors.png
  docs/en/observability/monitor-k8s/images/metrics-explorer.png
  docs/en/observability/monitor-k8s/images/metrics-inventory.png
  docs/en/observability/monitor-k8s/images/spring-apm-app-2.png
  docs/en/observability/monitor-k8s/images/system-overview.png
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-metrics.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-network.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-overview.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-uptime.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s.asciidoc
  docs/en/observability/tutorials.asciidoc
  docs/en/shared/install-apm-agents-kube/dotnet.asciidoc
  docs/en/shared/install-apm-agents-kube/java.asciidoc
Labels: 7.11.0, backport

#330 [7.10] docs: Add quickstart videos (#324)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#329 [7.11] docs: Add quickstart videos (#324)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#328 [7.x] docs: Add quickstart videos (#324)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#325 Uptime 7.11 doc updates
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/images/synthetic-app-overview.png
  docs/en/observability/images/synthetics-waterfall.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: 7.11.0, docs

#336 [7.11] Uptime 7.11 doc updates (#325)
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/images/synthetic-app-overview.png
  docs/en/observability/images/synthetics-waterfall.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#335 [7.x] Uptime 7.11 doc updates (#325)
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/images/monitors-list.png
  docs/en/observability/images/synthetic-app-journey.png
  docs/en/observability/images/synthetic-app-overview.png
  docs/en/observability/images/synthetics-waterfall.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#331 Document enhanced host metrics
  docs/en/observability/images/logs-overlay.png
  docs/en/observability/images/metadata-overlay.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/images/processes-overlay.png
  docs/en/observability/monitor-servers.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
Labels: 7.11.0, docs

#337 [7.x] Document enhanced host metrics (#331)
  docs/en/observability/images/logs-overlay.png
  docs/en/observability/images/metadata-overlay.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/images/processes-overlay.png
  docs/en/observability/monitor-servers.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
Labels: backport

#338 [7.11] Document enhanced host metrics (#331)
  docs/en/observability/images/logs-overlay.png
  docs/en/observability/images/metadata-overlay.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/images/processes-overlay.png
  docs/en/observability/monitor-servers.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
Labels: backport

#340 [7.x] Update snippet for cloning and running the synthetics-quickstart (#339)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#341 [7.11] Update snippet for cloning and running the synthetics-quickstart (#339)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#342 [7.10] Update snippet for cloning and running the synthetics-quickstart (#339)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#347 Hardcode synthetics docker image to {minor}.0 (#346)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#348 [7.x] hardcode-synthetics-docker-image-to-7.10.0 (#346)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#349 [7.11] hardcode-synthetics-docker-image-to-7.10.0 (#346)
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#350 Conditionally display videos in current version
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: 7.10.0, blocked, docs

#344 Add privileges required to run Elastic Agent standalone
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
Labels: 7.10.0, 7.11.0, docs, needs_backport

#354 [7.x] Add privileges required to run Elastic Agent standalone (#344)
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
Labels: backport, docs

#356 [7.10] Add privileges required to run Elastic Agent standalone (#344)
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
Labels: backport, docs

#355 [7.11] Add privileges required to run Elastic Agent standalone (#344)
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
Labels: backport, docs

#353 [7.10] docs: conditionally display videos in obs-docs (#350)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#352 [7.11] docs: conditionally display videos in obs-docs (#350)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#351 [7.x] docs: conditionally display videos in obs-docs (#350)
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport

#343 Update FAQ info about agent policies
  docs/en/ingest-management/faq.asciidoc
Labels: 7.10.0, 7.11.0, docs, needs_backport

#357 [7.x] Update FAQ info about agent policies (#343)
  docs/en/ingest-management/faq.asciidoc
Labels: backport, docs

#358 [7.11] Update FAQ info about agent policies (#343)
  docs/en/ingest-management/faq.asciidoc
Labels: backport, docs

#359 [7.10] Update FAQ info about agent policies (#343)
  docs/en/ingest-management/faq.asciidoc
Labels: backport, docs
