Repository elastic/observability-docs, pull requests merged in 2021-09, with the labels that each got.

#1010 Add skeleton files for 7.14.1 release notes
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: Team:Agent, Team:Fleet

#1015 [7.x] Add skeleton files for 7.14.1 release notes (#1010)
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#1017 [7.14] Add skeleton files for 7.14.1 release notes (#1010)
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#1016 [7.15] Add skeleton files for 7.14.1 release notes (#1010)
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#1020 Update Fleet Server docs with link to related ECE info
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: docs, Team:Fleet, v7.14.0, v7.15.0

#1026 [7.x] Update Fleet Server docs with link to related ECE info (#1020)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#1027 [7.15] Update Fleet Server docs with link to related ECE info (#1020)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#1028 [7.14] Update Fleet Server docs with link to related ECE info (#1020)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#1024 [Metrics UI] Update Metric Threshold Alert
  docs/en/observability/images/alert-preview-metric.png
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: docs, v8.0.0, v7.15.0

#1033 [7.x] [Metrics UI] Update Metric Threshold Alert (#1024)
  docs/en/observability/images/alert-preview-metric.png
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#1034 [7.15] [Metrics UI] Update Metric Threshold Alert (#1024)
  docs/en/observability/images/alert-preview-metric.png
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#1038 [7.15] Integrations developer guide (#769)
  docs/en/integrations/air-gapped.asciidoc
  docs/en/integrations/asset-testing.asciidoc
  docs/en/integrations/build-integration.asciidoc
  docs/en/integrations/dashboards.asciidoc
  docs/en/integrations/elastic-package.asciidoc
  docs/en/integrations/index.asciidoc
  docs/en/integrations/integration-example.asciidoc
  docs/en/integrations/package-spec.asciidoc
  docs/en/integrations/pipeline-testing.asciidoc
  docs/en/integrations/publish-integration.asciidoc
  docs/en/integrations/quick-start.asciidoc
  docs/en/integrations/static-testing.asciidoc
  docs/en/integrations/system-testing.asciidoc
  docs/en/integrations/testing.asciidoc
  docs/en/integrations/what-is-an-integration.asciidoc
Labels: backport

#1037 [7.x] Integrations developer guide (#769)
  docs/en/integrations/air-gapped.asciidoc
  docs/en/integrations/asset-testing.asciidoc
  docs/en/integrations/build-integration.asciidoc
  docs/en/integrations/dashboards.asciidoc
  docs/en/integrations/elastic-package.asciidoc
  docs/en/integrations/index.asciidoc
  docs/en/integrations/integration-example.asciidoc
  docs/en/integrations/package-spec.asciidoc
  docs/en/integrations/pipeline-testing.asciidoc
  docs/en/integrations/publish-integration.asciidoc
  docs/en/integrations/quick-start.asciidoc
  docs/en/integrations/static-testing.asciidoc
  docs/en/integrations/system-testing.asciidoc
  docs/en/integrations/testing.asciidoc
  docs/en/integrations/what-is-an-integration.asciidoc
Labels: backport

#1041 [7.14] Update monitor-aws.asciidoc (#1025)
  docs/en/observability/monitor-aws.asciidoc
Labels: backport

#1039 [7.x] Update monitor-aws.asciidoc (#1025)
  docs/en/observability/monitor-aws.asciidoc
Labels: backport

#1040 [7.15] Update monitor-aws.asciidoc (#1025)
  docs/en/observability/monitor-aws.asciidoc
Labels: backport

#1047 Add contact person to issue template
  .github/ISSUE_TEMPLATE/docs-request.md
Labels: Team:Docs

#1021 Add Osquery tab info for host details overlay
  docs/en/observability/images/osquery-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: docs, v7.15.0

#1042 Updates log categorization docs
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/images/log-categories.jpg
  docs/en/observability/images/log-create-categorization-job.jpg
  docs/en/observability/images/log-opened.png
Labels: docs, v8.0.0, v7.16.0, v7.15.0

#1050 [7.15] Add Osquery tab info for host details overlay (#1021)
  docs/en/observability/images/osquery-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: backport

#1048 [7.x] Add Osquery tab info for host details overlay (#1021)
  docs/en/observability/images/osquery-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: backport

#1051 [7.x] Updates log categorization docs (#1042)
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/images/log-categories.jpg
  docs/en/observability/images/log-create-categorization-job.jpg
  docs/en/observability/images/log-opened.png
Labels: docs, backport, v7.16.0

#1052 [7.15] Updates log categorization docs (#1042)
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/images/log-categories.jpg
  docs/en/observability/images/log-create-categorization-job.jpg
  docs/en/observability/images/log-opened.png
Labels: docs, backport, v7.15.0

#1014 Add metrics endpoint debugging info for container docs
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: Team:Docs, v7.14.0, v7.15.0

#1053 [7.x] Add metrics endpoint debugging info for container docs (#1014)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport

#1054 [7.15] Add metrics endpoint debugging info for container docs (#1014)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport

#1055 [7.14] Add metrics endpoint debugging info for container docs (#1014)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport

#1046 [Uptime] Add troubleshooting page for Uptime guide
  docs/en/observability/index.asciidoc
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
Labels: enhancement, Team:Uptime, v7.16.0

#1056 [7.x] [Uptime] Add troubleshooting page for Uptime guide (#1046)
  docs/en/observability/index.asciidoc
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
Labels: backport

#1031 Update beats-agent-comparison.asciidoc
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: Team:Fleet

#1058 Add Endpoint security and Osquery to beats/agent comparison
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: Team:Agent

#1029 Add integrations page and document how to upgrade integrations
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/update-integration.png
  docs/en/ingest-management/images/upgrade-package-policy.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: docs, v7.15.0

#1064 [7.x] Add integrations page and document how to upgrade integrations (#1029)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/update-integration.png
  docs/en/ingest-management/images/upgrade-package-policy.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1065 [7.15] Add integrations page and document how to upgrade integrations (#1029)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/update-integration.png
  docs/en/ingest-management/images/upgrade-package-policy.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1067 [7.x] Add Endpoint security and Osquery to beats/agent comparison (#1058)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1068 [7.15] Add Endpoint security and Osquery to beats/agent comparison (#1058)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1069 [7.14] Add Endpoint security and Osquery to beats/agent comparison (#1058)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1005 [Uptime] [Synthetics Integration] Add synthetic monitoring with fleet and Elastic Agent documentation
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/observability/images/synthetics-agent-policy-select.png
  docs/en/observability/images/synthetics-agent-policy.png
  docs/en/observability/images/synthetics-integration.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: docs, v8.0.0, Team:Docs, Team:Uptime, v7.16.0, v7.15.0

#1074 [7.x] [Uptime] [Synthetics Integration] Add synthetic monitoring with fleet and Elastic Agent documentation (#1005)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/observability/images/synthetics-agent-policy-select.png
  docs/en/observability/images/synthetics-agent-policy.png
  docs/en/observability/images/synthetics-integration.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#1075 [7.15] [Uptime] [Synthetics Integration] Add synthetic monitoring with fleet and Elastic Agent documentation (#1005)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/observability/images/synthetics-agent-policy-select.png
  docs/en/observability/images/synthetics-agent-policy.png
  docs/en/observability/images/synthetics-integration.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#1076 Link to Integrations documentation from overview
  docs/en/ingest-management/overview.asciidoc
Labels: Team:Docs

#1077 [7.x] Link to Integrations documentation from overview (#1076)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1078 [7.15] Link to Integrations documentation from overview (#1076)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1085 [Uptime] Clarify docs around mapping issues / standalone agent
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
Labels: bug

#1086 [7.x] [Uptime] Clarify docs around mapping issues / standalone agent (#1085)
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
Labels: backport

#1082 Add 7.15 whats new
  docs/en/observability/images/7-15-agent-monitoring.png
  docs/en/observability/images/7-15-apm-correlations.png
  docs/en/observability/images/7-15-apm-dependencies.png
  docs/en/observability/images/7-15-apm-failed-correlations.png
  docs/en/observability/images/7-15-apm-service-logs.png
  docs/en/observability/images/7-15-azure.png
  docs/en/observability/images/7-15-gcp.png
  docs/en/observability/images/7-15-jruby.png
  docs/en/observability/images/7-15-osquery.png
  docs/en/observability/images/7-15-upgrade-integrations-1.png
  docs/en/observability/images/7-15-upgrade-integrations-2.png
  docs/en/observability/whats-new.asciidoc
Labels: docs, v7.15.0

#1089 [7.15] Add Fleet Server deployment and scaling docs (#1061)
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/images/add-fleet-node-on-cloud.png
  docs/en/ingest-management/fleet/images/dashboard-datastream.png
  docs/en/ingest-management/fleet/images/dashboard-with-namespace-showing.png
  docs/en/ingest-management/fleet/images/datastream-namespace.png
  docs/en/ingest-management/fleet/images/elastic-cloud-agent-policy-page.png
  docs/en/ingest-management/fleet/images/elastic-cloud-agent-policy.png
  docs/en/ingest-management/fleet/images/fleet-policy-page.png
  docs/en/ingest-management/fleet/images/fleet-server-cloud-deployment.png
  docs/en/ingest-management/fleet/images/fleet-server-configuration.png
  docs/en/ingest-management/fleet/images/fleet-server-hosted-container.png
  docs/en/ingest-management/fleet/images/fleet-server-on-prem-deployment.png
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: backport

#1093 Add osquery link
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: docs, v7.15.0

#1095 [7.15] Add osquery link (#1093)
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: backport

#1094 [7.x] Add osquery link (#1093)
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: backport

#1080 Add 7.15 release notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.15.asciidoc
Labels: docs, blocked

#1081 Add 7.14.2 release notes
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: docs

#1097 [7.x] Add 7.15 release notes (#1080)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.15.asciidoc
Labels: backport

#1098 [7.15] Add 7.15 release notes (#1080)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.15.asciidoc
Labels: backport

#1100 [7.x] Update elastic-agent Url docker official repo (#1099)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport

#1101 [7.15] Update elastic-agent Url docker official repo (#1099)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport

#1102 [7.14] Update elastic-agent Url docker official repo (#1099)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport
