Repository elastic/observability-docs, pull requests merged in 2021-10, with the labels that each got.

#1114 Fix Fleet setting key for registry proxy URL
  docs/en/ingest-management/overview.asciidoc
Labels: docs

#1116 [7.x] Fix Fleet setting key for custom registry URL (#1114)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1119 [7.13] Fix Fleet setting key for custom registry URL (#1114)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1117 [7.15] Fix Fleet setting key for custom registry URL (#1114)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1118 [7.14] Fix Fleet setting key for custom registry URL (#1114)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1115 Rename Fleet User Guide
  .ci/Jenkinsfile
  README.md
  docs/en/ingest-management/index.asciidoc
  docs/en/integrations/air-gapped.asciidoc
Labels: Team:Docs

#1121 [7.x] Rename Fleet User Guide (#1115)
  docs/en/ingest-management/index.asciidoc
  docs/en/integrations/air-gapped.asciidoc
Labels: backport

#1122 [7.15] Rename Fleet User Guide (#1115)
  docs/en/ingest-management/index.asciidoc
  docs/en/integrations/air-gapped.asciidoc
Labels: backport

#1123 [7.13] Rename Fleet User Guide (#1115)
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1124 [7.14] Rename Fleet User Guide (#1115)
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1128 [7.14] [monitor-gcp] Fix Service Account Roles (#1120)
  docs/en/observability/images/monitor-gcp-service-account-create-key.png
  docs/en/observability/images/monitor-gcp-service-account-manage-keys.png
  docs/en/observability/images/monitor-gcp-service-account-menu.png
  docs/en/observability/images/monitor-gcp-service-account-name.png
  docs/en/observability/images/monitor-gcp-service-account-roles-compute-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-final.png
  docs/en/observability/images/monitor-gcp-service-account-roles-monitoring-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-pubsub-subscriber.png
  docs/en/observability/monitor-gcp.asciidoc
Labels: backport

#1127 [7.15] [monitor-gcp] Fix Service Account Roles (#1120)
  docs/en/observability/images/monitor-gcp-service-account-create-key.png
  docs/en/observability/images/monitor-gcp-service-account-manage-keys.png
  docs/en/observability/images/monitor-gcp-service-account-menu.png
  docs/en/observability/images/monitor-gcp-service-account-name.png
  docs/en/observability/images/monitor-gcp-service-account-roles-compute-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-final.png
  docs/en/observability/images/monitor-gcp-service-account-roles-monitoring-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-pubsub-subscriber.png
  docs/en/observability/monitor-gcp.asciidoc
Labels: backport

#1129 [7.13] [monitor-gcp] Fix Service Account Roles (#1120)
  docs/en/observability/images/monitor-gcp-service-account-create-key.png
  docs/en/observability/images/monitor-gcp-service-account-manage-keys.png
  docs/en/observability/images/monitor-gcp-service-account-menu.png
  docs/en/observability/images/monitor-gcp-service-account-name.png
  docs/en/observability/images/monitor-gcp-service-account-roles-compute-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-final.png
  docs/en/observability/images/monitor-gcp-service-account-roles-monitoring-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-pubsub-subscriber.png
  docs/en/observability/monitor-gcp.asciidoc
Labels: backport

#1133 [7.x] Favor synthetics-demo repo over synthetics/examples. (#1108)
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#1135 Update link to fix docs build
  docs/en/observability/whats-new.asciidoc
Labels: v7.11.0

#1136 Update elastic-agent-providers.asciidoc - Fixed typo, replacing `kuberentes` with `kubernetes`
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
Labels: v7.16.0, v7.15.0

#1134 Add discrete markers to prepare for chunk level increase
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
  docs/en/observability/inspect-metric-anomalies.asciidoc
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-aws-services.asciidoc
  docs/en/observability/monitor-servers.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/tail-logs.asciidoc
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: docs, v7.16.0

#1157 [7.10] Add discrete markers (#1134)
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
  docs/en/observability/inspect-metric-anomalies.asciidoc
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-aws-services.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/tail-logs.asciidoc
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#1155 [7.12] Add discrete markers (#1134)
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
  docs/en/observability/inspect-metric-anomalies.asciidoc
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-aws-services.asciidoc
  docs/en/observability/monitor-servers.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/tail-logs.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#1166 Replace temporary links to finalize pr#1149
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/integrations.asciidoc
  docs/en/ingest-management/quick-starts.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/observability/ingest-splunk.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
Labels: v7.16.0

#1168 Remove redirects page for 7.16
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: v7.16.0

#1180 Removes redirects page from Fleet and Elastic Agent docs
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: docs, v7.16.0

#1194 docs: How to set data retention (ILM) policies for integrations
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/images/create-component-template.png
  docs/en/ingest-management/images/create-index-template.png
  docs/en/ingest-management/images/data-stream-info.png
Labels: v8.0.0, Team:Docs, v7.16.0

#1198 [7.16] docs: How to set data retention (ILM) policies for integrations (#1194)
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/images/create-component-template.png
  docs/en/ingest-management/images/create-index-template.png
  docs/en/ingest-management/images/data-stream-info.png
Labels: backport

#1197 [8.0] docs: How to set data retention (ILM) policies for integrations (#1194)
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/images/create-component-template.png
  docs/en/ingest-management/images/create-index-template.png
  docs/en/ingest-management/images/data-stream-info.png
Labels: backport

#1181 docs: update APM links
  docs/en/observability/apm.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/shared/configure-apm-server/content.asciidoc
  docs/en/shared/spin-up-the-stack/content.asciidoc
Labels: v7.16.0

#1200 [7.16] docs: update APM links (#1181)
  docs/en/observability/apm.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/shared/configure-apm-server/content.asciidoc
  docs/en/shared/spin-up-the-stack/content.asciidoc
Labels: backport

#1199 [8.0] docs: update APM links (#1181)
  docs/en/observability/apm.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/shared/configure-apm-server/content.asciidoc
  docs/en/shared/spin-up-the-stack/content.asciidoc
Labels: backport
