Repository elastic/observability-docs, pull requests merged in 2021-04, with the labels that each got.

#475 [7.10] Refactor files to prep for book changing chunk level
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-dynamic-inputs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs, docs

#478 [7.12] Refactor files to prep for book changing chunk level
  docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs, docs

#477 [7.11] Refactor files to prep for book changing chunk level
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-dynamic-inputs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/dynamic/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs, docs

#476 [7.9] Add discrete tags to prep for book changing chunk level
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: Team:Docs, docs

#479 [7.x] Refactor files to prep for book changing chunk level
  docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs, docs

#485 Update security note for configuring uptime settings
  docs/en/observability/configure-uptime-settings.asciidoc
Labels: v7.10.0, v7.11.0, v7.12.0, v7.13.0, v8.0.0

#487 [7.x] Update security note for configuring uptime settings (#485)
  docs/en/observability/configure-uptime-settings.asciidoc
Labels: backport

#488 [7.12] Update security note for configuring uptime settings (#485)
  docs/en/observability/configure-uptime-settings.asciidoc
Labels: backport

#489 [7.11] Update security note for configuring uptime settings (#485)
  docs/en/observability/configure-uptime-settings.asciidoc
Labels: backport

#490 [7.10] Update security note for configuring uptime settings (#485)
  docs/en/observability/configure-uptime-settings.asciidoc
Labels: backport

#474 [7.12] docs: add logs app video (#470)
  docs/en/observability/tail-logs.asciidoc
Labels: backport

#473 [7.x] docs: add logs app video (#470)
  docs/en/observability/tail-logs.asciidoc
Labels: backport

#492 [7.x] docs: fix small bugs in gcp tut (#481)
  docs/en/observability/images/monitor-gcp-audit-overview-dashboard.png
  docs/en/observability/monitor-gcp.asciidoc
Labels: backport

#493 [7.12] docs: fix small bugs in gcp tut (#481)
  docs/en/observability/images/monitor-gcp-audit-overview-dashboard.png
  docs/en/observability/monitor-gcp.asciidoc
Labels: backport

#459 Document location of Beats logs
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: Team:Agent, docs, v7.12.0

#495 [7.12] Document location of Beats logs (#459)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: backport, docs

#494 [7.x] Document location of Beats logs (#459)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: backport, docs

#496 Add discrete tags to fix chunk level
  docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs

#491 Create CODEOWNERS
  .github/CODEOWNERS
  README.md
Labels: discuss

#506 [master] Update download.asciidoc (#455)
  docs/en/ingest-management/tab-widgets/download.asciidoc
Labels: backport

#505 [7.x] Update download.asciidoc (#455)
  docs/en/ingest-management/tab-widgets/download.asciidoc
Labels: backport

#504 [7.12] Update download.asciidoc (#455)
  docs/en/ingest-management/tab-widgets/download.asciidoc
Labels: backport

#508 Mention command for generating encryption keys
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: Team:Docs, docs

#511 [7.12] Mention command for generating encryption keys (#508)
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: backport, docs

#510 [7.x] Mention command for generating encryption keys (#508)
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: backport, docs

#515 [7.12] Create agent-policies.asciidoc (#469)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/apply-agent-policy.png
  docs/en/ingest-management/images/assign-policy.png
  docs/en/ingest-management/images/create-agent-policy.png
  docs/en/ingest-management/index.asciidoc
Labels: backport

#514 [7.x] Create agent-policies.asciidoc (#469)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/apply-agent-policy.png
  docs/en/ingest-management/images/assign-policy.png
  docs/en/ingest-management/images/create-agent-policy.png
  docs/en/ingest-management/index.asciidoc
Labels: backport

#528 [Alerting] Changed alerting management links due to the upcoming changes in the alerting docs.
  docs/en/observability/create-alerts.asciidoc
Labels: docs, v7.13.0

#532 Update agent-policies.asciidoc
  docs/en/ingest-management/agent-policies.asciidoc
Labels: v7.12.0

#534 [7.12] Update agent-policies.asciidoc (#532)
  docs/en/ingest-management/agent-policies.asciidoc
Labels: backport

#533 [7.x] Update agent-policies.asciidoc (#532)
  docs/en/ingest-management/agent-policies.asciidoc
Labels: backport

#520 Update elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
Labels: v7.12.0

#542 [7.x] Add third party REST API docs (#483)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/images/elastic-agent-splunk.png
  docs/en/observability/images/kibana-fleet-third-party-rest-api.png
  docs/en/observability/images/kibana-fleet-third-party-rest-dataset-settings.png
  docs/en/observability/images/kibana-fleet-third-party-rest-settings.png
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-splunk.asciidoc
Labels: backport

#556 [7.13] quick fleet server blurb (#539)
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: backport, docs

#555 [7.x] quick fleet server blurb (#539)
  docs/en/ingest-management/fleet-overview.asciidoc
Labels: backport, docs

#580 Add Synthetics check details content
  docs/en/observability/images/synthetics_check_details.png
  docs/en/observability/images/synthetics_overview.png
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
Labels: docs, v7.13.0

#591 [7.x] Add Synthetics check details content (#580)
  docs/en/observability/images/synthetics_check_details.png
  docs/en/observability/images/synthetics_overview.png
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
Labels: backport

#592 [7.13] Add Synthetics check details content (#580)
  docs/en/observability/images/synthetics_check_details.png
  docs/en/observability/images/synthetics_overview.png
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
Labels: backport

#594 Metrics app: update host details content
  docs/en/observability/images/anomalies-overlay.png
  docs/en/observability/images/logs-overlay.png
  docs/en/observability/images/metadata-overlay.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/images/processes-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: docs, v7.13.0

#596 [7.x] Update host details (#594)
  docs/en/observability/images/anomalies-overlay.png
  docs/en/observability/images/logs-overlay.png
  docs/en/observability/images/metadata-overlay.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/images/processes-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: backport

#597 [7.13] Update host details (#594)
  docs/en/observability/images/anomalies-overlay.png
  docs/en/observability/images/logs-overlay.png
  docs/en/observability/images/metadata-overlay.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/images/processes-overlay.png
  docs/en/observability/monitor-servers.asciidoc
Labels: backport

#598 Metrics app: add anomalies tab content
  docs/en/observability/images/metrics-ml-jobs.png
  docs/en/observability/inspect-metric-anomalies.asciidoc
Labels: docs, v7.13.0

#600 [7.x] Metrics app: add anomalies tab content (#598)
  docs/en/observability/images/metrics-ml-jobs.png
  docs/en/observability/inspect-metric-anomalies.asciidoc
Labels: backport

#601 [7.13] Metrics app: add anomalies tab content (#598)
  docs/en/observability/images/metrics-ml-jobs.png
  docs/en/observability/inspect-metric-anomalies.asciidoc
Labels: backport

#607 [7.13] Add Fleet Server docs (#585)
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/images/add-fleet-node-on-cloud.png
  docs/en/ingest-management/fleet/images/add-fleet-server.png
  docs/en/ingest-management/fleet/images/agents-tab-fleet-server.png
  docs/en/ingest-management/fleet/images/fleet-server-communication.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/widget.asciidoc
Labels: backport

#606 [7.x] Add Fleet Server docs (#585)
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/images/add-fleet-node-on-cloud.png
  docs/en/ingest-management/fleet/images/add-fleet-server.png
  docs/en/ingest-management/fleet/images/agents-tab-fleet-server.png
  docs/en/ingest-management/fleet/images/fleet-server-communication.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/widget.asciidoc
Labels: backport
