Repository elastic/observability-docs, pull requests merged in 2021-11, with the labels that each got.

#1205 [master] Add tip about ECK to Fleet-managed Agent section (#1150)
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
Labels: backport

#1204 [8.0] Add tip about ECK to Fleet-managed Agent section (#1150)
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
Labels: backport

#1188 Remove Fleet Developer Guide source files
  docs/en/fleet-developer/fleet-architecture.asciidoc
  docs/en/fleet-developer/fleet-ports.asciidoc
  docs/en/fleet-developer/fleet-security-model.asciidoc
  docs/en/fleet-developer/index.asciidoc
Labels: Team:Fleet

#1182 [7.14] Add Fleet Server deployment and scaling docs (#1061)
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/images/add-fleet-node-on-cloud.png
  docs/en/ingest-management/fleet/images/dashboard-datastream.png
  docs/en/ingest-management/fleet/images/dashboard-with-namespace-showing.png
  docs/en/ingest-management/fleet/images/datastream-namespace.png
  docs/en/ingest-management/fleet/images/elastic-cloud-agent-policy-page.png
  docs/en/ingest-management/fleet/images/elastic-cloud-agent-policy.png
  docs/en/ingest-management/fleet/images/fleet-policy-page.png
  docs/en/ingest-management/fleet/images/fleet-server-cloud-deployment.png
  docs/en/ingest-management/fleet/images/fleet-server-configuration.png
  docs/en/ingest-management/fleet/images/fleet-server-hosted-container.png
  docs/en/ingest-management/fleet/images/fleet-server-on-prem-deployment.png
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: backport, v7.14.0

#1196 Update docs for metric threshold alert filter and group
  docs/en/observability/images/metrics-alert-filters-and-group.png
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: v8.0.0, Team:Docs, v7.16.0

#1210 [7.16] Update docs for metric threshold alert filter and group (#1196)
  docs/en/observability/images/metrics-alert-filters-and-group.png
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#1209 [8.0] Update docs for metric threshold alert filter and group (#1196)
  docs/en/observability/images/metrics-alert-filters-and-group.png
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#1206 mark logging.ecs and logging.json as deprecated
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
Labels: docs, v7.16.0, Team:Elastic-Agent-Control-Plane

#1208 remove agent.logging.ecs and json
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
Labels: docs, v8.0.0, Team:Elastic-Agent-Control-Plane

#1230 Add disclaimer to standalone docs
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/standalone-note.asciidoc
Labels: docs, Team:Docs, v7.16.0

#1236 [7.16] Add disclaimer to standalone docs (#1230)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/standalone-note.asciidoc
Labels: backport

#1237 [7.15] Add disclaimer to standalone docs (#1230)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/standalone-note.asciidoc
Labels: backport

#1235 [8.0] Add disclaimer to standalone docs (#1230)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/standalone-note.asciidoc
Labels: backport

#1171 Consolidate synthetics and uptime content
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
Labels: docs, v7.16.0

#1241 [7.16] Consolidate synthetics and uptime content (#1171)
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
Labels: backport

#1242 [8.0] Consolidate synthetics and uptime content (#1171)
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
Labels: backport

#1238 Indicate that Fleet-managed agents do not support http json input
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: docs, Team:Elastic-Agent, v7.16.0

#1244 [7.16] Indicate that Fleet-managed agents do not support http json input (#1238)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1245 [7.15] Indicate that Fleet-managed agents do not support http json input (#1238)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1246 [7.14] Indicate that Fleet-managed agents do not support http json input (#1238)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1243 [8.0] Indicate that Fleet-managed agents do not support http json input (#1238)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1252 Backport (#1212) Add elastic-agent diagnostics to troubleshooting section
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport, v8.0.0

#1253 Backport (#1208) remove agent.logging.ecs and json
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
Labels: backport, v8.0.0

#1254 Break topic about managing integrations into multiple topics
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/uninstall-integration.asciidoc
  docs/en/ingest-management/integrations/update-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
Labels: v7.16.0

#1256 [7.16] Break topic about managing integrations into multiple topics (#1254)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/uninstall-integration.asciidoc
  docs/en/ingest-management/integrations/update-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
Labels: backport

#1248 Update quick starts for 7.16
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/observability/images/add-integration-apm.png
  docs/en/observability/images/add-integration.png
  docs/en/observability/images/add-synthetics-integration.png
  docs/en/observability/images/fleet-server-hosted-container.png
  docs/en/observability/images/kibana-fleet-agents.png
  docs/en/observability/images/kibana-fleet-integrations-apm-overview.png
  docs/en/observability/images/kibana-fleet-integrations-apm.png
  docs/en/observability/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/observability/images/kibana-fleet-integrations-nginx.png
  docs/en/observability/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/observability/images/kibana-fleet-integrations-synthetics.png
  docs/en/observability/images/kibana-fleet-policies-default-with-apm.png
  docs/en/observability/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/observability/images/kibana-fleet-policies-default-with-synthetics.png
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/instrument-apps.asciidoc
Labels: v8.0.0, Team:Docs, v7.16.0

#1258 [7.16] Update quick starts for 7.16 (#1248)
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/observability/images/add-integration-apm.png
  docs/en/observability/images/add-integration.png
  docs/en/observability/images/add-synthetics-integration.png
  docs/en/observability/images/fleet-server-hosted-container.png
  docs/en/observability/images/kibana-fleet-agents.png
  docs/en/observability/images/kibana-fleet-integrations-apm-overview.png
  docs/en/observability/images/kibana-fleet-integrations-apm.png
  docs/en/observability/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/observability/images/kibana-fleet-integrations-nginx.png
  docs/en/observability/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/observability/images/kibana-fleet-integrations-synthetics.png
  docs/en/observability/images/kibana-fleet-policies-default-with-apm.png
  docs/en/observability/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/observability/images/kibana-fleet-policies-default-with-synthetics.png
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/instrument-apps.asciidoc
Labels: backport

#1257 [8.0] Update quick starts for 7.16 (#1248)
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/observability/images/add-integration-apm.png
  docs/en/observability/images/add-integration.png
  docs/en/observability/images/add-synthetics-integration.png
  docs/en/observability/images/fleet-server-hosted-container.png
  docs/en/observability/images/kibana-fleet-agents.png
  docs/en/observability/images/kibana-fleet-integrations-apm-overview.png
  docs/en/observability/images/kibana-fleet-integrations-apm.png
  docs/en/observability/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/observability/images/kibana-fleet-integrations-nginx.png
  docs/en/observability/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/observability/images/kibana-fleet-integrations-synthetics.png
  docs/en/observability/images/kibana-fleet-policies-default-with-apm.png
  docs/en/observability/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/observability/images/kibana-fleet-policies-default-with-synthetics.png
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/instrument-apps.asciidoc
Labels: backport

#1255 [8.0] Break topic about managing integrations into multiple topics (#1254)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/uninstall-integration.asciidoc
  docs/en/ingest-management/integrations/update-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
Labels: backport

#1259 Document how to upgrade integration policies automatically
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/images/update-integration.png
  docs/en/ingest-management/images/upgrade-integration-policies-automatically.png
  docs/en/ingest-management/images/upgrade-integration.png
  docs/en/ingest-management/images/upgrade-package-policy.png
  docs/en/ingest-management/images/upgrade-policy-editor.png
  docs/en/ingest-management/images/upgrade-resolve-conflicts.png
  docs/en/ingest-management/images/upgrade-view-previous-config.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/uninstall-integration.asciidoc
  docs/en/ingest-management/integrations/update-integration.asciidoc
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Fleet, v7.16.0

#1268 [7.16] Document how to upgrade integration policies automatically (#1259)
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/images/update-integration.png
  docs/en/ingest-management/images/upgrade-integration-policies-automatically.png
  docs/en/ingest-management/images/upgrade-integration.png
  docs/en/ingest-management/images/upgrade-package-policy.png
  docs/en/ingest-management/images/upgrade-policy-editor.png
  docs/en/ingest-management/images/upgrade-resolve-conflicts.png
  docs/en/ingest-management/images/upgrade-view-previous-config.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/uninstall-integration.asciidoc
  docs/en/ingest-management/integrations/update-integration.asciidoc
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport

#1267 [8.0] Document how to upgrade integration policies automatically (#1259)
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/images/update-integration.png
  docs/en/ingest-management/images/upgrade-integration-policies-automatically.png
  docs/en/ingest-management/images/upgrade-integration.png
  docs/en/ingest-management/images/upgrade-package-policy.png
  docs/en/ingest-management/images/upgrade-policy-editor.png
  docs/en/ingest-management/images/upgrade-resolve-conflicts.png
  docs/en/ingest-management/images/upgrade-view-previous-config.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/uninstall-integration.asciidoc
  docs/en/ingest-management/integrations/update-integration.asciidoc
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport

#1211 Add Cases and Alerts content
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/create-cases.asciidoc
  docs/en/observability/create-observability-connectors.asciidoc
  docs/en/observability/grant-cases-access.asciidoc
  docs/en/observability/images/action-dropdown.png
  docs/en/observability/images/add-case-connector.png
  docs/en/observability/images/alerts-page.png
  docs/en/observability/images/app-link-icon.png
  docs/en/observability/images/cases-privledges.png
  docs/en/observability/images/cases.png
  docs/en/observability/images/flyout-icon.png
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases.asciidoc
  docs/en/observability/view-observability-alerts.asciidoc
Labels: docs, v8.0.0, v7.16.0

#1271 [7.16] Add Cases and Alerts content (#1211)
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/create-cases.asciidoc
  docs/en/observability/create-observability-connectors.asciidoc
  docs/en/observability/grant-cases-access.asciidoc
  docs/en/observability/images/action-dropdown.png
  docs/en/observability/images/add-case-connector.png
  docs/en/observability/images/alerts-page.png
  docs/en/observability/images/app-link-icon.png
  docs/en/observability/images/cases-privledges.png
  docs/en/observability/images/cases.png
  docs/en/observability/images/flyout-icon.png
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases.asciidoc
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport

#1270 [8.0] Add Cases and Alerts content (#1211)
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/create-cases.asciidoc
  docs/en/observability/create-observability-connectors.asciidoc
  docs/en/observability/grant-cases-access.asciidoc
  docs/en/observability/images/action-dropdown.png
  docs/en/observability/images/add-case-connector.png
  docs/en/observability/images/alerts-page.png
  docs/en/observability/images/app-link-icon.png
  docs/en/observability/images/cases-privledges.png
  docs/en/observability/images/cases.png
  docs/en/observability/images/flyout-icon.png
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases.asciidoc
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport

#1264 Add header to legacy observability docs
  docs/en/logs/page_header.html
  docs/en/metrics/page_header.html
  docs/en/uptime/page_header.html
Labels: v7.9.0

#1273 [Fleet] Revert "docs: How to set data retention (ILM) policies for integrations (#1194)"
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/images/create-component-template.png
  docs/en/ingest-management/images/create-index-template.png
  docs/en/ingest-management/images/data-stream-info.png
Labels: v8.0.0, Team:Fleet, v7.16.0, v8.1.0

#1265 Add agent.monitoring.pprof doc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Labels: Team:Elastic-Agent-Control-Plane

#1280 [7.16] Revert "docs: How to set data retention (ILM) policies for integrations (#1194)" (#1273)
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/images/create-component-template.png
  docs/en/ingest-management/images/create-index-template.png
  docs/en/ingest-management/images/data-stream-info.png
Labels: backport

#1279 [8.0] Revert "docs: How to set data retention (ILM) policies for integrations (#1194)" (#1273)
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/images/create-component-template.png
  docs/en/ingest-management/images/create-index-template.png
  docs/en/ingest-management/images/data-stream-info.png
Labels: backport

#1274 Reorganize Fleet Server content
  docs/en/ingest-management/fleet/add-fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-server-deployment-models.asciidoc
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Fleet, v7.16.0

#1282 [7.16] Reorganize Fleet Server content (#1274)
  docs/en/ingest-management/fleet/add-fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-server-deployment-models.asciidoc
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1281 [8.0] Reorganize Fleet Server content (#1274)
  docs/en/ingest-management/fleet/add-fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-server-deployment-models.asciidoc
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1277 Backport #1265
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Labels: backport, v8.0.0

#1278 Backport #1265
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Labels: backport, v7.16.0

#1262 [DOCS] Adds 7.16 highlight for APM correlations
  docs/en/observability/images/7-16-apm-failed-correlations.png
  docs/en/observability/whats-new.asciidoc
Labels: Team:APM, v7.16.0

#1286 Remove section about turning on Fleet Server monitoring in cloud
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/images/elastic-cloud-agent-policy-page.png
  docs/en/ingest-management/fleet/images/fleet-policy-page.png
  docs/en/ingest-management/fleet/images/fleet-server-agent-policy-page.png
Labels: v8.0.0, v7.16.0

#1297 [7.16] Remove section about turning on agent monitoring in cloud for Fleet Server (#1286)
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/images/elastic-cloud-agent-policy-page.png
  docs/en/ingest-management/fleet/images/fleet-policy-page.png
  docs/en/ingest-management/fleet/images/fleet-server-agent-policy-page.png
Labels: backport

#1296 [8.0] Remove section about turning on agent monitoring in cloud for Fleet Server (#1286)
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/images/elastic-cloud-agent-policy-page.png
  docs/en/ingest-management/fleet/images/fleet-policy-page.png
  docs/en/ingest-management/fleet/images/fleet-server-agent-policy-page.png
Labels: backport

#1289 Change agent pprof default to false
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane

#1300 [Backport] Change agent pprof default to false (#1289)
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Labels: backport, v8.0.0

#1301 [Backport] Change agent pprof default to false (#1289)
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Labels: backport, v7.16.0
