Repository elastic/observability-docs, pull requests merged in 2021-03, with the labels that each got.

#410 7.12-update for enroll command
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
Labels: v7.12.0

#427 [7.x] 7.12-update for enroll command (#410)
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
Labels: backport

#428 [7.12] 7.12-update for enroll command (#410)
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
Labels: backport

#433 [7.12][Metrics UI] Remove anomaly alert documentation (#430)
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/anomaly-variables.png
  docs/en/observability/images/infra-anomaly-conditions.png
  docs/en/observability/infrastructure-anomaly-alert.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
Labels: backport

#432 [7.x][Metrics UI] Remove anomaly alert documentation (#430)
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/anomaly-variables.png
  docs/en/observability/images/infra-anomaly-conditions.png
  docs/en/observability/infrastructure-anomaly-alert.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
Labels: backport

#423 Monitor gcp tutorial
  docs/en/observability/images/monitor-gcp-audit-overview-dashboard.png
  docs/en/observability/images/monitor-gcp-compute-overview-dashboard.png
  docs/en/observability/images/monitor-gcp-create-pubsub-topic.png
  docs/en/observability/images/monitor-gcp-create-sink.png
  docs/en/observability/images/monitor-gcp-navigate-logs-router.png
  docs/en/observability/images/monitor-gcp-service-account-create-key.png
  docs/en/observability/images/monitor-gcp-service-account-menu.png
  docs/en/observability/images/monitor-gcp-service-account-name.png
  docs/en/observability/images/monitor-gcp-service-account-roles-compute-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-final.png
  docs/en/observability/images/monitor-gcp-service-account-roles-monitoring-viewer.png
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: enhancement, v7.12.0

#441 [7.12] Add data stream docs to Fleet user guide (#429)
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/fleet-overview.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#440 [7.x] Add data stream docs to Fleet user guide (#429)
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/fleet-overview.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#422 Added docs for capabilities
  docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: docs, v7.12.0

#438 [7.12] Monitor gcp tutorial (#423)
  docs/en/observability/images/monitor-gcp-audit-overview-dashboard.png
  docs/en/observability/images/monitor-gcp-compute-overview-dashboard.png
  docs/en/observability/images/monitor-gcp-create-pubsub-topic.png
  docs/en/observability/images/monitor-gcp-create-sink.png
  docs/en/observability/images/monitor-gcp-navigate-logs-router.png
  docs/en/observability/images/monitor-gcp-service-account-create-key.png
  docs/en/observability/images/monitor-gcp-service-account-menu.png
  docs/en/observability/images/monitor-gcp-service-account-name.png
  docs/en/observability/images/monitor-gcp-service-account-roles-compute-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-final.png
  docs/en/observability/images/monitor-gcp-service-account-roles-monitoring-viewer.png
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport

#437 [7.x] Monitor gcp tutorial (#423)
  docs/en/observability/images/monitor-gcp-audit-overview-dashboard.png
  docs/en/observability/images/monitor-gcp-compute-overview-dashboard.png
  docs/en/observability/images/monitor-gcp-create-pubsub-topic.png
  docs/en/observability/images/monitor-gcp-create-sink.png
  docs/en/observability/images/monitor-gcp-navigate-logs-router.png
  docs/en/observability/images/monitor-gcp-service-account-create-key.png
  docs/en/observability/images/monitor-gcp-service-account-menu.png
  docs/en/observability/images/monitor-gcp-service-account-name.png
  docs/en/observability/images/monitor-gcp-service-account-roles-compute-viewer.png
  docs/en/observability/images/monitor-gcp-service-account-roles-final.png
  docs/en/observability/images/monitor-gcp-service-account-roles-monitoring-viewer.png
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport

#446 [7.x] Update elastic-agent-command-line.asciidoc (#406)
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
Labels: backport

#448 [master] Update elastic-agent-command-line.asciidoc (#406)
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
Labels: backport

#447 [7.12] Update elastic-agent-command-line.asciidoc (#406)
  docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
Labels: backport

#444 [7.x] Added docs for capabilities (#422)
  docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: backport

#445 [7.12] Added docs for capabilities (#422)
  docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: backport

#451 Add missing links to APM integration
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: v7.12.0

#453 [7.12] Add missing links to APM integration (#451)
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: backport

#452 [7.x] Add missing links to APM integration (#451)
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: backport

#456 Updates TSVB links
  docs/en/observability/explore-metrics.asciidoc
Labels: docs, v7.12.0, v7.13.0

#458 [7.12] Updates TSVB links (#456)
  docs/en/observability/explore-metrics.asciidoc
Labels: backport

#457 [7.x] Updates TSVB links (#456)
  docs/en/observability/explore-metrics.asciidoc
Labels: backport

#431 7.12 Synthetics Docs Changes
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: v7.12.0

#463 [7.x] 7.12 Synthetics Docs Changes (#431)
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#464 [7.12] 7.12 Synthetics Docs Changes (#431)
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#461 Add What's new content for 7.12 release
  docs/en/observability/images/apm-correlations.png
  docs/en/observability/images/improved-synthetics-waterfall.png
  docs/en/observability/images/infra-anomaly-define.png
  docs/en/observability/images/infra-anomaly-scope.png
  docs/en/observability/images/logs-stream.png
  docs/en/observability/images/metrics-alert-actions.png
  docs/en/observability/images/metrics-alert-threshold.png
  docs/en/observability/images/ml-swimlanes-charts.png
  docs/en/observability/images/otel-exporter-arch.png
  docs/en/observability/images/otel-protocol-arch.png
  docs/en/observability/images/stack-monitoring-alert.png
  docs/en/observability/images/synthetics-waterfall-details.png
  docs/en/observability/whats-new.asciidoc
Labels: docs, v7.12.0

#462 Minor change to title for agent installation instructions
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: Team:Fleet, docs

#470 docs: add logs app video
  docs/en/observability/tail-logs.asciidoc
Labels: enhancement, v7.12.0

#472 [7.12] Update install-elastic-agent.asciidoc (#462)
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport, docs

#471 [7.x] Update install-elastic-agent.asciidoc (#462)
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport, docs
