Repository elastic/observability-docs, pull requests merged in 2021-07, with the labels that each got.

#826 [7.x] Fix uninstall commands (#822)
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Labels: backport

#829 Adds missing asterisks to a Fleet Server requirement related to wildcard domains
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: Team:Fleet, docs, v7.13.2, v7.14.0

#836 Make more clear in the example that conditions accumulate
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: Team:Docs, v7.13.2, v7.14.0

#837 [7.x] Make more clear in the example that conditions accumulate (#836)
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#838 [7.14] Make more clear in the example that conditions accumulate (#836)
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#839 [7.13] Make more clear in the example that conditions accumulate (#836)
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#833 [7.x] [monitor-azure] Update tutorial to use native integration (#803)
  docs/en/observability/images/monitor-azure-click-access-keys.png
  docs/en/observability/images/monitor-azure-click-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-click-policy.png
  docs/en/observability/images/monitor-azure-click-view-keys.png
  docs/en/observability/images/monitor-azure-cloud-overview-dashboard.png
  docs/en/observability/images/monitor-azure-compute-vms-overview-dashboard.png
  docs/en/observability/images/monitor-azure-configure-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-create-elastic-resource.png
  docs/en/observability/images/monitor-azure-elastic-click-ingest-logs.png
  docs/en/observability/images/monitor-azure-elastic-config-logs-metrics.png
  docs/en/observability/images/monitor-azure-elastic-deployment.png
  docs/en/observability/images/monitor-azure-elastic-vms.png
  docs/en/observability/images/monitor-azure-kibana-deployment.png
  docs/en/observability/images/monitor-azure-kibana-logs-app.png
  docs/en/observability/images/monitor-azure-kibana-observability-page-data.png
  docs/en/observability/images/monitor-azure-kibana-observability-page-empty.png
  docs/en/observability/images/monitor-azure-kibana-security.png
  docs/en/observability/images/monitor-azure-kibana-vms-logs.png
  docs/en/observability/images/monitor-azure-kibana-vms-metrics.png
  docs/en/observability/images/monitor-azure-open-powershell.png
  docs/en/observability/images/monitor-azure-search-activity-log.png
  docs/en/observability/images/monitor-azure-search-elasticsearch.png
  docs/en/observability/images/monitor-azure-search-event-hubs.png
  docs/en/observability/images/monitor-azure-search-storage-accounts.png
  docs/en/observability/monitor-azure.asciidoc
Labels: backport

#834 [7.14] [monitor-azure] Update tutorial to use native integration (#803)
  docs/en/observability/images/monitor-azure-click-access-keys.png
  docs/en/observability/images/monitor-azure-click-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-click-policy.png
  docs/en/observability/images/monitor-azure-click-view-keys.png
  docs/en/observability/images/monitor-azure-cloud-overview-dashboard.png
  docs/en/observability/images/monitor-azure-compute-vms-overview-dashboard.png
  docs/en/observability/images/monitor-azure-configure-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-create-elastic-resource.png
  docs/en/observability/images/monitor-azure-elastic-click-ingest-logs.png
  docs/en/observability/images/monitor-azure-elastic-config-logs-metrics.png
  docs/en/observability/images/monitor-azure-elastic-deployment.png
  docs/en/observability/images/monitor-azure-elastic-vms.png
  docs/en/observability/images/monitor-azure-kibana-deployment.png
  docs/en/observability/images/monitor-azure-kibana-logs-app.png
  docs/en/observability/images/monitor-azure-kibana-observability-page-data.png
  docs/en/observability/images/monitor-azure-kibana-observability-page-empty.png
  docs/en/observability/images/monitor-azure-kibana-security.png
  docs/en/observability/images/monitor-azure-kibana-vms-logs.png
  docs/en/observability/images/monitor-azure-kibana-vms-metrics.png
  docs/en/observability/images/monitor-azure-open-powershell.png
  docs/en/observability/images/monitor-azure-search-activity-log.png
  docs/en/observability/images/monitor-azure-search-elasticsearch.png
  docs/en/observability/images/monitor-azure-search-event-hubs.png
  docs/en/observability/images/monitor-azure-search-storage-accounts.png
  docs/en/observability/monitor-azure.asciidoc
Labels: backport

#835 [7.13] [monitor-azure] Update tutorial to use native integration (#803)
  docs/en/observability/images/monitor-azure-click-access-keys.png
  docs/en/observability/images/monitor-azure-click-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-click-policy.png
  docs/en/observability/images/monitor-azure-click-view-keys.png
  docs/en/observability/images/monitor-azure-cloud-overview-dashboard.png
  docs/en/observability/images/monitor-azure-compute-vms-overview-dashboard.png
  docs/en/observability/images/monitor-azure-configure-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-create-elastic-resource.png
  docs/en/observability/images/monitor-azure-elastic-click-ingest-logs.png
  docs/en/observability/images/monitor-azure-elastic-config-logs-metrics.png
  docs/en/observability/images/monitor-azure-elastic-deployment.png
  docs/en/observability/images/monitor-azure-elastic-vms.png
  docs/en/observability/images/monitor-azure-kibana-deployment.png
  docs/en/observability/images/monitor-azure-kibana-logs-app.png
  docs/en/observability/images/monitor-azure-kibana-observability-page-data.png
  docs/en/observability/images/monitor-azure-kibana-observability-page-empty.png
  docs/en/observability/images/monitor-azure-kibana-security.png
  docs/en/observability/images/monitor-azure-kibana-vms-logs.png
  docs/en/observability/images/monitor-azure-kibana-vms-metrics.png
  docs/en/observability/images/monitor-azure-open-powershell.png
  docs/en/observability/images/monitor-azure-search-activity-log.png
  docs/en/observability/images/monitor-azure-search-elasticsearch.png
  docs/en/observability/images/monitor-azure-search-event-hubs.png
  docs/en/observability/images/monitor-azure-search-storage-accounts.png
  docs/en/observability/monitor-azure.asciidoc
Labels: backport

#841 Metric threshold alert improvement
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: Team:Docs, v7.13.2, v7.14.0

#843 [7.x] Metric threshold alert improvement (#841)
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#844 [7.14] Metric threshold alert improvement (#841)
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#845 [7.13] Metric threshold alert improvement (#841)
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport

#808 Elastic agent: Add logging content
  docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/logging-widget.asciidoc
  docs/en/ingest-management/tab-widgets/logging.asciidoc
Labels: Team:Fleet, v7.13.0

#849 [7.x] Elastic agent: Add logging content (#808)
  docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/logging-widget.asciidoc
  docs/en/ingest-management/tab-widgets/logging.asciidoc
Labels: backport

#850 [7.13] Elastic agent: Add logging content (#808)
  docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/logging-widget.asciidoc
  docs/en/ingest-management/tab-widgets/logging.asciidoc
Labels: backport

#851 [7.14] Elastic agent: Add logging content (#808)
  docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/logging-widget.asciidoc
  docs/en/ingest-management/tab-widgets/logging.asciidoc
Labels: backport

#832 [7.13] Adds missing asterisks to limitation about wildcard domains (#829)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#831 [7.14] Adds missing asterisks to limitation about wildcard domains (#829)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#830 [7.x] Adds missing asterisks to limitation about wildcard domains (#829)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#848 Update docs for agent managed by fleet on kubernetes
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Labels: 7.15-candidate, Team:Agent, Team:Integrations, enhancement

#855 [7.14] add synthetics configuration docs (#847)
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
Labels: backport

#854 [7.x] add synthetics configuration docs (#847)
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
Labels: backport

#821 Add pointer to docs about kibana.yml settings
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: Team:Docs, docs, v7.14.0

#840 Uptime app: Update content and images for 7.14
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/images/alert-action-types.png
  docs/en/observability/images/alert-connector.png
  docs/en/observability/images/cert-expiry-settings.png
  docs/en/observability/images/heartbeat-indices.png
  docs/en/observability/images/monitor-duration-chart.png
  docs/en/observability/images/monitor-status-alert.png
  docs/en/observability/images/pings-over-time.png
  docs/en/observability/images/tls-alert.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-alert-connectors.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: docs, v7.14.0

#862 [7.x] Uptime app: Update content and images for 7.14 (#840)
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/images/alert-action-types.png
  docs/en/observability/images/alert-connector.png
  docs/en/observability/images/cert-expiry-settings.png
  docs/en/observability/images/heartbeat-indices.png
  docs/en/observability/images/monitor-duration-chart.png
  docs/en/observability/images/monitor-status-alert.png
  docs/en/observability/images/pings-over-time.png
  docs/en/observability/images/tls-alert.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-alert-connectors.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#863 [7.14] Uptime app: Update content and images for 7.14 (#840)
  docs/en/observability/analyze-monitors.asciidoc
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/images/alert-action-types.png
  docs/en/observability/images/alert-connector.png
  docs/en/observability/images/cert-expiry-settings.png
  docs/en/observability/images/heartbeat-indices.png
  docs/en/observability/images/monitor-duration-chart.png
  docs/en/observability/images/monitor-status-alert.png
  docs/en/observability/images/pings-over-time.png
  docs/en/observability/images/tls-alert.png
  docs/en/observability/images/tls-certificates.png
  docs/en/observability/images/uptime-alert-connectors.png
  docs/en/observability/images/uptime-app.png
  docs/en/observability/images/uptime-history.png
  docs/en/observability/images/uptime-status-panel.png
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#861 [Synthetics] update docs with new api's
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: Team:Uptime, v7.14.0

#867 [7.x] Update docs for agent managed by fleet on kubernetes (#848)
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Labels: backport

#859 [7.13] Add pointer to docs about kibana.yml settings (#821)
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport

#858 [7.14] Add pointer to docs about kibana.yml settings (#821)
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport

#857 [7.x] Add pointer to docs about kibana.yml settings (#821)
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport

#866 [7.14] [Synthetics] update docs with new api's (#861)
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#865 [7.x] [Synthetics] update docs with new api's (#861)
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#823 Add docs about Fleet enrollment tokens
  docs/en/ingest-management/images/create-token.png
  docs/en/ingest-management/images/revoke-token.png
  docs/en/ingest-management/images/show-token.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
Labels: Team:Fleet, docs, v7.13.2, v7.14.0

#870 [7.13] Add docs about Fleet enrollment tokens (#823)
  docs/en/ingest-management/images/create-token.png
  docs/en/ingest-management/images/revoke-token.png
  docs/en/ingest-management/images/show-token.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
Labels: backport

#869 [7.14] Add docs about Fleet enrollment tokens (#823)
  docs/en/ingest-management/images/create-token.png
  docs/en/ingest-management/images/revoke-token.png
  docs/en/ingest-management/images/show-token.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
Labels: backport

#868 [7.x] Add docs about Fleet enrollment tokens (#823)
  docs/en/ingest-management/images/create-token.png
  docs/en/ingest-management/images/revoke-token.png
  docs/en/ingest-management/images/show-token.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
Labels: backport

#773 Initial issue template
  .github/ISSUE_TEMPLATE/docs-request.md
Labels: Team:Docs

#871 Remove beta admonitions from Fleet and Elastic Agent docs
  docs/en/fleet-developer/fleet-architecture.asciidoc
  docs/en/fleet-developer/fleet-ports.asciidoc
  docs/en/fleet-developer/fleet-security-model.asciidoc
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: Team:Docs, docs, v7.14.0

#873 [7.14] Remove beta admonitions from Fleet and Elastic Agent docs (#871)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#872 [7.x] Remove beta admonitions from Fleet and Elastic Agent docs (#871)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#883 Add missing relnotes for 7.13.3 and 7.13.4
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: v7.13.3, v7.13.4

#879 Add core web vitals
  docs/en/observability/user-experience-visualizations.asciidoc
Labels: v7.14.0

#888 [7.x] Add core web vitals (#879)
  docs/en/observability/user-experience-visualizations.asciidoc
Labels: backport

#889 [7.14] Add core web vitals (#879)
  docs/en/observability/user-experience-visualizations.asciidoc
Labels: backport

#890 Add note about avoid using leaderelection in large clusters
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
Labels: Team:Integrations

#893 [7.14] [Elastic Agent] Document usage inside a container (#757)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: backport

#892 [7.x] [Elastic Agent] Document usage inside a container (#757)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: backport

#886 [7.14] Add missing relnotes for 7.13.3 and 7.13.4 (#883)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#887 [7.13] Add missing relnotes for 7.13.3 and 7.13.4 (#883)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#885 [7.x] Add missing relnotes for 7.13.3 and 7.13.4 (#883)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#882 small placeholder file and link to git repo api docs
  docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Fleet

#894 [7.x] small placeholder file and link to git repo api docs (#882)
  docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#895 [7.14] small placeholder file and link to git repo api docs (#882)
  docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#903 Link Fleet Overview to Fleet API Docs page
  docs/en/ingest-management/overview.asciidoc
Labels: Team:Fleet, v7.14.0, v7.15.0

#906 [7.14] Link Fleet Overview to Fleet API Docs page (#903)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#905 [7.x] Link Fleet Overview to Fleet API Docs page (#903)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#897 Fleet-managed agents: Add logging content
  docs/en/ingest-management/elastic-agent/elastic-agent-logging.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/images/kibana-fleet-datasets.png
  docs/en/ingest-management/images/kibana-fleet-log-levels.png
Labels: Team:Fleet, v7.13.0, v7.14.0

#908 [7.x] Fleet-managed agents: Add logging content (#897)
  docs/en/ingest-management/elastic-agent/elastic-agent-logging.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/images/kibana-fleet-datasets.png
  docs/en/ingest-management/images/kibana-fleet-log-levels.png
Labels: backport

#909 [7.13] Fleet-managed agents: Add logging content (#897)
  docs/en/ingest-management/elastic-agent/elastic-agent-logging.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/images/kibana-fleet-datasets.png
  docs/en/ingest-management/images/kibana-fleet-log-levels.png
Labels: backport

#910 [7.14] Fleet-managed agents: Add logging content (#897)
  docs/en/ingest-management/elastic-agent/elastic-agent-logging.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/images/kibana-fleet-datasets.png
  docs/en/ingest-management/images/kibana-fleet-log-levels.png
Labels: backport

#898 example for resetting a package to bring back the dashboard assets
  docs/en/ingest-management/faq.asciidoc
Labels: Team:Fleet, v7.14.0, v7.15.0

#913 [7.x] example for resetting a package to bring back the dashboard assets (#898)
  docs/en/ingest-management/faq.asciidoc
Labels: backport

#914 [7.14] example for resetting a package to bring back the dashboard assets (#898)
  docs/en/ingest-management/faq.asciidoc
Labels: backport

#904 Add logstash section to existing elastic agent configuration docs
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: Team:Agent, v7.14.0, v7.15.0

#922 [7.x] Add logstash section to existing configuration docs (#904)
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: backport

#923 [7.14] Add logstash section to existing configuration docs (#904)
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
Labels: backport

#896 Add known issue about secrets entered in Kibana
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: Team:Agent, Team:Fleet, v7.14.0, v7.15.0

#915 Add beats and Elastic Agent capabilities comparison
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/images/agent-metrics-dashboard.png
  docs/en/ingest-management/images/agent-monitoring-assets.png
  docs/en/ingest-management/images/agent-monitoring-settings.png
  docs/en/ingest-management/index.asciidoc
Labels: Team:Agent, v7.14.0

#925 [7.14] Add known issue about secrets entered in Kibana (#896)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#924 [7.x] Add known issue about secrets entered in Kibana (#896)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#902 Add info about --insecure flag to agent install docs
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: Team:Fleet, v7.14.0, v7.15.0

#926 [7.x] Add beats and Elastic Agent capabilities comparison (#915)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/images/agent-metrics-dashboard.png
  docs/en/ingest-management/images/agent-monitoring-assets.png
  docs/en/ingest-management/images/agent-monitoring-settings.png
  docs/en/ingest-management/index.asciidoc
Labels: backport

#899 Mention Elastic Agent monitoring in the Fleet docs
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
Labels: Team:Agent, v7.14.0, v7.15.0

#931 [7.14] Mention Elastic Agent monitoring in the Fleet docs (#899)
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport

#930 [7.x] Mention Elastic Agent monitoring in the Fleet docs (#899)
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport

#929 [7.14] Add info about --insecure flag to agent install docs (#902)
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#927 [7.14] Add beats and Elastic Agent capabilities comparison (#915)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/images/agent-metrics-dashboard.png
  docs/en/ingest-management/images/agent-monitoring-assets.png
  docs/en/ingest-management/images/agent-monitoring-settings.png
  docs/en/ingest-management/index.asciidoc
Labels: backport

#928 [7.x] Add info about --insecure flag to agent install docs (#902)
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#932 Remove review comments and add missing support statement
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: v7.14.0, v7.15.0

#933 [7.x] Remove review comments and add missing support statement (#932)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#934 [7.14] Remove review comments and add missing support statement (#932)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#884 Describe how to view Elastic Agent status
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/view-elastic-agent-status.asciidoc
  docs/en/ingest-management/images/agent-status-filter.png
  docs/en/ingest-management/images/agent-status.png
  docs/en/ingest-management/images/view-agent-logs.png
Labels: Team:Agent, v7.14.0, v7.15.0

#937 [7.14] Describe how to view Elastic Agent status (#884)
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/view-elastic-agent-status.asciidoc
  docs/en/ingest-management/images/agent-status-filter.png
  docs/en/ingest-management/images/agent-status.png
  docs/en/ingest-management/images/view-agent-logs.png
Labels: backport

#936 [7.x] Describe how to view Elastic Agent status (#884)
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/view-elastic-agent-status.asciidoc
  docs/en/ingest-management/images/agent-status-filter.png
  docs/en/ingest-management/images/agent-status.png
  docs/en/ingest-management/images/view-agent-logs.png
Labels: backport
