Repository elastic/observability-docs, pull requests merged in 2021-12, with the labels that each got.

#1113 Update faq.asciidoc
  docs/en/ingest-management/faq.asciidoc
Labels: docs, v8.0.0, v7.16.0, v7.15.0

#1304 [7.16] Update faq.asciidoc (#1113)
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport

#1302 [8.0] Update faq.asciidoc (#1113)
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport

#1287 Review documentation regarding self-managed package registry
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/fleet/air-gapped.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/integrations/air-gapped.asciidoc
  docs/en/integrations/what-is-an-integration.asciidoc
Labels: v8.0.0, v7.16.0, 7.16-candidate, 8.0-candidate, Team:Ecosystem

#1317 [7.16] Review documentation regarding self-managed package registry (#1287)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/fleet/air-gapped.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/integrations/air-gapped.asciidoc
  docs/en/integrations/what-is-an-integration.asciidoc
Labels: backport

#1320 [7.15] docs: fix bad link for 7.16
  docs/en/observability/ingest-splunk.asciidoc
Labels: v7.13.0, Team:Docs, v7.14.0, v7.15.0

#1326 [7.16] Add CI/CD Observability content (#1266)
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/advanced-arch-observability.png
  docs/en/observability/images/ansible-service-map.png
  docs/en/observability/images/ci-cd-overview.png
  docs/en/observability/images/concourse-ci-traces.png
  docs/en/observability/images/configure-otel-plugin.png
  docs/en/observability/images/jenkins-ansible-pipeline.png
  docs/en/observability/images/jenkins-concourse.png
  docs/en/observability/images/jenkins-dashboard-import.png
  docs/en/observability/images/jenkins-dashboard-ready.png
  docs/en/observability/images/jenkins-dashboard.png
  docs/en/observability/images/jenkins-jvm-indicators.png
  docs/en/observability/images/jenkins-kpis.png
  docs/en/observability/images/jenkins-makefile.png
  docs/en/observability/images/jenkins-maven-pipeline.png
  docs/en/observability/images/jenkins-pipeline-build.png
  docs/en/observability/images/jenkins-pipeline-context.png
  docs/en/observability/images/jenkins-pipeline-errors.png
  docs/en/observability/images/jenkins-pipeline-overview.png
  docs/en/observability/images/jenkins-pipeline-trace.png
  docs/en/observability/images/jenkins-plugin-manager.png
  docs/en/observability/images/jenkins-server.png
  docs/en/observability/images/jenkins-servers.png
  docs/en/observability/images/jenkins-service-map.png
  docs/en/observability/images/kibana-url.png
  docs/en/observability/images/simple-arch-observability.png
  docs/en/observability/index.asciidoc
Labels: backport

#1327 [7.15] Add CI/CD Observability content (#1266)
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/advanced-arch-observability.png
  docs/en/observability/images/ansible-service-map.png
  docs/en/observability/images/ci-cd-overview.png
  docs/en/observability/images/concourse-ci-traces.png
  docs/en/observability/images/configure-otel-plugin.png
  docs/en/observability/images/jenkins-ansible-pipeline.png
  docs/en/observability/images/jenkins-concourse.png
  docs/en/observability/images/jenkins-dashboard-import.png
  docs/en/observability/images/jenkins-dashboard-ready.png
  docs/en/observability/images/jenkins-dashboard.png
  docs/en/observability/images/jenkins-jvm-indicators.png
  docs/en/observability/images/jenkins-kpis.png
  docs/en/observability/images/jenkins-makefile.png
  docs/en/observability/images/jenkins-maven-pipeline.png
  docs/en/observability/images/jenkins-pipeline-build.png
  docs/en/observability/images/jenkins-pipeline-context.png
  docs/en/observability/images/jenkins-pipeline-errors.png
  docs/en/observability/images/jenkins-pipeline-overview.png
  docs/en/observability/images/jenkins-pipeline-trace.png
  docs/en/observability/images/jenkins-plugin-manager.png
  docs/en/observability/images/jenkins-server.png
  docs/en/observability/images/jenkins-servers.png
  docs/en/observability/images/jenkins-service-map.png
  docs/en/observability/images/kibana-url.png
  docs/en/observability/images/simple-arch-observability.png
  docs/en/observability/index.asciidoc
Labels: backport

#1325 [8.0] Add CI/CD Observability content (#1266)
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/advanced-arch-observability.png
  docs/en/observability/images/ansible-service-map.png
  docs/en/observability/images/ci-cd-overview.png
  docs/en/observability/images/concourse-ci-traces.png
  docs/en/observability/images/configure-otel-plugin.png
  docs/en/observability/images/jenkins-ansible-pipeline.png
  docs/en/observability/images/jenkins-concourse.png
  docs/en/observability/images/jenkins-dashboard-import.png
  docs/en/observability/images/jenkins-dashboard-ready.png
  docs/en/observability/images/jenkins-dashboard.png
  docs/en/observability/images/jenkins-jvm-indicators.png
  docs/en/observability/images/jenkins-kpis.png
  docs/en/observability/images/jenkins-makefile.png
  docs/en/observability/images/jenkins-maven-pipeline.png
  docs/en/observability/images/jenkins-pipeline-build.png
  docs/en/observability/images/jenkins-pipeline-context.png
  docs/en/observability/images/jenkins-pipeline-errors.png
  docs/en/observability/images/jenkins-pipeline-overview.png
  docs/en/observability/images/jenkins-pipeline-trace.png
  docs/en/observability/images/jenkins-plugin-manager.png
  docs/en/observability/images/jenkins-server.png
  docs/en/observability/images/jenkins-servers.png
  docs/en/observability/images/jenkins-service-map.png
  docs/en/observability/images/kibana-url.png
  docs/en/observability/images/simple-arch-observability.png
  docs/en/observability/index.asciidoc
Labels: backport

#1276 Describe how to use integrations UI to generate standalone agent config
  docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/images/add-agent-to-hosts.png
  docs/en/ingest-management/images/add-integration-standalone.png
  docs/en/ingest-management/images/download-agent-policy.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
Labels: Team:Elastic-Agent, v7.16.0

#1316 [8.0] Review documentation regarding self-managed package registry (#1287)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/fleet/air-gapped.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/integrations/air-gapped.asciidoc
  docs/en/integrations/what-is-an-integration.asciidoc
Labels: backport

#1239 Add proxy setup docs for Elastic Agent and Fleet
  docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
  docs/en/ingest-management/fleet/images/fleet-epr-proxy.png
  docs/en/ingest-management/fleet/images/fleet-proxy-settings-ui.png
  docs/en/ingest-management/images/agent-proxy-server.png
  docs/en/ingest-management/images/fleet-proxy-server.png
  docs/en/ingest-management/index.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, v7.16.0

#1332 [7.16] Add proxy setup docs for Elastic Agent and Fleet (#1239)
  docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
  docs/en/ingest-management/fleet/images/fleet-epr-proxy.png
  docs/en/ingest-management/fleet/images/fleet-proxy-settings-ui.png
  docs/en/ingest-management/images/agent-proxy-server.png
  docs/en/ingest-management/images/fleet-proxy-server.png
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1330 [7.16] Describe how to use integrations UI to generate standalone agent config (#1276)
  docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/images/add-agent-to-hosts.png
  docs/en/ingest-management/images/add-integration-standalone.png
  docs/en/ingest-management/images/download-agent-policy.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
Labels: backport

#1331 [8.0] Add proxy setup docs for Elastic Agent and Fleet (#1239)
  docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
  docs/en/ingest-management/fleet/images/fleet-epr-proxy.png
  docs/en/ingest-management/fleet/images/fleet-proxy-settings-ui.png
  docs/en/ingest-management/images/agent-proxy-server.png
  docs/en/ingest-management/images/fleet-proxy-server.png
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1329 [8.0] Describe how to use integrations UI to generate standalone agent config (#1276)
  docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/images/add-agent-to-hosts.png
  docs/en/ingest-management/images/add-integration-standalone.png
  docs/en/ingest-management/images/download-agent-policy.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
Labels: backport

#1319 Add 7.16 release notes for Elastic Agent and Fleet
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
Labels: docs, v7.16.0

#1333 [7.16] Add 7.16 release notes for Elastic Agent and Fleet (#1319)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
Labels: backport

#1303 [main] Update faq.asciidoc (#1113)
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport

#1338 Update ci-cd-observability.asciidoc
  docs/en/observability/ci-cd-observability.asciidoc
Labels: v8.0.0, Team:Docs, v7.16.0, v8.1.0

#1342 [7.16] Update ci-cd-observability.asciidoc (#1338)
  docs/en/observability/ci-cd-observability.asciidoc
Labels: backport

#1341 [8.0] Update ci-cd-observability.asciidoc (#1338)
  docs/en/observability/ci-cd-observability.asciidoc
Labels: backport

#1263 Indicate --url is required when enrolling a fleet server with a cert
  docs/en/ingest-management/commands.asciidoc
Labels: backport, blocked, v7.14.0, Team:Elastic-Agent-Control-Plane

#1334 Adding PowerShell to download and extract Endpoint agent on Windows
  docs/en/ingest-management/tab-widgets/download.asciidoc
Labels: Team:Docs, backport-7.16, backport-8.0

#1349 Update install-integration-assets.asciidoc
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
Labels: backport-7.16, backport-8.0

#1299 [Hosted Elastic Agent] Add info about auto unenrollment
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: v8.0.0, v7.16.0, Team:Elastic-Agent-Control-Plane, backport-7.16, backport-8.0

#1356 Update fleet-settings.asciidoc with caveat for Fleet URL, take2
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: v7.16.0, backport-7.16, backport-8.0

#1306 Update elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
Labels: Team:Fleet, backport-7.16, backport-8.0

#1345 Fix inaccuracies in the Fleet and Elastic Agent overview
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/overview.asciidoc
Labels: v7.16.0, backport-7.16, backport-8.0

#1362 Fix link to air gapped registry docs
  docs/en/observability/whats-new.asciidoc
Labels: v7.15.0

#1365 Update screen capture
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
Labels: v7.16.0, backport-7.16, backport-8.0

#1359 docs: update APM quick start guide
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/tab-widgets/add-apm-integration/content.asciidoc
  docs/en/observability/tab-widgets/add-apm-integration/images/add-integration-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-add-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-edit-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-switch-to-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-switch-to-ea.png
  docs/en/observability/tab-widgets/add-apm-integration/images/kibana-fleet-integrations-apm-overview.png
  docs/en/observability/tab-widgets/add-apm-integration/images/kibana-fleet-integrations-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/kibana-fleet-policies-default-with-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/widget.asciidoc
  observability/images/add-integration-apm.png
  observability/images/cloud-add-apm.png
  observability/images/cloud-edit-apm.png
  observability/images/cloud-switch-to-apm.png
  observability/images/cloud-switch-to-ea.png
  observability/images/kibana-fleet-integrations-apm-overview.png
  observability/images/kibana-fleet-policies-default-with-apm.png
Labels: backport-7.16, backport-8.0

#1284 Add documentation for the elastic-agent diagnostics pprof commands
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, backport-8.0

#1380 Update TLS cert alert image
  docs/en/observability/images/tls-alert.png
Labels: v8.0.0, v7.16.0, backport-7.16, backport-8.0

#1340 Document how to create user or api key for standalone agent
  docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/images/copy-api-key.png
  docs/en/ingest-management/images/create-standalone-agent-role.png
  docs/en/ingest-management/index.asciidoc
Labels: v8.0.0, v7.16.0, backport-7.16, backport-8.0

#1390 Fix link to Kibana role management docs
  docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
Labels: Team:Elastic-Agent, backport-8.0

#1392 Add 7.17 to mergify
  .mergify.yml
Labels: backport-skip

#1368 Update overview.asciidoc
  docs/en/ingest-management/overview.asciidoc
Labels: Team:Fleet, backport-7.16, backport-8.0

#1396 Update fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport-7.16, backport-8.0

#1399 [7.17] Update fleet-server.asciidoc (#1396)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#1400 [7.17] Update overview.asciidoc (#1368)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1344 Remove air-gapped topic from the integrations dev guide
  docs/en/integrations/air-gapped.asciidoc
  docs/en/integrations/index.asciidoc
Labels: v7.16.0, backport-skip

#1402 Fix links on "Fleet and Elastic Agent overview" page with wrong syntax
  docs/en/ingest-management/overview.asciidoc
Labels: backport-7.16, backport-8.0

#1403 [8.0] FIx links on "Fleet and Elastic Agent overview" (#1402)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1405 [7.17] FIx links on "Fleet and Elastic Agent overview" (#1402)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1404 [main] FIx links on "Fleet and Elastic Agent overview" (#1402)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#1374 Add docs for --fleet-server-es-ca-trusted-fingerprint
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/security/.certificates.asciidoc.swp
  docs/en/ingest-management/security/certificates.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, backport-8.0

#1367 [Fleet] Add known issue to Fleet 7.16
  docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
Labels: Team:Fleet, v7.16.0, backport-7.16

#1410 Update README.md
  README.md
Labels: backport-skip

#1375 Document command-line flag for delaying enrollment
  docs/en/ingest-management/commands.asciidoc
Labels: v8.0.0, Team:Fleet, v7.16.0, backport-7.16, backport-8.0, backport-7.17
