Repository elastic/observability-docs, pull requests merged in 2021-08, with the labels that each got.

#912 Update images for 7.14 to reflect Amsterdam EUI theme
  docs/en/observability/images/apm-app-landing.png
  docs/en/observability/images/apm.png
  docs/en/observability/images/js-errors.png
  docs/en/observability/images/kubernetes-filter.png
  docs/en/observability/images/log-event-details.png
  docs/en/observability/images/log-rate.png
  docs/en/observability/images/logs-app.png
  docs/en/observability/images/metrics-app.png
  docs/en/observability/images/metrics-explorer-filter.png
  docs/en/observability/images/metrics-explorer.png
  docs/en/observability/images/metrics-ml-jobs.png
  docs/en/observability/images/metrics-summary.png
  docs/en/observability/images/obs-overview-ue.png
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/pod-metrics.png
  docs/en/observability/images/uptime-summary.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/images/visitor-breakdown.png
  docs/en/observability/observability-ui.asciidoc
Labels: Team:Docs, v7.14.0

#940 [7.14] Update images for 7.14 to reflect Amsterdam EUI theme (#912)
  docs/en/observability/images/apm-app-landing.png
  docs/en/observability/images/apm.png
  docs/en/observability/images/js-errors.png
  docs/en/observability/images/kubernetes-filter.png
  docs/en/observability/images/log-event-details.png
  docs/en/observability/images/log-rate.png
  docs/en/observability/images/logs-app.png
  docs/en/observability/images/metrics-app.png
  docs/en/observability/images/metrics-explorer-filter.png
  docs/en/observability/images/metrics-explorer.png
  docs/en/observability/images/metrics-ml-jobs.png
  docs/en/observability/images/metrics-summary.png
  docs/en/observability/images/obs-overview-ue.png
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/pod-metrics.png
  docs/en/observability/images/uptime-summary.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/images/visitor-breakdown.png
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#941 [7.x] Update images for 7.14 to reflect Amsterdam EUI theme (#912)
  docs/en/observability/images/apm-app-landing.png
  docs/en/observability/images/apm.png
  docs/en/observability/images/js-errors.png
  docs/en/observability/images/kubernetes-filter.png
  docs/en/observability/images/log-event-details.png
  docs/en/observability/images/log-rate.png
  docs/en/observability/images/logs-app.png
  docs/en/observability/images/metrics-app.png
  docs/en/observability/images/metrics-explorer-filter.png
  docs/en/observability/images/metrics-explorer.png
  docs/en/observability/images/metrics-ml-jobs.png
  docs/en/observability/images/metrics-summary.png
  docs/en/observability/images/obs-overview-ue.png
  docs/en/observability/images/page-load-duration.png
  docs/en/observability/images/pod-metrics.png
  docs/en/observability/images/uptime-summary.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/images/visitor-breakdown.png
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#935 Update Fleet user guide docs for 7.14
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-logging.asciidoc
  docs/en/ingest-management/fleet/images/add-fleet-node-on-cloud.png
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-agent.png
  docs/en/ingest-management/images/add-integration-apm.png
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/add-synthetics-integration.png
  docs/en/ingest-management/images/apply-agent-policy.png
  docs/en/ingest-management/images/assign-policy.png
  docs/en/ingest-management/images/create-agent-policy.png
  docs/en/ingest-management/images/create-token.png
  docs/en/ingest-management/images/fleet-agents.png
  docs/en/ingest-management/images/fleet-settings-ssl.png
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/images/kibana-apm-sample-data.png
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-apm-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-apm.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-apm.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-start.png
  docs/en/ingest-management/images/revoke-token.png
  docs/en/ingest-management/images/show-token.png
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: Team:Docs, v7.14.0, v7.15.0

#946 docs: update APM data stream naming scheme
  docs/en/ingest-management/data-streams.asciidoc
Labels: v7.14.0, v7.15.0

#948 [7.x] docs: update apm ds naming scheme (#946)
  docs/en/ingest-management/data-streams.asciidoc
Labels: backport

#949 [7.14] docs: update apm ds naming scheme (#946)
  docs/en/ingest-management/data-streams.asciidoc
Labels: backport

#945 [7.14] Update Fleet user guide docs for 7.14 (#935)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-logging.asciidoc
  docs/en/ingest-management/fleet/images/add-fleet-node-on-cloud.png
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-agent.png
  docs/en/ingest-management/images/add-integration-apm.png
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/add-synthetics-integration.png
  docs/en/ingest-management/images/apply-agent-policy.png
  docs/en/ingest-management/images/assign-policy.png
  docs/en/ingest-management/images/create-agent-policy.png
  docs/en/ingest-management/images/create-token.png
  docs/en/ingest-management/images/fleet-agents.png
  docs/en/ingest-management/images/fleet-settings-ssl.png
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/images/kibana-apm-sample-data.png
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-apm-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-apm.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-apm.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-start.png
  docs/en/ingest-management/images/revoke-token.png
  docs/en/ingest-management/images/show-token.png
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#944 [7.x] Update Fleet user guide docs for 7.14 (#935)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-logging.asciidoc
  docs/en/ingest-management/fleet/images/add-fleet-node-on-cloud.png
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-agent.png
  docs/en/ingest-management/images/add-integration-apm.png
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/add-synthetics-integration.png
  docs/en/ingest-management/images/apply-agent-policy.png
  docs/en/ingest-management/images/assign-policy.png
  docs/en/ingest-management/images/create-agent-policy.png
  docs/en/ingest-management/images/create-token.png
  docs/en/ingest-management/images/fleet-agents.png
  docs/en/ingest-management/images/fleet-settings-ssl.png
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/images/kibana-apm-sample-data.png
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-apm-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-apm.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-apm.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-start.png
  docs/en/ingest-management/images/revoke-token.png
  docs/en/ingest-management/images/show-token.png
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#939 [7.14] docs: What’s new?
  docs/en/observability/images/7.14-agent-unenroll-timeout.png
  docs/en/observability/images/7.14-aws-dashboards.png
  docs/en/observability/images/7.14-aws-integrations.png
  docs/en/observability/images/7.14-cluster-id-kubernetes.png
  docs/en/observability/images/7.14-fleet.png
  docs/en/observability/whats-new.asciidoc
Labels: docs, v7.14.0

#947 Remove limitations topic from Fleet and Agent docs
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
Labels: Team:Agent, v7.14.0, v7.15.0

#955 [7.x] Remove limitations topic from Fleet and Agent docs (#947)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
Labels: backport

#956 [7.14] Remove limitations topic from Fleet and Agent docs (#947)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
Labels: backport

#951 Add Fleet-related Kibana relnotes
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: Team:Fleet, v7.14.0

#957 [7.x] Add Fleet-related Kibana relnotes (#951)
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#958 [7.14] Add Fleet-related Kibana relnotes (#951)
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#961 Add known issue about problem with agents enrolled through a proxy
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: Team:Agent, v7.14.0

#963 [7.x] Add known issue about problem with agents enrolled through a proxy (#961)
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#964 [7.14] Add known issue about problem with agents enrolled through a proxy (#961)
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: backport

#950 Add known problem about default policy setup
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: Team:Fleet, v7.13.0, v7.14.0

#966 [7.x] Add known problem about default policy setup (#950)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#967 [7.14] Add known problem about default policy setup (#950)
  docs/en/ingest-management/faq.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#968 Add issue to Fleet troubleshooting page for ECE 2.10 / Fleet 7.14 issue
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: docs

#970 Update troubleshooting page to remove my "Elastic Elastic Stack" references
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: docs

#972 [7.x] Clarify topic title (#969)
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport

#973 [7.14] Clarify topic title (#969)
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport

#976 Remove SDH reference in documentation
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: docs, Team:Docs

#977 [7.x] Remove SDH reference in documentation (#976)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#979 [7.13] Remove SDH reference in documentation (#976)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#978 [7.14] Remove SDH reference in documentation (#976)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#980 [Fleet] Fix workaround for missing Fleet server policies for cloud
  docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Labels: Team:Fleet

#853 Add details for logging.metrics.enabled
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc
Labels: Team:Agent, v7.15.0

#985 [7.x] Add details for logging.metrics.enabled (#853)
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc
Labels: backport

#992 docs: fix links to PHP agent documentation
  docs/en/ingest-management/index.asciidoc
Labels: docs, v7.14.0, v7.15.0

#993 [7.x] docs: fix links to PHP agent documentation (#992)
  docs/en/ingest-management/index.asciidoc
Labels: backport

#994 [7.15] docs: fix links to PHP agent documentation (#992)
  docs/en/ingest-management/index.asciidoc
Labels: backport

#995 [7.14] docs: fix links to PHP agent documentation (#992)
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1003 [7.14] Add Elasticsearch and Logstash output settings to Elastic Agent docs (#460)
  docs/en/ingest-management/elastic-agent/configuration/authentication/kerberos-shared-settings.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/authentication/ssl-shared-settings.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-shared-settings.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.yml
  docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#943 Add capabilities to beats and agent comparison table
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: Team:Agent, v7.14.0, v7.15.0

#1011 [7.x] Add capabilities to beats and agent comparison table (#943)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1012 [7.14] Add capabilities to beats and agent comparison table (#943)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport

#1013 [7.15] Add capabilities to beats and agent comparison table (#943)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport
