Repository elastic/observability-docs, pull requests merged in 2021-05, with the labels that each got.

#602 Update getting started guide to include Fleet Server
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-agent.png
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-settings.png
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: Team:Fleet, v7.13.0

#610 Add the AWS guide
  docs/en/observability/images/EC2-instances.png
  docs/en/observability/images/EC2-logs.png
  docs/en/observability/images/S3-Server-Access-Logs.png
  docs/en/observability/images/Server-Access-Logging.png
  docs/en/observability/images/aws-billing.png
  docs/en/observability/images/configure-event-notification.png
  docs/en/observability/images/configure-notification-output.png
  docs/en/observability/images/creating-a-queue.png
  docs/en/observability/images/creating-a-s3-bucket.png
  docs/en/observability/images/ec2-dashboard.png
  docs/en/observability/images/one-bucket-archi.png
  docs/en/observability/images/two-buckets-archi.png
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: v7.12.0, v7.13.0, v7.14.0

#616 Fleet server: updating the troubleshooting info
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: Team:Agent

#621 Quick update to Fleet Server main paragraph
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: v7.13.0

#625 [7.x] Fleet server: updating the troubleshooting info (#616)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#626 [7.13] Fleet server: updating the troubleshooting info (#616)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#615 [monitor-azure] Monitor Microsoft Azure tutorial
  docs/en/observability/images/monitor-azure-add-role-assignment.png
  docs/en/observability/images/monitor-azure-billing-overview-dashboard.png
  docs/en/observability/images/monitor-azure-click-access-keys.png
  docs/en/observability/images/monitor-azure-click-app-registration.png
  docs/en/observability/images/monitor-azure-click-client-secret.png
  docs/en/observability/images/monitor-azure-click-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-click-policy.png
  docs/en/observability/images/monitor-azure-click-view-keys.png
  docs/en/observability/images/monitor-azure-cloud-overview-dashboard.png
  docs/en/observability/images/monitor-azure-compute-vms-overview-dashboard.png
  docs/en/observability/images/monitor-azure-configure-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-open-powershell.png
  docs/en/observability/images/monitor-azure-register-app.png
  docs/en/observability/images/monitor-azure-search-active-directory.png
  docs/en/observability/images/monitor-azure-search-activity-log.png
  docs/en/observability/images/monitor-azure-search-event-hubs.png
  docs/en/observability/images/monitor-azure-search-storage-accounts.png
  docs/en/observability/images/monitor-azure-search-subscriptions.png
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: v7.12.0, v7.13.0, v7.14.0

#632 [7.12] Add the AWS guide (#610)
  docs/en/observability/images/EC2-instances.png
  docs/en/observability/images/EC2-logs.png
  docs/en/observability/images/S3-Server-Access-Logs.png
  docs/en/observability/images/Server-Access-Logging.png
  docs/en/observability/images/aws-billing.png
  docs/en/observability/images/configure-event-notification.png
  docs/en/observability/images/configure-notification-output.png
  docs/en/observability/images/creating-a-queue.png
  docs/en/observability/images/creating-a-s3-bucket.png
  docs/en/observability/images/ec2-dashboard.png
  docs/en/observability/images/one-bucket-archi.png
  docs/en/observability/images/two-buckets-archi.png
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport

#631 [7.13] Add the AWS guide (#610)
  docs/en/observability/images/EC2-instances.png
  docs/en/observability/images/EC2-logs.png
  docs/en/observability/images/S3-Server-Access-Logs.png
  docs/en/observability/images/Server-Access-Logging.png
  docs/en/observability/images/aws-billing.png
  docs/en/observability/images/configure-event-notification.png
  docs/en/observability/images/configure-notification-output.png
  docs/en/observability/images/creating-a-queue.png
  docs/en/observability/images/creating-a-s3-bucket.png
  docs/en/observability/images/ec2-dashboard.png
  docs/en/observability/images/one-bucket-archi.png
  docs/en/observability/images/two-buckets-archi.png
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport

#630 [7.x] Add the AWS guide (#610)
  docs/en/observability/images/EC2-instances.png
  docs/en/observability/images/EC2-logs.png
  docs/en/observability/images/S3-Server-Access-Logs.png
  docs/en/observability/images/Server-Access-Logging.png
  docs/en/observability/images/aws-billing.png
  docs/en/observability/images/configure-event-notification.png
  docs/en/observability/images/configure-notification-output.png
  docs/en/observability/images/creating-a-queue.png
  docs/en/observability/images/creating-a-s3-bucket.png
  docs/en/observability/images/ec2-dashboard.png
  docs/en/observability/images/one-bucket-archi.png
  docs/en/observability/images/two-buckets-archi.png
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport

#629 [7.12] [monitor-azure] Monitor Microsoft Azure tutorial (#615)
  docs/en/observability/images/monitor-azure-add-role-assignment.png
  docs/en/observability/images/monitor-azure-billing-overview-dashboard.png
  docs/en/observability/images/monitor-azure-click-access-keys.png
  docs/en/observability/images/monitor-azure-click-app-registration.png
  docs/en/observability/images/monitor-azure-click-client-secret.png
  docs/en/observability/images/monitor-azure-click-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-click-policy.png
  docs/en/observability/images/monitor-azure-click-view-keys.png
  docs/en/observability/images/monitor-azure-cloud-overview-dashboard.png
  docs/en/observability/images/monitor-azure-compute-vms-overview-dashboard.png
  docs/en/observability/images/monitor-azure-configure-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-open-powershell.png
  docs/en/observability/images/monitor-azure-register-app.png
  docs/en/observability/images/monitor-azure-search-active-directory.png
  docs/en/observability/images/monitor-azure-search-activity-log.png
  docs/en/observability/images/monitor-azure-search-event-hubs.png
  docs/en/observability/images/monitor-azure-search-storage-accounts.png
  docs/en/observability/images/monitor-azure-search-subscriptions.png
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport

#628 [7.13] [monitor-azure] Monitor Microsoft Azure tutorial (#615)
  docs/en/observability/images/monitor-azure-add-role-assignment.png
  docs/en/observability/images/monitor-azure-billing-overview-dashboard.png
  docs/en/observability/images/monitor-azure-click-access-keys.png
  docs/en/observability/images/monitor-azure-click-app-registration.png
  docs/en/observability/images/monitor-azure-click-client-secret.png
  docs/en/observability/images/monitor-azure-click-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-click-policy.png
  docs/en/observability/images/monitor-azure-click-view-keys.png
  docs/en/observability/images/monitor-azure-cloud-overview-dashboard.png
  docs/en/observability/images/monitor-azure-compute-vms-overview-dashboard.png
  docs/en/observability/images/monitor-azure-configure-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-open-powershell.png
  docs/en/observability/images/monitor-azure-register-app.png
  docs/en/observability/images/monitor-azure-search-active-directory.png
  docs/en/observability/images/monitor-azure-search-activity-log.png
  docs/en/observability/images/monitor-azure-search-event-hubs.png
  docs/en/observability/images/monitor-azure-search-storage-accounts.png
  docs/en/observability/images/monitor-azure-search-subscriptions.png
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport

#627 [7.x] [monitor-azure] Monitor Microsoft Azure tutorial (#615)
  docs/en/observability/images/monitor-azure-add-role-assignment.png
  docs/en/observability/images/monitor-azure-billing-overview-dashboard.png
  docs/en/observability/images/monitor-azure-click-access-keys.png
  docs/en/observability/images/monitor-azure-click-app-registration.png
  docs/en/observability/images/monitor-azure-click-client-secret.png
  docs/en/observability/images/monitor-azure-click-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-click-policy.png
  docs/en/observability/images/monitor-azure-click-view-keys.png
  docs/en/observability/images/monitor-azure-cloud-overview-dashboard.png
  docs/en/observability/images/monitor-azure-compute-vms-overview-dashboard.png
  docs/en/observability/images/monitor-azure-configure-diagnostics-settings.png
  docs/en/observability/images/monitor-azure-open-powershell.png
  docs/en/observability/images/monitor-azure-register-app.png
  docs/en/observability/images/monitor-azure-search-active-directory.png
  docs/en/observability/images/monitor-azure-search-activity-log.png
  docs/en/observability/images/monitor-azure-search-event-hubs.png
  docs/en/observability/images/monitor-azure-search-storage-accounts.png
  docs/en/observability/images/monitor-azure-search-subscriptions.png
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport

#634 [7.x] Quick update to Fleet Server main paragraph (#621)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#619 [7.13] Update getting started guide to include Fleet Server (#602)
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-agent.png
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-settings.png
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: backport

#618 [7.x] Update getting started guide to include Fleet Server (#602)
  docs/en/ingest-management/getting-started-traces.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-agent.png
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-settings.png
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: backport

#633 tuts: single source Filebeat and Metricbeat instructions
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/tutorials.asciidoc
  docs/en/shared/install-configure-filebeat.asciidoc
  docs/en/shared/install-configure-metricbeat.asciidoc
Labels: v7.12.0, v7.13.0, v7.14.0

#637 [7.x] tuts: single source Filebeat and Metricbeat instructions (#633)
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/tutorials.asciidoc
  docs/en/shared/install-configure-filebeat.asciidoc
  docs/en/shared/install-configure-metricbeat.asciidoc
Labels: backport

#638 [7.13] tuts: single source Filebeat and Metricbeat instructions (#633)
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/tutorials.asciidoc
  docs/en/shared/install-configure-filebeat.asciidoc
  docs/en/shared/install-configure-metricbeat.asciidoc
Labels: backport

#639 [7.12] tuts: single source Filebeat and Metricbeat instructions (#633)
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/tutorials.asciidoc
  docs/en/shared/install-configure-filebeat.asciidoc
  docs/en/shared/install-configure-metricbeat.asciidoc
Labels: backport

#646 [7.x] Add placeholder file for release notes (#614)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#645 Get K8s documentation building
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Labels: Team:Agent, docs, v7.13.0

#636 Fleet: Add synthetics integration
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-synthetics-integration.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-synthetics.png
Labels: docs, v7.13.0

#656 [7.x] Fleet: Add synthetics integration (#636)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-synthetics-integration.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-synthetics.png
Labels: backport

#655 [7.13] Fleet: Add synthetics integration (#636)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/add-synthetics-integration.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/ingest-management/images/kibana-fleet-integrations-synthetics.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/ingest-management/images/kibana-fleet-policies-default-with-synthetics.png
Labels: backport

#653 [7.x] Get K8s documentation building (#645)
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Labels: backport

#654 [7.13] Get K8s documentation building (#645)
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Labels: backport

#624 Update installation instructions for Elastic Agent
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/images/kibana-fleet-policies-default-yaml.png
  docs/en/ingest-management/tab-widgets/install.asciidoc
Labels: Team:Agent, docs, v7.13.0

#657 [7.x] Update installation instructions for Elastic Agent (#624)
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/images/kibana-fleet-policies-default-yaml.png
  docs/en/ingest-management/tab-widgets/install.asciidoc
Labels: backport

#658 [7.13] Update installation instructions for Elastic Agent (#624)
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
  docs/en/ingest-management/images/kibana-fleet-policies-default-yaml.png
  docs/en/ingest-management/tab-widgets/install.asciidoc
Labels: backport

#660 [7.x] docs: update synthetics with zip support (#609)
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#659 [7.13] docs: update synthetics with zip support (#609)
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: backport

#612 Add note on how to to build the docs
  README.md
Labels: Team:Docs

#644 docs: add policy types
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/green-check.svg
  docs/en/ingest-management/images/red-x.svg
  docs/en/ingest-management/index.asciidoc
Labels: v7.13.0, v7.14.0

#669 [7.x] docs: add policy types (#644)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/green-check.svg
  docs/en/ingest-management/images/red-x.svg
  docs/en/ingest-management/index.asciidoc
Labels: backport

#670 [7.13] docs: add policy types (#644)
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/green-check.svg
  docs/en/ingest-management/images/red-x.svg
  docs/en/ingest-management/index.asciidoc
Labels: backport

#676 Add .gitignore to 7.x
  .gitignore
Labels: v7.13.0, v7.14.0

#677 [7.13] Add .gitignore to 7.x (#676)
  .gitignore
Labels: backport

#613 [Fleet Server] Add details related to API Keys
  docs/en/fleet-developer/fleet-architecture.asciidoc
  docs/en/fleet-developer/fleet-security-model.asciidoc
Labels: Team:Docs

#662 Fleet: Add migration content
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/apm-fleet-prompt.png
  docs/en/ingest-management/images/fleet-server-prompt-managed.png
  docs/en/ingest-management/images/fleet-server-prompt.png
  docs/en/ingest-management/tab-widgets/upgrade-fleet-widget.asciidoc
  docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
Labels: Team:Docs, docs, v7.13.0

#683 [7.x] Document Exploratory view (#674)
  docs/en/observability/exploratory-data-visualizations.asciidoc
  docs/en/observability/images/exploratory-view.png
  docs/en/observability/images/synthetic-monitoring-visualization.png
  docs/en/observability/images/user-experience-visualization.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetic-monitoring-visualizations.asciidoc
  docs/en/observability/user-experience-visualizations.asciidoc
Labels: backport

#684 [7.13] Document Exploratory view (#674)
  docs/en/observability/exploratory-data-visualizations.asciidoc
  docs/en/observability/images/exploratory-view.png
  docs/en/observability/images/synthetic-monitoring-visualization.png
  docs/en/observability/images/user-experience-visualization.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetic-monitoring-visualizations.asciidoc
  docs/en/observability/user-experience-visualizations.asciidoc
Labels: backport

#685 [7.x] Fleet: Add migration content (#662)
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/apm-fleet-prompt.png
  docs/en/ingest-management/images/fleet-server-prompt-managed.png
  docs/en/ingest-management/images/fleet-server-prompt.png
  docs/en/ingest-management/tab-widgets/upgrade-fleet-widget.asciidoc
  docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
Labels: backport

#686 [7.13] Fleet: Add migration content (#662)
  docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/images/apm-fleet-prompt.png
  docs/en/ingest-management/images/fleet-server-prompt-managed.png
  docs/en/ingest-management/images/fleet-server-prompt.png
  docs/en/ingest-management/tab-widgets/upgrade-fleet-widget.asciidoc
  docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
Labels: backport

#687 [7.x] Update alerting terminology (#679)
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#688 [7.13] Update alerting terminology (#679)
  docs/en/observability/configure-uptime-settings.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: backport

#690 [7.13] Clarify no import dependencies can be used with inline scripts (#682)
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport

#689 [7.x] Clarify no import dependencies can be used with inline scripts (#682)
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport

#678 Add Elastic Package Registry (EPR) overview
  docs/en/ingest-management/overview.asciidoc
Labels: docs, v7.13.0

#695 [7.13] Add Elastic Package Registry (EPR) overview (#678)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#696 [7.x] Add Elastic Package Registry (EPR) overview (#678)
  docs/en/ingest-management/overview.asciidoc
Labels: backport

#692 Update metrics widget image
  docs/en/observability/images/metrics-summary.png
  docs/en/observability/observability-ui.asciidoc
Labels: docs, v7.13.0

#697 [7.13] Update metrics widget image (#692)
  docs/en/observability/images/metrics-summary.png
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#698 [7.x] Update metrics widget image (#692)
  docs/en/observability/images/metrics-summary.png
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#673 Add topic about Fleet settings
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs, docs

#705 [7.x] Add topic about Fleet settings (#673)
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#706 [7.13] Add topic about Fleet settings (#673)
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#675 [7.13] docs: What’s new?
  docs/en/observability/images/7.13-apm-server-instance-view.png
  docs/en/observability/images/7.13-azure-logs-metrics.png
  docs/en/observability/images/7.13-improved-infra-mon.png
  docs/en/observability/images/7.13-kpi-over-time-2.png
  docs/en/observability/images/7.13-kpi-over-time.png
  docs/en/observability/images/7.13-new-analyze-data.png
  docs/en/observability/images/7.13-new-apm-fleet.png
  docs/en/observability/images/7.13-new-enhanced-host-details.png
  docs/en/observability/images/7.13-new-ml-detection.png
  docs/en/observability/images/7.13-otel.png
  docs/en/observability/images/7.13-runtime-fields-kib.png
  docs/en/observability/images/7.13-use-runtime-fields.png
  docs/en/observability/whats-new.asciidoc
Labels: v7.13.0

#702 Clean up release notes and add items from Kibana
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: docs, v7.13.0

#707 [7.13] Clean up release notes and add items from Kibana (#702)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#708 [7.x] Clean up release notes and add items from Kibana (#702)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#709 [7.13][DOCS] Fixes an attribute in what's new
  docs/en/observability/whats-new.asciidoc
Labels: docs, v7.13.0

#667 Update Elastic Agent command reference with Fleet Server flags
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: docs

#711 [7.13] Update Elastic Agent command reference with Fleet Server flags (#667)
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: backport

#710 [7.x] Update Elastic Agent command reference with Fleet Server flags (#667)
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: backport

#713 Add link to Fleet settings topic
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: Team:Docs, docs, v7.13.0

#712 Clarify breaking changes for 7.13
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: Team:Docs, docs, v7.13.0

#714 [7.x] Add link to Fleet settings topic (#713)
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: backport

#717 [7.13] Clarify breaking changes for 7.13 (#712)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#715 [7.13] Add link to Fleet settings topic (#713)
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: backport

#716 [7.x] Clarify breaking changes for 7.13 (#712)
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#728 Fixes two small errors in Fleet Server Docs
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: v7.13.0, v7.14.0

#729 [7.x] Fixes two small errors in Fleet Server Docs (#728)
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: backport

#730 [7.13] Fixes two small errors in Fleet Server Docs (#728)
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: backport

#727 Add Elastic Agent unenrollment issue
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: Team:Agent, v7.13.0

#737 [7.13] Add Elastic Agent unenrollment issue (#727)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#736 [7.x] Add Elastic Agent unenrollment issue (#727)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Labels: backport

#718 Update manual and endpoint uninstall steps
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/remove-endpoint-files/content.asciidoc
  docs/en/ingest-management/tab-widgets/remove-endpoint-files/widget.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: Team:Agent, docs, v7.13.0

#741 [7.13] Update manual and endpoint uninstall steps (#718)
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/remove-endpoint-files/content.asciidoc
  docs/en/ingest-management/tab-widgets/remove-endpoint-files/widget.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#740 [7.x] Update manual and endpoint uninstall steps (#718)
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/remove-endpoint-files/content.asciidoc
  docs/en/ingest-management/tab-widgets/remove-endpoint-files/widget.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#739 [7.13] Add stack compatibility info to Fleet Server docs (#731)
  docs/en/ingest-management/fleet/fleet-server.asciidoc
Labels: backport

#734 Update troubleshooting.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: v7.13.0, v7.14.0

#671 Document Agent/Fleet Server environment variables
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Labels: v7.13.0, v7.14.0
