Repository elastic/observability-docs, pull requests merged in 2022-02, with the labels that each got.

#1503 Update beats-agent-comparison.asciidoc for osquery
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-7.16, backport-8.0, backport-7.17

#1501 [CI/CD Observability] Bump Maven Extension version
  docs/en/observability/ci-cd-observability.asciidoc
Labels: backport-7.16

#1510 Add note to 7.16 release notes about requirement for unique integration policy names
  docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
Labels: v7.16.0, backport-7.16, backport-7.17

#1518 Add 8.1 to mergify
  .mergify.yml
Labels: backport-skip

#1486 Clarify command syntax for elastic-agent commands
  docs/en/ingest-management/commands.asciidoc
Labels: v8.0.0, Team:Elastic-Agent, v7.16.0, v8.1.0, backport-8.1, backport-7.16, backport-8.0, v7.17.0, backport-7.17

#1514 Add release notes for Elastic Agent 7.17.0
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, v7.17.0, backport-7.17

#1487 Describe filter for showing Elastic Agent integrations
  docs/en/ingest-management/images/unified-view-selector.png
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Labels: v8.0.0, Team:Elastic-Agent, v7.16.0, v8.1.0, backport-8.1, backport-7.16, backport-8.0, v7.17.0, backport-7.17

#1499 Adjust names of log files in Elastic Agent documentation
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport-8.1, backport-8.0

#1531 Use main for integrations/ecs-logging/elastic-package
  docs/en/integrations/build-integration.asciidoc
  docs/en/integrations/elastic-package.asciidoc
  docs/en/integrations/index.asciidoc
  docs/en/integrations/integration-example.asciidoc
  docs/en/integrations/publish-integration.asciidoc
  docs/en/integrations/system-testing.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport-skip

#1481 Clarify internet requirements in the Fleet FAQ
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: v8.0.0, Team:Fleet, v7.16.0, v8.1.0, backport-8.1, backport-7.16, backport-8.0, v7.17.0, backport-7.17

#1516 docs: add pytest-otel details
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/advanced-arch-observability.png
  docs/en/observability/images/pytest-otel-pipeline.png
  docs/en/observability/images/simple-arch-observability.png
Labels: docs, v8.0.0, Team:Automation, v8.1.0, backport-8.1, backport-8.0, v7.17.0, backport-7.17

#1560 Better communicate the point of the `zip_url` feature
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
Labels: docs, Team:Uptime, backport-8.1, backport-8.0

#1570 docs: add links to air gap docs
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-traces.asciidoc
Labels: Team:Docs, backport-8.1, backport-8.2, backport-8.0

#1559 Add experimental banner to Fleet API docs page
  docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
Labels: Team:Fleet, backport-8.1, backport-7.16, backport-8.0, backport-7.17

#1473 Add docs about debugging standalone Elastic Agents
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/debug-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: v8.0.0, Team:Elastic-Agent, v7.16.0, v8.1.0, backport-7.16, v7.17.0, backport-7.17

#1519 Document Beats to Agent migration
  docs/en/ingest-management/images/migration-add-integration-policy.png
  docs/en/ingest-management/images/migration-add-nginx-integration.png
  docs/en/ingest-management/images/migration-add-processor.png
  docs/en/ingest-management/images/migration-agent-data-streams.png
  docs/en/ingest-management/images/migration-agent-details.png
  docs/en/ingest-management/images/migration-agent-status-healthy.png
  docs/en/ingest-management/images/migration-event-from-agent.png
  docs/en/ingest-management/images/migration-event-from-filebeat.png
  docs/en/ingest-management/images/migration-index-lifecycle-policies.png
  docs/en/ingest-management/images/migration-preserve-raw-event.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/migrate-beats-to-agent.asciidoc
Labels: v8.0.0, Team:Elastic-Agent, v8.1.0, backport-8.1, backport-8.0

#1558 Add docs on upgrading Agent in air-gapped environment
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, backport-8.1, backport-7.16, backport-8.0, backport-7.17

#1555 Add release notes for 8.0 to Elastic Agent and Fleet docs
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
Labels: v8.0.0, Team:Elastic-Agent, Team:Fleet, backport-8.1, backport-8.0

#1590 Fixed some typos
  docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_secrets-provider.asciidoc
  docs/en/ingest-management/fleet/set-elastic-agent-enrollment-timeout.asciidoc
  docs/en/ingest-management/fleet/view-elastic-agent-status.asciidoc
  docs/en/integrations/build-integration.asciidoc
  docs/en/observability/deploy-beats-to-send-data.asciidoc
Labels: backport-8.1, backport-8.2, backport-8.0

#1595 [8.0] [Observability - CI/CD Observability] Document scripted Service Health Check (#1517)
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/ci-cd-canary-deployment-pipeline.png
Labels: backport

#1597 [7.17] [Observability - CI/CD Observability] Document scripted Service Health Check (#1517)
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/ci-cd-canary-deployment-pipeline.png
Labels: backport

#1598 [8.1] [Observability - CI/CD Observability] Document scripted Service Health Check (#1517)
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/ci-cd-canary-deployment-pipeline.png
Labels: backport

#1596 [main] [Observability - CI/CD Observability] Document scripted Service Health Check (#1517)
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/ci-cd-canary-deployment-pipeline.png
Labels: backport

#1601 Add 8.0.1 release notes for Fleet and Elastic Agent
  docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
Labels: backport-8.1, backport-8.0, v8.0.1

#1600 Correct improper capitalization
  docs/en/observability/observability-ui.asciidoc
Labels: backport-8.1, backport-7.16, backport-7.17

#1608 [7.17] Correct improper capitalization (#1600)
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#1609 [7.16] Correct improper capitalization (#1600)
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#1607 [8.1] Correct improper capitalization (#1600)
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#1606 [main] Correct improper capitalization (#1600)
  docs/en/observability/observability-ui.asciidoc
Labels: backport

#1614 Add 7.17.1 release notes for Elastic Agent and Fleet
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, v7.17.1

#1616 Update install command for rpm/deb detection
  docs/en/ingest-management/commands.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, v8.2.0, backport-skip

#1579 Add elastic-agent min requirements
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane, Team:Elastic-Agent-Control-Plane, backport-8.1
