Repository elastic/observability-docs, pull requests merged in 2022-10, with the labels that each got.

#2204 Update output-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
Labels: backport-skip

#2216 Update output-configuration.asciidoc (#2204)
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
Labels: backport-8.5

#2213 Explain why output settings might be grayed out in Fleet
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: Team:Docs, Team:Fleet, backport-8.4, backport-8.5

#2198 Add new autodiscovery docs section for k8s
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-kubernetes-autodiscovery.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-skip, Team:Cloudnative-Monitoring

#2233 Need to stipulate that a path to cert+key is acceptable in the Logstash config
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport-8.4, backport-8.5

#2174 Add Azure tutorial that shows Elastic Agent
  docs/en/observability/images/agent-tut-azure-activity-log-columns.png
  docs/en/observability/images/agent-tut-azure-activity-log-settings.png
  docs/en/observability/images/agent-tut-azure-activity-logs-dashboard.png
  docs/en/observability/images/agent-tut-azure-activity-logs.png
  docs/en/observability/images/agent-tut-azure-add-role-assignment.png
  docs/en/observability/images/agent-tut-azure-billing-dashboard.png
  docs/en/observability/images/agent-tut-azure-click-client-secret.png
  docs/en/observability/images/agent-tut-azure-create-eventhub.png
  docs/en/observability/images/agent-tut-azure-event-hub-diagram.png
  docs/en/observability/images/agent-tut-azure-integration-settings.png
  docs/en/observability/images/agent-tut-azure-log-categories.png
  docs/en/observability/images/agent-tut-azure-register-app.png
  docs/en/observability/images/monitor-azure-native-create-elastic-resource.png
  docs/en/observability/images/monitor-azure-native-elastic-config-logs-metrics.png
  docs/en/observability/images/monitor-azure-native-elastic-deployment.png
  docs/en/observability/images/monitor-azure-native-elastic-vms.png
  docs/en/observability/images/monitor-azure-native-kibana-logs-app.png
  docs/en/observability/images/monitor-azure-native-kibana-observability-page-data.png
  docs/en/observability/images/monitor-azure-native-kibana-vms-logs.png
  docs/en/observability/images/monitor-azure-native-kibana-vms-metrics-detail.png
  docs/en/observability/images/monitor-azure-native-kibana-vms-metrics.png
  docs/en/observability/images/monitor-azure-search-elasticsearch.png
  docs/en/observability/monitor-azure-agent.asciidoc
  docs/en/observability/monitor-azure-beats.asciidoc
  docs/en/observability/monitor-azure-native.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport-8.4, backport-8.5

#2237 Mark hints autodiscovery as beta
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-kubernetes-autodiscovery.asciidoc
Labels: Team:Cloudnative-Monitoring, backport-8.5

#2236 Update view-integration-policies.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
Labels: Team:Docs

#2259 Update view-integration-policies.asciidoc (#2236)
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
Labels: backport-8.5

#2228 Clarify terminology around adding an integration
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Labels: Team:Docs, Team:Fleet, backport-8.4, backport-8.5

#2255 Minor improvements in hints autodiscovery docs
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-kubernetes-autodiscovery.asciidoc
Labels: backport-skip, Team:Cloudnative-Monitoring, backport-8.5

#2267 [DOCS] Assign users to Observability cases
  docs/en/observability/create-cases.asciidoc
  docs/en/observability/grant-cases-access.asciidoc
  docs/en/observability/images/cases.png
  docs/en/observability/manage-cases.asciidoc
Labels: docs, Team:Docs, v8.5.0, v8.6.0, backport-8.5

#2243 [synthetics] Link to `request` parameter example
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport-8.4, backport-8.5

#2246 [synthetics] Add information about the `push` command's `--yes` option
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
Labels: backport-8.5

#2275 Highlight statement that only one agent can run on a host
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
Labels: Team:Docs, backport-8.3, backport-8.4, backport-8.5

#2277 [synthetics] Document how to import NPM packages and their limitations
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport-8.5

#2285 Add 7.17.7 Fleet/Agent release notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-8.5

#2231 [Discuss] New issue forms
  .github/ISSUE_TEMPLATE/0-community-request.yaml
  .github/ISSUE_TEMPLATE/8.6-request.yaml
  .github/ISSUE_TEMPLATE/8.7-request.yaml
  .github/ISSUE_TEMPLATE/docs-request.md
  .github/ISSUE_TEMPLATE/other-request.yaml
Labels: Team:Docs, request, backport-skip, 8.6-request, 8.7-request, 💝 community

#2264 Add Fleet/Agent release notes for 8.5
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Labels: Team:Fleet, backport-8.5
