Repository elastic/observability-docs, pull requests merged in 2022-11, with the labels that each got.

#2242 [synthetics] Update available methods for creating monitors
  docs/en/observability/images/create-browser-monitor-project-monitors.png
  docs/en/observability/images/create-browser-monitor-ui.png
  docs/en/observability/images/private-locations-monitor-locations.png
  docs/en/observability/images/synthetics-agent-policy-select.png
  docs/en/observability/images/synthetics-agent-policy.png
  docs/en/observability/images/synthetics-integration-agent-options.png
  docs/en/observability/images/synthetics-integration-inline-script.png
  docs/en/observability/images/synthetics-integration-selective-tests.png
  docs/en/observability/images/synthetics-integration-source-type.png
  docs/en/observability/images/synthetics-integration-throttling.png
  docs/en/observability/images/synthetics-integration.png
  docs/en/observability/images/synthetics-overview.png
  docs/en/observability/images/uptime-app-add-monitor-browser.png
  docs/en/observability/images/uptime-app-inline-script.png
  docs/en/observability/images/uptime-set-up-app.png
  docs/en/observability/images/uptime-set-up-heartbeat.png
  docs/en/observability/images/uptime-set-up-project-monitors.png
  docs/en/observability/images/uptime-set-up-ui.asciidoc.png
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-journeys.asciidoc
  docs/en/observability/synthetics-manage-monitors.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
  docs/en/observability/synthetics-private-location.asciidoc
  docs/en/observability/synthetics-run-test.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-delete-monitor-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-delete-monitor-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-monitor-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-monitor-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-test-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-test-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-configure-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-configure-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-inline-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-inline-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-widget.asciidoc
  docs/en/observability/uptime-set-up-app.asciidoc
  docs/en/observability/uptime-set-up-choose-project-monitors.asciidoc
  docs/en/observability/uptime-set-up-heartbeat.asciidoc
  docs/en/observability/uptime-set-up.asciidoc
Labels: backport-8.5

#2289 [DOCS] Diagnostic Pprof
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: docs, backport-7.17, backport-8.4, backport-8.5

#2315 adjust for removed kibana security settings
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
Labels: backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-8.4, backport-8.5

#2316 Remove redundant jump link
  docs/en/ingest-management/agent-policies.asciidoc
Labels: backport-8.4, backport-8.5

#2325 Fix typo in topic about creating agent policy
  docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
Labels: Team:Docs, backport-8.5

#2329 Add 8.5 to backportrc
  .backportrc.json
Labels: Team:Docs, backport-8.5

#2333 [DOCS] Remove alerts from cases
  docs/en/observability/grant-cases-access.asciidoc
  docs/en/observability/manage-cases.asciidoc
Labels: Team:Docs, backport-skip, v8.6.0

#2331 [synthetics] Remove remaining references to the Elastic Synthetics integration
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/synthetics-run-test.asciidoc
Labels: backport-8.5

#2224 Add docs about package verification
  docs/en/ingest-management/fleet/air-gapped.asciidoc
  docs/en/ingest-management/integrations/package-signatures.asciidoc
Labels: Team:Docs, Team:Fleet, backport-8.5

#2341 Change Endpoint and Cloud Security to Elastic Defend in Fleet docs
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/migrate-auditbeat-to-agent.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.5

#2334 Improve docs about agent monitoring
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/elastic-agent-logging.asciidoc
  docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/view-elastic-agent-status.asciidoc
  docs/en/ingest-management/images/agent-set-logging-level.png
  docs/en/ingest-management/images/selected-agent-metrics-dashboard.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/redirects.asciidoc
Labels: Team:Docs, backport-8.5

#2348 [8.5] Add docker run command (#2291)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport

#2349 [main] Add docker run command (#2291)
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport

#2350 [DOC] Typos
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.5

#2346 actions: use github actions
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  .ci/jobs/observability-docs-mbp.yml
  .ci/jobs/observability-docs.yml
  .github/workflows/doc-preview.yml
Labels: Team:Automation, backport-skip

#2298 Update package registry distributions according to Package Storage V2
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-skip

#2356 Correcting the air gap comment
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-8.5

#2361 Add Fleet/Agent 8.5.1 release notes
  docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Labels: backport-8.5

#2335 Add GKE docs section
  docs/en/ingest-management/elastic-agent/install-elastic-agent-in-container.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-gke-standard-managed-by-fleet.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-skip, Team:Cloudnative-Monitoring, 8.6-candidate, v8.6.0

#2360 Add EKS documentation
  docs/en/ingest-management/elastic-agent/install-elastic-agent-in-container.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-eks-managed-by-fleet.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-skip, 8.6-candidate, v8.6.0

#2344 Fix mini toc in level 3 topics
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-8.5

#2369 backport: Add 8.6 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#2371 [Fleet] Update logstash client certificate generation
  docs/en/ingest-management/security/logstash-certificates.asciidoc
Labels: Team:Fleet, backport-8.5, backport-8.6

#2385 Remove link to Elastic helm charts
  docs/en/observability/monitor-k8s/monitor-k8s.asciidoc
Labels: backport-8.5, backport-8.6

#2368 [agent] Add documentation for Agent encryption at rest
  docs/en/ingest-management/elastic-agent/elastic-agent-encryption.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Elastic-Agent, backport-8.5

#2391 [main] Need to get an emergency release note out for 8.5.1 (#2390)
  docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Labels: backport

#2392 Add known issue with offline agents failing to unenroll from Fleet
  docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Labels: backport-8.5

#2293 Clarify that Fleet Server certs are managed by cloud
  docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
Labels: backport-8.5, backport-8.6

#2393 Add Fleet/Agent 8.5.2 release notes
  docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Labels: backport-8.5

#2395 Correction on step 5
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
Labels: docs, backport-skip

#2214 Add AWS Serverless Forwarder to Obs Guide
  docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder-configuration.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-serverless-transform.asciidoc
  docs/en/observability/aws-serverless-troubleshooting.asciidoc
  docs/en/observability/images/aws-serverless-forwarder-create-function.png
  docs/en/observability/images/aws-serverless-forwarder-install-assets.png
  docs/en/observability/images/aws-serverless-lambda-flow.png
  docs/en/observability/images/false-after-multi.png
  docs/en/observability/images/false-before-multi.png
  docs/en/observability/images/multiline-regexp-test-repl-main.png
  docs/en/observability/images/multiline-regexp-test-repl-run.png
  docs/en/observability/images/true-after-multi.png
  docs/en/observability/images/true-before-multi.png
  docs/en/observability/index.asciidoc
Labels: backport-8.3, backport-8.1, backport-7.16, backport-8.2, backport-8.0, backport-7.17, backport-8.4, backport-8.5

#2410 Update wget command
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
Labels: backport-8.5, backport-8.6

#2420 Azure AKS on Fleet
  docs/en/ingest-management/elastic-agent/install-elastic-agent-in-container.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/run-container-common/deploy-kube-state-metrics.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-aks-managed-by-fleet.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: docs, Team:Cloudnative-Monitoring, backport-8.6

#2425 Fix docs on synthetics monitor interval
  docs/en/observability/synthetics-configuration.asciidoc
Labels: docs, backport-skip

#2418 docs: add `0.0.0.0` tip
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/tab-widgets/add-apm-integration/content.asciidoc
Labels: backport-8.5, backport-8.6
