Repository elastic/observability-docs, pull requests merged in 2022-03, with the labels that each got.

#1621 update image and text for Integrations Server
  docs/en/ingest-management/fleet/images/integrations-server-hosted-container.png
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
  docs/en/observability/images/integrations-server-hosted-container.png
Labels: docs, Team:Docs, backport-8.0

#1610 Remove coming tags for 8.0.1
  docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
Labels: backport-8.1, backport-8.0

#1623 Update steps for APM Server Quick Start
  docs/en/observability/tab-widgets/add-apm-integration/content.asciidoc
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-add-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-apm-policy-view.png
Labels: docs, Team:Docs, backport-8.0

#1631 Update set-elastic-agent-enrollment-timeout.asciidoc
  docs/en/ingest-management/fleet/set-elastic-agent-enrollment-timeout.asciidoc
Labels: Team:Fleet, backport-8.1, backport-7.16, backport-8.0, backport-7.17

#1602 Add troubleshooting steps for failed 8.x upgrades
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Fleet, backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-7.17

#1640 Update the add agent graphic
  docs/en/observability/images/add-agent.png
Labels: Team:Docs, backport-8.1

#1627 Add metrics buffer documentation
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, v8.2.0, backport-skip

#1645 Remove superuser requirement from Fleet
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/fleet-limitations.asciidoc
  docs/en/ingest-management/fleet/fleet.asciidoc
  docs/en/ingest-management/migrate-beats-to-agent.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-traces.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, v8.1.0, backport-8.1

#1643 8.1: What's new in Observability?
  docs/en/observability/images/81-alerts.png
  docs/en/observability/images/81-privs.png
  docs/en/observability/whats-new.asciidoc
Labels: Team:Docs

#1644 Update whats-new.asciidoc
  docs/en/observability/whats-new.asciidoc
Labels: backport-skip

#1642 Add 8.1.0 Fleet and Elastic Agent release notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, v8.1.0, backport-8.1

#1620 Update link to the Elastic Agent code repository
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Elastic-Agent, v8.2.0, backport-8.2

#1647 docs: Mention Fleet-managed requirement in APM quick start
  docs/en/observability/ingest-traces.asciidoc
Labels: Team:Docs, backport-8.1, backport-8.0

#1648 Update Fleet docs to reflect removal of default agent policy
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/create-agent-policies-no-UI.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/images/add-fleet-server.png
  docs/en/ingest-management/images/add-agent.png
  docs/en/ingest-management/images/add-integration.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/install.asciidoc
Labels: Team:Fleet, v8.1.0, backport-8.1

#1656 Remove duplicate text from Synthetics quickstart
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
Labels: Synthetics, backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-7.17

#1661 Add info about default policies to Fleet release notes
  docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
Labels: Team:Fleet, v8.1.0, backport-8.1

#1668 Elastic-agent: add documentation about running agent on managed kubenetes environmets, need to adjust resource configuration
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
Labels: backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-7.17

#1679 Add missing description for FLEET_SERVER_POLICY_ID env var
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
Labels: Team:Fleet, v8.1.0, backport-8.1

#1680 Clarify that extra privileges are required to delete system indices
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Fleet, backport-8.1, backport-8.0

#1678 Update synthetics_check_details image
  docs/en/observability/images/synthetics_check_details.png
Labels: backport-8.1

#1687 [Fleet] Use reset API instead of system indices for reseting cloud policy
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Fleet, backport-skip

#1683 [CI/CD Observability] Bump OTel Maven Extension version in the docs
  docs/en/observability/ci-cd-observability.asciidoc
Labels: backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-7.17

#1677 Explore Data changes for UI and multi-series
  docs/en/observability/exploratory-data-visualizations.asciidoc
  docs/en/observability/images/exploratory-view-metrics.png
  docs/en/observability/images/exploratory-view-uptime.png
  docs/en/observability/images/exploratory-view-ux-page-load-time.png
  docs/en/observability/images/exploratory-view.png
  docs/en/observability/images/green-check.svg
  docs/en/observability/images/red-x.svg
  docs/en/observability/index.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: backport-8.1, backport-7.16, backport-8.0, backport-7.17

#1690 Add Fleet and Elastic Agent 8.1.1 relnotes
  docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, backport-8.1

#1671 Replace "index patterns" with `data-source` shared attribute
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/integrations/package-spec.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
Labels: v8.2.0, backport-8.1

#1704 Update create-cases.asciidoc
  docs/en/observability/create-cases.asciidoc
Labels: backport-skip

#1709 docs: log correlation is auto enabled
  docs/en/observability/monitor-java-app.asciidoc
Labels: v7.10.0, v7.11.0, v7.12.0, v7.13.0, Team:Docs, v7.14.0, v7.15.0, backport-8.1, backport-7.16, backport-8.0, backport-7.17

#1714 [7.15] docs: log correlation is auto enabled (#1709)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#1716 [7.13] docs: log correlation is auto enabled (#1709)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#1717 [7.12] docs: log correlation is auto enabled (#1709)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#1715 [7.14] docs: log correlation is auto enabled (#1709)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#1718 [7.11] docs: log correlation is auto enabled (#1709)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#1719 [7.10] docs: log correlation is auto enabled (#1709)
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport

#1693 Incorporate blog content into synthetic monitoring docs
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
Labels: Synthetics, backport-skip

#1688 Add docs on storing CI/CD build logs in Elastic
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/ci-cd-visualize-logs-kibana-and-jenkins-architecture.png
  docs/en/observability/images/ci-cd-visualize-logs-kibana-and-jenkins-console.png
  docs/en/observability/images/ci-cd-visualize-logs-kibana-architecture.png
  docs/en/observability/images/ci-cd-visualize-logs-kibana-console.png
Labels: backport-8.1

#1720 Update Synthetics Integration with new UI options
  docs/en/observability/images/synthetics-integration-source-type.png
  docs/en/observability/images/synthetics-integration-throttling.png
  docs/en/observability/images/synthetics-integration.png
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
Labels: backport-8.1

#1723 Replace alert workflow status filter with status filter
  docs/en/observability/images/alerts-page.png
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport-8.1, backport-8.0

#1515 Document loading inputs configuration from external files in standalone mode
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
Labels: backport-8.1, backport-8.2

#1733 Update .mergify.yml
  .mergify.yml
Labels: backport-skip

#1737 Add Fleet/Agent release notes for 7.17.2
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: v7.17.2

#1738 Add Fleet/Agent release notes for 8.1.2
  docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
Labels: backport-8.1, backport-8.2, v8.1.2
