Repository elastic/observability-docs, pull requests merged in 2022-08, with the labels that each got.

#2055 Add known issue and workaround for enroll command failing on deb/rpm
  docs/en/ingest-management/release-notes/release-notes-8.3.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, backport-8.3, backport-8.4, v8.3.3

#2053 Clarify that at least one fileset must be enabled in a filebeat module
  docs/en/observability/ingest-logs.asciidoc
Labels: backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-8.4

#2059 Explain why the edit hosts button in Fleet may be grayed out
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: Team:Fleet, v8.4.0, backport-8.4

#2076 Fix typo in attribute reference
  docs/en/ingest-management/overview.asciidoc
Labels: Team:Docs, backport-8.3, backport-8.4

#2064 Add docs about managing agent tags
  docs/en/ingest-management/fleet/filter-agent-list-by-tags.asciidoc
  docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
  docs/en/ingest-management/fleet/fleet.asciidoc
  docs/en/ingest-management/images/add-remove-tags.png
Labels: Team:Fleet, v8.4.0, backport-8.4

#2052 Hide topic about package signatures
  docs/en/ingest-management/integrations/package-signatures.asciidoc
Labels: backport-8.4

#2077 [DOCS] Add notes about security for ML anomaly detection job
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
Labels: docs, 8.3-candidate, backport-8.3, 7.17-candidate, backport-7.17, v8.5.0, v8.4.0, backport-8.4

#2062 Add topic about reinstalling integration assets
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/uninstall-integration.asciidoc
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
  docs/en/ingest-management/redirects.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: Team:Fleet, v8.4.0, backport-8.4

#2083 [DOCS] Add Webhook Case Management connector to Cases
  docs/en/observability/create-observability-connectors.asciidoc
Labels: v8.5.0, v8.4.0, backport-8.4

#2082 Update alerts, cases, and rules screenshots
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/alerts-overview.png
  docs/en/observability/images/alerts-page.png
  docs/en/observability/images/create-alerts-manage-rules.png
  docs/en/observability/images/create-alerts-rules-details.png
  docs/en/observability/images/view-alert-details.png
Labels: v8.4.0, backport-8.4

#2089 Update list of Action types on Alerts
  docs/en/observability/images/alert-action-types.png
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
Labels: v8.4.0, backport-8.4

#2096 Update commands.asciidoc (#2093)
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.4

#2078 Add docs about setting agent binary download location
  docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.yml
  docs/en/ingest-management/fleet/air-gapped.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: Team:Fleet, v8.4.0, backport-8.4

#2060 Remove beta admonition for Logstash output in Fleet
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/security/logstash-certificates.asciidoc
Labels: Team:Fleet, v8.4.0, backport-8.4

#2101 Fix numbering issue caused by linter comment
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Labels: backport-8.3, backport-8.2, backport-8.4

#2075 [synthetics] Add docs on private locations
  docs/en/observability/images/private-locations-monitor-locations.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-configure-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-conf-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-conf-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-connect-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-connect-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-docker-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-docker-widget.asciidoc
  docs/en/observability/uptime-set-up-app.asciidoc
  docs/en/observability/uptime-set-up-heartbeat.asciidoc
  docs/en/observability/uptime-set-up.asciidoc
Labels: v8.4.0, backport-8.4

#1944 [Synthetics] Document changing retention on a per-data-stream basis
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-manage-retention.asciidoc
Labels: Team:Uptime, backport-8.3, backport-8.4

#2114 [synthetics] Standardize beta notes across synthetics docs
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-journeys.asciidoc
  docs/en/observability/synthetics-manage-monitors.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
  docs/en/observability/synthetics-run-test.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
Labels: backport-8.3, backport-8.4

#2094 Custom ingest pipelines
  docs/en/ingest-management/data-streams.asciidoc
Labels: v8.4.0, backport-8.4

#2071 [synthetics] Document the `request` parameter
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
Labels: v8.4.0, backport-8.4

#2105 Add Fleet and Elastic Agent 8.4 release notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.4.asciidoc
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, v8.4.0, backport-8.4

#2124 Add Fleet and Elastic Agent 7.17.6 release notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: Team:Fleet, Team:Elastic-Agent-Data-Plane, v7.17.6

#2102 Change "Metrics" to "Infrastructure"
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/configure-metrics-sources.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/exploratory-data-visualizations.asciidoc
  docs/en/observability/explore-metrics.asciidoc
  docs/en/observability/fields-reference.asciidoc
  docs/en/observability/images/metrics-summary.png
  docs/en/observability/index.asciidoc
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/inspect-metric-anomalies.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-aws-services.asciidoc
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/monitor-azure.asciidoc
  docs/en/observability/monitor-docker-containers.asciidoc
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/monitor-kubernetes-pods.asciidoc
  docs/en/observability/monitor-servers.asciidoc
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
  docs/en/observability/view-observability-alerts.asciidoc
Labels: v8.4.0, backport-8.4

#2128 Fix broken link to Data Stream ILM tutorial
  docs/en/observability/synthetics-manage-retention.asciidoc
Labels: Team:Docs, backport-skip

#2130 Fix broken link to data streams ILM tutorial
  docs/en/observability/synthetics-manage-retention.asciidoc
Labels: Team:Docs, v8.4.0

#2131 Consistently use attributes for links to other books
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/observability/ingest-splunk.asciidoc
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/synthetics-manage-retention.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
  docs/en/observability/uptime-set-up-heartbeat.asciidoc
Labels: backport-8.3, backport-8.1, backport-7.16, backport-8.2, backport-8.0, backport-7.17, backport-8.4

#2139 [7.15] [7.16] Consistently use attributes for links to other books (backport #2131) (#2137)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/observability/ingest-splunk.asciidoc
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
Labels: backport

#2140 [7.14] [7.16] Consistently use attributes for links to other books (backport #2131) (#2137)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/observability/ingest-splunk.asciidoc
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/monitor-aws.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
Labels: backport

#2142 [7.12] [7.16] Consistently use attributes for links to other books (backport #2131) (#2137)
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/monitor-aws.asciidoc
Labels: backport

#2141 [7.13] [7.16] Consistently use attributes for links to other books (backport #2131) (#2137)
  docs/en/observability/ingest-splunk.asciidoc
  docs/en/observability/logs-app-fields.asciidoc
  docs/en/observability/metrics-app-fields.asciidoc
  docs/en/observability/monitor-aws.asciidoc
Labels: backport

#2119 Update link to future package spec
  docs/en/integrations/index.asciidoc
Labels: backport-skip

#2148 [synthetics] Add note on required privileges for enabling monitor management
  docs/en/observability/uptime-set-up-app.asciidoc
Labels: backport-8.4

#2150 Add Fleet and Elastic Agent 8.4.1 release notes
  docs/en/ingest-management/release-notes/release-notes-8.4.asciidoc
Labels: Team:Fleet, Team:Elastic-Agent-Data-Plane, backport-8.4
