Repository elastic/observability-docs, pull requests merged in 2022-04, with the labels that each got.

#1748 [Backport] [8.0] [1741] add minimal agent install docs
  docs/en/ingest-management/elastic-agent/install-fleet-managed-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1742 Update CI/CD diagrams
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/advanced-arch-observability.png
  docs/en/observability/images/ci-cd-visualize-logs-kibana-and-jenkins-architecture.png
  docs/en/observability/images/ci-cd-visualize-logs-kibana-architecture.png
  docs/en/observability/images/simple-arch-observability.png
Labels: backport-8.1, backport-8.2

#1751 Add information about alert details flyover
  docs/en/observability/images/view-alert-details.png
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport-8.1, backport-8.2

#1724 Re-add Customise integration data retention documentation
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/images/create-component-template.png
  docs/en/ingest-management/images/create-index-template.png
  docs/en/ingest-management/images/data-stream-info.png
Labels: backport-8.2

#1734 Add screenshots and text for all Advanced browser options
  docs/en/observability/images/synthetics-integration-agent-options.png
  docs/en/observability/images/synthetics-integration-selective-tests.png
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
Labels: backport-8.1, backport-8.2

#1757 Fix Elastic Agent start/stop commands on win
  docs/en/ingest-management/tab-widgets/start.asciidoc
  docs/en/ingest-management/tab-widgets/stop.asciidoc
Labels: backport-8.1, backport-7.16, backport-8.2, backport-8.0, backport-7.17

#1750 Update path to Elastic Agent repo in docs
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
Labels: v8.2.0, backport-8.2

#1770 Make http json input green in support table
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-8.1, backport-8.2, backport-8.0, backport-7.17

#1736 Add screenshots and text for inline script source type
  docs/en/observability/images/synthetics-integration-inline-script.png
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
Labels: backport-8.1, backport-8.2

#1780 Add known problem with agent binary verification
  docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.2

#1758 [Fleet] Do not recommand user to run Fleet server in http
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: Team:Fleet, v8.2.0, backport-skip

#1779 Add info about the dedicated Observability Rules page
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/create-alerts-manage-rules.png
Labels: v8.2.0, backport-8.2

#1783 Remove locally defined `release-state` variable
  docs/en/observability/ingest-logs.asciidoc
Labels: backport-8.2

#1769 Document the inspector panel for APM, Uptime, and User experience
  docs/en/observability/images/inspect-enable.png
  docs/en/observability/images/inspect-flyout-dropdown.png
  docs/en/observability/images/inspect-flyout-request.png
  docs/en/observability/images/inspect-flyout-response.png
  docs/en/observability/images/inspect-flyout-statistics.png
  docs/en/observability/images/inspect-flyout.png
  docs/en/observability/index.asciidoc
  docs/en/observability/inspect.asciidoc
  docs/en/observability/troubleshooting.asciidoc
Labels: backport-8.2

#1785 Adds Elastic Agent and Fleet 8.1.3 release notes
  docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.1, 8.1.3

#1782 Add Elastic Agent and Fleet 7.17.3 release notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: 7.17.3

#1795 Add placeholder topic about generating certs for Logstash
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/generate-certificates.asciidoc
  docs/en/ingest-management/security/logstash-certificates.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: Team:Fleet, backport-8.2

#1794 Align "action variables" sections in rules pages
  docs/en/observability/images/advanced-variables.png
  docs/en/observability/images/basic-variables.png
  docs/en/observability/images/duration-anomaly-alert-default-message.png
  docs/en/observability/images/infrastructure-threshold-alert-default-message.png
  docs/en/observability/images/logs-threshold-alert-default-message.png
  docs/en/observability/images/metrics-threshold-alert-default-message.png
  docs/en/observability/images/monitor-status-alert-default-message.png
  docs/en/observability/images/tls-certificate-alert-default-message.png
  docs/en/observability/images/uptime-connector-duration.png
  docs/en/observability/images/uptime-connector-variables.png
  docs/en/observability/images/uptime-status-variables.png
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
Labels: backport-8.2

#1725 Update the structure of Synthetic monitoring section
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/observability/images/synthetics-integration-source-type.png
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/redirects.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-journeys.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/synthetics-run-test.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-inline-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-inline-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-conf-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-conf-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-connect-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-connect-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-docker-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/set-up-docker-widget.asciidoc
  docs/en/observability/uptime-analyze.asciidoc
  docs/en/observability/uptime-set-up.asciidoc
  docs/en/observability/view-infrastructure-metrics.asciidoc
  docs/en/observability/view-monitor-status.asciidoc
Labels: Synthetics, backport-8.1, backport-8.2

#1789 Add content on disabling writing to Observability alert indices
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport-8.1, backport-8.2

#1788 Change APM & Fleet to Integrations Server
  docs/en/ingest-management/fleet/add-fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
  docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Fleet, backport-8.1, backport-8.2

#1812 Add temporary redirect for Synthetics Agent/Fleet quickstart guide
  docs/en/observability/redirects.asciidoc
Labels: backport-8.1, backport-8.2, needs-writer-review

#1810 Add Fleet and Elastic Agent 8.2.0 relnotes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.2.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, backport-8.2

#1818 Spec fallback: use integration type by default
  docs/en/integrations/package-spec.asciidoc
Labels: backport-skip

#1807 Add docs about configuring SSL for the Logstash output
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/fleet/fleet.asciidoc
  docs/en/ingest-management/images/add-logstash-output.png
  docs/en/ingest-management/images/agent-output-settings.png
  docs/en/ingest-management/images/ca-certs.png
  docs/en/ingest-management/images/client-certs.png
  docs/en/ingest-management/images/logstash-certs.png
  docs/en/ingest-management/images/logstash-output-certs.png
  docs/en/ingest-management/security/logstash-certificates.asciidoc
Labels: Team:Fleet, v8.2.0, backport-8.2

#1815 Document per-policy outputs in Fleet
  docs/en/ingest-management/agent-policies.asciidoc
Labels: v8.2.0, backport-8.2

#1826 Add temporary redirect for former intro to Synthetics/browser monitors page
  docs/en/observability/redirects.asciidoc
Labels: backport-8.1, backport-8.2

#1824 Updates docs about adding agents
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/images/kibana-agent-flyout.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/tab-widgets/prereq.asciidoc
  docs/en/observability/images/add-synthetics-integration.png
  docs/en/observability/images/host-metrics2.png
  docs/en/observability/images/kibana-agent-add-log-path.png
  docs/en/observability/images/kibana-agent-confirm-data.png
  docs/en/observability/images/kibana-agent-flyout.png
  docs/en/observability/images/kibana-agent-system-integration-visualizations.png
  docs/en/observability/images/kibana-fleet-agents.png
  docs/en/observability/images/kibana-fleet-policies-default-with-nginx.png
  docs/en/observability/images/kibana-fleet-policies-default-with-synthetics.png
  docs/en/observability/images/kibana-home.png
  docs/en/observability/images/kibana-system-policy.png
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
Labels: v8.2.0, backport-8.2
