Repository elastic/observability-docs, pull requests merged in 2022-07, with the labels that each got.

#1977 Clarify Elastic Agent description to include remote services and hardware
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
  docs/en/ingest-management/images/agent-architecture.png
  docs/en/ingest-management/overview.asciidoc
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-traces.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-8.3, v8.3.1

#1966 Update "Endpoint Security" integration references to "Endpoint and Cloud Security"
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/debug-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/tab-widgets/remove-endpoint-files/content.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
  docs/en/observability/deploy-agent-to-send-data.asciidoc
  docs/en/observability/uptime-set-up.asciidoc
Labels: v8.3.0, backport-8.3

#1987 Indicate when there are no bug fixes for Agent or Fleet
  docs/en/ingest-management/release-notes/release-notes-8.3.asciidoc
Labels: Team:Docs, backport-8.3

#1990 Fix breaking link to the CICD Observability dashboards
  docs/en/observability/ci-cd-observability.asciidoc
Labels: backport-8.3, backport-8.2

#1971 Document some Fleet Server timeout configs
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-8.3

#2004 Update docs for step-based workflow
  docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
Labels: Team:Docs, Team:Fleet, backport-8.3, v8.3.2

#1976 Fix wrong config in elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
Labels: backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-7.17

#2007 [synthetics] Move Heartbeat tab to first position in all synthetics docs
  docs/en/observability/synthetics-run-test.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-delete-monitor-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-delete-monitor-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-monitor-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-monitor-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-test-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-test-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-configure-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-configure-widget.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-content.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-widget.asciidoc
Labels: backport-8.3

#1983 Remove old FAQ description about secure communications
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-8.3

#2023 [8.2] Remove old FAQ description about secure communications
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport

#2022 [8.1] Remove old FAQ description about secure communications
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport

#2021 [8.0] Remove old FAQ description about secure communications
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport

#2020 [7.17] Remove old FAQ description about secure communications
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport

#2027 [DOCS] Add deletion sub-feature privilege for cases
  docs/en/observability/grant-cases-access.asciidoc
  docs/en/observability/images/cases-privileges.png
  docs/en/observability/images/cases-privledges.png
Labels: backport-skip, v8.4.0

#2024 Add placeholder for topic about integration package signatures
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/package-signatures.asciidoc
Labels: backport-skip, v8.4.0

#1953 [synthetics] Document the new Synthetics Recorder
  docs/en/observability/images/synthetics-create-test-script-recorder.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-journeys.asciidoc
  docs/en/observability/synthetics-recorder.asciidoc
Labels: backport-8.3

#2028 Clean up old TODO items in source files for Fleet/Agent docs
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/elastic-agent-logging.asciidoc
  docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
  docs/en/ingest-management/fleet/fleet-server-deployment-models.asciidoc
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
  docs/en/ingest-management/security/logstash-certificates.asciidoc
  docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Docs, backport-8.3

#2026 Add Fleet/Agent 8.3.3 release notes
  docs/en/ingest-management/release-notes/release-notes-8.3.asciidoc
Labels: Team:Docs, Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-8.3

#2034 backport: Add 8.4 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#2000 Improve organization and flow of Fleet/Agent docs
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/security/generate-certificates.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, backport-8.3

#2030 Add subsection for custom CA in air-gapped environments
  docs/en/ingest-management/fleet/air-gapped.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Ecosystem, backport-8.3, backport-7.17, backport-8.4

#2031 Update APM Node.js setup steps and links.
  docs/en/shared/install-apm-agents-kube/nodejs.asciidoc
  docs/en/shared/install-apm-agents/content.asciidoc
Labels: backport-8.3, backport-8.4
