Repository elastic/observability-docs, pull requests merged in 2022-01, with the labels that each got.

#1409 Add deprecation notices for username/passwords for env vars
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, backport-7.16

#1421 Fix example command to show one module instead of multiple
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
Labels: v8.0.0, v7.16.0, backport-7.16, backport-8.0, v7.17.0, backport-7.17

#1407 Add topic about setting enrollment timeout for Fleet-managed agents
  docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
  docs/en/ingest-management/fleet/fleet.asciidoc
  docs/en/ingest-management/fleet/set-elastic-agent-enrollment-timeout.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: v8.0.0, v7.16.0, backport-7.16, backport-8.0, backport-7.17

#1423 Remove username/password from elastic-agent
  docs/en/ingest-management/elastic-agent/configuration/env/.container-envs.asciidoc.swp
  docs/en/ingest-management/elastic-agent/configuration/env/.shared-env.asciidoc.swp
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, backport-8.0

#1422 Add workaround for Fleet Server integration policy upgrade problem
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: v7.16.0, backport-7.16, backport-8.0, backport-7.17

#1383 Add documentation for the elastic agent "status" command
  docs/en/ingest-management/commands.asciidoc
Labels: backport-7.16, backport-8.0, backport-7.17

#1442 [Fleet] Fix troubleshouting agent stuck in update to avoid ghost package policy
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Fleet, backport-skip

#1441 Added missing --fleet-server-insecure-http to docs
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Labels: 7.16-candidate, 8.0-candidate, 8.1-candidate, backport-7.16, backport-8.0, 7.17-candidate, backport-7.17

#1434 Update deprecation tags for basic auth env vars for agent
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, backport-7.16

#1452 [backport] Update deprecation tags for basic auth env vars for agent (#1434)
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: docs, backport, Team:Elastic-Agent-Control-Plane

#1455 Add placeholder for Fleet/Agent 8.0.0 relnotes
  docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
Labels: v8.0.0, backport-8.0

#1443 Clarify licensing requirements for bulk agent upgrades
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
Labels: v8.0.0, Team:Fleet, v7.16.0, backport-7.16, backport-8.0, v7.17.0, backport-7.17

#1451 elastic-agent remove deprecation notice
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-8.0

#1450 Add relnotes for 7.16.3 and missing patch releases
  docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, backport-7.16

#1454 Remove stale list of integrations from the Fleet/Agent docs
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: v8.0.0, Team:Elastic-Agent, v7.16.0, v7.15.0, backport-7.16, backport-8.0, v7.17.0, backport-7.17

#1463 Add ca_trusted_fingerprint documentation to standalone agent docs
  docs/en/ingest-management/elastic-agent/configuration/authentication/ssl-shared-settings.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/observability/images/add-fleet-server.png
Labels: docs, Team:Elastic-Agent-Control-Plane, backport-8.1, backport-8.0

#1461 Create new entry to synthetics commands docs page for `--playwright-options`
  docs/en/observability/synthetics-command-reference.asciidoc
Labels: Team:Uptime, backport-8.0

#1475 Add KIBANA_USERNAME/KIBANA_PASSWORD to agent container docs
  docs/en/ingest-management/elastic-agent/configuration/env/.shared-env.asciidoc.swp
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, backport-8.0

#1476 agent kibana env vars update deprecation notices
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: docs, Team:Elastic-Agent-Control-Plane, backport-7.16

#1484 [backport] Update deprecation notices (#1476)
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: backport

#1502 Update beats-agent-comparison.asciidoc
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-7.16, backport-8.0, backport-7.17
