Repository elastic/observability-docs, pull requests merged in 2022-05, with the labels that each got.

#1811 Update Observability overview page for 8.2
  docs/en/observability/images/alerts-overview.png
  docs/en/observability/images/apm.png
  docs/en/observability/images/log-rate.png
  docs/en/observability/images/metrics-summary.png
  docs/en/observability/images/obs-overview-ue.png
  docs/en/observability/images/uptime-summary.png
  docs/en/observability/observability-ui.asciidoc
Labels: v8.2.0, backport-8.2, needs-writer-review

#1833 Remove old images
  docs/en/ingest-management/images/add-agent.png
  docs/en/observability/images/host-metrics.png
  docs/en/observability/images/kibana-fleet-datastreams.png
  docs/en/observability/images/kibana-fleet-integrations-nginx-overview.png
  docs/en/observability/images/kibana-fleet-integrations-nginx.png
  docs/en/observability/images/kibana-fleet-integrations-synthetics-overview.png
  docs/en/observability/images/kibana-fleet-integrations-synthetics.png
Labels: techdebt, v8.2.0, backport-8.2

#1841 Update beats-agent-comparison.asciidoc
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: Team:Elastic-Agent, v8.2.0, backport-8.2

#1834 Update APM quick start with new Add agent steps
  docs/en/observability/ingest-traces.asciidoc
Labels: v8.2.0, backport-8.2

#1829 extend doc for providers.kubernetes_leaderelection
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc
Labels: backport-8.3, backport-8.2

#1852 Change module references to integrations in Logs and Metrics intros
  docs/en/observability/analyze-metrics.asciidoc
  docs/en/observability/monitor-logs.asciidoc
Labels: backport-8.2, needs-writer-review

#1849 Fix log file names in 7.17 docs
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: v7.17.2

#1867 Lint all docs for for repeated words
  docs/en/ingest-management/migrate-beats-to-agent.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
Labels: backport-8.2

#1863 Update screenshots
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/fleet/images/elastic-cloud-agent-policy.png
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/images/agent-status-filter.png
  docs/en/ingest-management/images/apply-agent-policy.png
  docs/en/ingest-management/images/assign-policy.png
  docs/en/ingest-management/images/create-agent-policy.png
  docs/en/ingest-management/images/create-token.png
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/kibana-fleet-start.png
  docs/en/ingest-management/images/revoke-token.png
  docs/en/ingest-management/images/show-token.png
  docs/en/ingest-management/images/upgrade-agents.png
  docs/en/ingest-management/images/upgrade-integration-policies-automatically.png
  docs/en/ingest-management/images/upgrade-integration.png
  docs/en/ingest-management/images/upgrade-package-policy.png
  docs/en/ingest-management/images/upgrade-policy-editor.png
  docs/en/ingest-management/images/upgrade-resolve-conflicts.png
  docs/en/ingest-management/images/upgrade-view-previous-config.png
  docs/en/ingest-management/images/view-agent-logs.png
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
Labels: Team:Fleet, v8.2.0, backport-8.2

#1855 Mention that Fleet Server must be running before configuring Fleet Settings
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: Team:Fleet, backport-8.1, backport-8.2, backport-8.0, backport-7.17

#1880 [DOCS] Refresh cases screenshot
  docs/en/observability/images/cases.png
Labels: v8.3.0, backport-skip

#1882 docs: Update ingest traces
  .gitignore
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/tab-widgets/add-apm-integration/content.asciidoc
  docs/en/observability/tab-widgets/add-apm-integration/images/add-integration-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/apm-agent-policy-1.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-add-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-agent-policy.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-apm-policy-view.png
  docs/en/observability/tab-widgets/add-apm-integration/images/cloud-edit-apm.png
  docs/en/observability/tab-widgets/add-apm-integration/images/kibana-fleet-integrations-apm-overview.png
  docs/en/observability/tab-widgets/add-apm-integration/images/kibana-fleet-policies-default-with-apm.png
Labels: Team:Docs, backport-8.2

#1787 Add GitHub Actions
  .github/workflows/add-issue-to-project.yml
  .github/workflows/add-pr-to-project.yml
Labels: backport-skip

#1888 Fix GitHub action
  .github/workflows/add-issue-to-project.yml
  .github/workflows/add-pr-to-project.yml
Labels: backport-skip, needs-writer-review

#1885 Add Fleet and Elastic Agent 8.2.1 release notes
  docs/en/ingest-management/release-notes/release-notes-8.2.asciidoc
Labels: backport-8.2, v8.2.1

#1893 use `pull_request_target`
  .github/workflows/add-pr-to-project.yml
Labels: backport-skip, needs-writer-review

#1894 Remove add label step
  .github/workflows/add-pr-to-project.yml
Labels: backport-skip

#1895 Add board automation for other teams
  .github/workflows/add-pr-to-project.yml
  .github/workflows/add-to-dev-projects.yml
Labels: backport-skip

#1896 Update .backportrc.json
  .backportrc.json
Labels: backport-skip

#1897 Add Fleet and Elastic Agent 8.2.2 release notes
  docs/en/ingest-management/release-notes/release-notes-8.2.asciidoc
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-8.2, v8.2.2

#1903 Enable backports to 8.3 via label
  .mergify.yml
Labels: backport-skip
