Repository elastic/observability-docs, pull requests merged in 2022-09, with the labels that each got.

#2152 [synthetics] Add Heartbeat and Uptime app diagrams
  docs/en/observability/images/uptime-set-up-app.png
  docs/en/observability/images/uptime-set-up-heartbeat.png
  docs/en/observability/uptime-set-up-app.asciidoc
  docs/en/observability/uptime-set-up-heartbeat.asciidoc
  docs/en/observability/uptime-set-up.asciidoc
Labels: backport-8.4

#2161 [DOCS] Add "attributes" to display {version}
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: docs, v8.5.0, backport-8.4, v8.4.1

#2171 Update fleet-server-scaling.asciidoc (#2158)
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Labels: backport-skip

#2170 Fix Playwright link
  docs/en/observability/synthetics-configuration.asciidoc
Labels: backport-8.3, backport-8.4

#2146 [synthetics] Add notes about API keys for private locations
  docs/en/observability/images/synthetics-monitor-management-api-key.png
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-content.asciidoc
  docs/en/observability/uptime-set-up-app.asciidoc
Labels: backport-8.4

#2163 Add missing binary download
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: Team:Fleet, backport-8.4

#2106 Add AWS tutorial that shows Elastic Agent
  docs/en/observability/images/agent-tut-aws-credentials.png
  docs/en/observability/images/agent-tut-billing-dashboard.png
  docs/en/observability/images/agent-tut-collect-billing-metrics.png
  docs/en/observability/images/agent-tut-collect-ec2-metrics.png
  docs/en/observability/images/agent-tut-config-vpc-logs.png
  docs/en/observability/images/agent-tut-configure-event-notification.png
  docs/en/observability/images/agent-tut-configure-notification-output.png
  docs/en/observability/images/agent-tut-create-s3-bucket.png
  docs/en/observability/images/agent-tut-creating-a-queue.png
  docs/en/observability/images/agent-tut-ec2-metrics-discover.png
  docs/en/observability/images/agent-tut-ec2-overview-dashboard.png
  docs/en/observability/images/agent-tut-enable-server-access-logging.png
  docs/en/observability/images/agent-tut-one-bucket-archi.png
  docs/en/observability/images/agent-tut-s3access-logs.png
  docs/en/observability/images/agent-tut-s3accesslog-dashboard.png
  docs/en/observability/images/agent-tut-two-buckets-archi.png
  docs/en/observability/images/agent-tut-vpcflowlog-dashboard.png
  docs/en/observability/monitor-aws-agent.asciidoc
  docs/en/observability/monitor-aws-beats.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport-8.4

#2182 Add hints based autodiscover part
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
Labels: backport-skip, Team:Cloudnative-Monitoring, v8.5.0, 8.5-candidate

#2184 [Synthetics] Add cap requirement to docker section
  docs/en/observability/synthetics-quickstart.asciidoc
Labels: docs, Team:Uptime

#2185 Add Fleet and Elastic Agent 8.4.2 release notes
  docs/en/ingest-management/release-notes/release-notes-8.4.asciidoc
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-8.4

#2100 Add non-interactive flag to syntax example
  docs/en/ingest-management/commands.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-8.3, backport-8.4, backport-8.5

#2189 backport: Add 8.5 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#2199 Update install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
Labels: v8.3.3

#2200 Update ingest-logs-metrics-uptime.asciidoc
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
Labels: v8.3.3

#2188 Docfix uptime-set-up-heartbeat.asciidoc
  docs/en/observability/uptime-set-up-heartbeat.asciidoc
Labels: backport-8.4, backport-8.5

#2201 Adds Fleet/Agent 8.4.3 release notes
  docs/en/ingest-management/release-notes/release-notes-8.4.asciidoc
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-8.4, backport-8.5
