Repository elastic/observability-docs, pull requests merged in 2023-03, with the labels that each got.

#2715 Add generated Fleet API docs
  docs/en/ingest-management/fleet/api-generated/README.md
  docs/en/ingest-management/fleet/api-generated/rules/.openapi-generator-ignore
  docs/en/ingest-management/fleet/api-generated/rules/.openapi-generator/FILES
  docs/en/ingest-management/fleet/api-generated/rules/.openapi-generator/VERSION
  docs/en/ingest-management/fleet/api-generated/rules/fleet-apis-passthru.asciidoc
  docs/en/ingest-management/fleet/api-generated/rules/fleet-apis.asciidoc
  docs/en/ingest-management/fleet/api-generated/template/index.mustache
  docs/en/ingest-management/fleet/apis.asciidoc
  docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-skip

#2726 Add known issue entry for elastic-agent#2343
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-8.6

#2728 Add release note for fleet-server#2303
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: Team:Fleet, backport-8.6

#2746 Add post-processing step to tidy up API docs section headers
  docs/en/ingest-management/fleet/api-generated/README.md
  docs/en/ingest-management/fleet/api-generated/rules/fleet-apis-passthru.asciidoc
Labels: backport-skip

#2734 Clarify limitations around using field names in agent processor configs
  docs/en/ingest-management/processors/processor-add_cloud_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_cloudfoundry_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_docker_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_fields.asciidoc
  docs/en/ingest-management/processors/processor-add_host_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_id.asciidoc
  docs/en/ingest-management/processors/processor-add_kubernetes_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_labels.asciidoc
  docs/en/ingest-management/processors/processor-add_locale.asciidoc
  docs/en/ingest-management/processors/processor-add_network_direction.asciidoc
  docs/en/ingest-management/processors/processor-add_nomad_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_observer_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_process_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_tags.asciidoc
  docs/en/ingest-management/processors/processor-communityid.asciidoc
  docs/en/ingest-management/processors/processor-convert.asciidoc
  docs/en/ingest-management/processors/processor-copy_fields.asciidoc
  docs/en/ingest-management/processors/processor-decode_base64_field.asciidoc
  docs/en/ingest-management/processors/processor-decode_cef.asciidoc
  docs/en/ingest-management/processors/processor-decode_csv_fields.asciidoc
  docs/en/ingest-management/processors/processor-decode_json_fields.asciidoc
  docs/en/ingest-management/processors/processor-decode_xml.asciidoc
  docs/en/ingest-management/processors/processor-decode_xml_wineventlog.asciidoc
  docs/en/ingest-management/processors/processor-decompress_gzip_field.asciidoc
  docs/en/ingest-management/processors/processor-detect_mime_type.asciidoc
  docs/en/ingest-management/processors/processor-dissect.asciidoc
  docs/en/ingest-management/processors/processor-dns.asciidoc
  docs/en/ingest-management/processors/processor-drop_event.asciidoc
  docs/en/ingest-management/processors/processor-drop_fields.asciidoc
  docs/en/ingest-management/processors/processor-extract_array.asciidoc
  docs/en/ingest-management/processors/processor-fingerprint.asciidoc
  docs/en/ingest-management/processors/processor-include_fields.asciidoc
  docs/en/ingest-management/processors/processor-parse_aws_vpc_flow_log.asciidoc
  docs/en/ingest-management/processors/processor-rate_limit.asciidoc
  docs/en/ingest-management/processors/processor-registered_domain.asciidoc
  docs/en/ingest-management/processors/processor-rename.asciidoc
  docs/en/ingest-management/processors/processor-replace.asciidoc
  docs/en/ingest-management/processors/processor-script.asciidoc
  docs/en/ingest-management/processors/processor-syslog.asciidoc
  docs/en/ingest-management/processors/processor-timestamp.asciidoc
  docs/en/ingest-management/processors/processor-translate_sid.asciidoc
  docs/en/ingest-management/processors/processor-truncate_fields.asciidoc
  docs/en/ingest-management/processors/processor-urldecode.asciidoc
  docs/en/ingest-management/processors/processors.asciidoc
Labels: Team:Docs, backport-8.6, backport-8.7

#2747 Add inactivity timeout documentation
  docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/set-inactivity-timeout.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.7

#2760 [main] Fixing content bug in step 3 notice box (#2757)
  docs/en/observability/ingest-traces.asciidoc
Labels: backport, backport-8.7

#2759 Add footnote for log file beats shipper install layout
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: Team:Docs, backport-8.3, backport-8.1, backport-8.2, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2763 [DOCS] Refresh monitor status rule screenshots
  docs/en/observability/images/monitor-status-alert-default-message.png
  docs/en/observability/images/monitor-status-alert-recovery.png
  docs/en/observability/images/monitor-status-alert.png
  docs/en/observability/images/uptime-alert-connectors.png
  docs/en/observability/images/uptime-run-when-selection.png
  docs/en/observability/monitor-status-alert.asciidoc
Labels: docs, v8.7.0, v8.8.0, backport-8.7

#2764 [DOCS] Refresh screenshots for TLS certificate rule
  docs/en/observability/images/tls-alert.png
  docs/en/observability/images/tls-certificate-alert-default-message.png
  docs/en/observability/images/tls-certificate-alert-recovery.png
  docs/en/observability/images/tls-run-when-selection.png
  docs/en/observability/uptime-tls-alert.asciidoc
Labels: docs, v8.7.0, v8.8.0, backport-8.7

#2765 [DOCS] Refresh infrastructure threshold rule screenshots
  docs/en/observability/images/infrastructure-threshold-alert-default-message.png
  docs/en/observability/images/infrastructure-threshold-run-when-selection.png
  docs/en/observability/images/inventory-alert.png
  docs/en/observability/images/metrics-threshold-run-when-selection.png
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: docs, v8.7.0, v8.8.0, backport-8.7

#2731 Enhance service correlation doc
  docs/en/observability/application-logs.asciidoc
  docs/en/observability/tab-widgets/filebeat-logs/content.asciidoc
  docs/en/shared/install-apm-agents/content.asciidoc
Labels: backport-8.7

#2732 [Synthetics] Suggest not to use browser types in 7x
  docs/en/observability/monitor-uptime-synthetics.asciidoc
  docs/en/observability/monitor-uptime.asciidoc
  docs/en/observability/shared/synthetics-note.asciidoc
  docs/en/observability/synthetic-monitoring.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
  docs/en/observability/synthetics-quickstart-fleet.asciidoc
  docs/en/observability/synthetics-quickstart.asciidoc
  docs/en/observability/synthetics-visualize.asciidoc
Labels: Synthetics

#2783 [synthetics] Use Synthetics with traffic filters
  docs/en/observability/images/synthetics-traffic-filters-create-filter.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-get-started-project.asciidoc
  docs/en/observability/synthetics-get-started-ui.asciidoc
  docs/en/observability/synthetics-traffic-filters.asciidoc
Labels: backport-8.7

#2785 Move profiling docs to the Observability docs
  docs/en/observability/images/profiling-apm-cluster-id.png
  docs/en/observability/images/profiling-cloud-id.png
  docs/en/observability/images/profiling-flamegraph-detailed-view.png
  docs/en/observability/images/profiling-flamegraph-differential-view.png
  docs/en/observability/images/profiling-flamegraph-view.png
  docs/en/observability/images/profiling-functions-default-view.png
  docs/en/observability/images/profiling-functions-differential-view.png
  docs/en/observability/images/profiling-k8s-hostagent.png
  docs/en/observability/images/profiling-restart-integrations-server.png
  docs/en/observability/images/profiling-setup-popup.png
  docs/en/observability/images/profiling-stacktraces-default-view.png
  docs/en/observability/images/profiling-stacktraces-show-more.png
  docs/en/observability/images/profiling-stacktraces-smaller-graphs.png
  docs/en/observability/images/profiling-stacktraces-unsymbolized.png
  docs/en/observability/index.asciidoc
  docs/en/observability/profiling-add-symbols.asciidoc
  docs/en/observability/profiling-advanced-configuration.asciidoc
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-tag-data-query.asciidoc
  docs/en/observability/profiling-troubleshooting.asciidoc
  docs/en/observability/profiling-upgrade.asciidoc
  docs/en/observability/profiling-use-a-proxy.asciidoc
  docs/en/observability/universal-profiling.asciidoc
Labels: backport-8.7

#2793 [DOCS] Add alert flapping and rule settings details
  docs/en/observability/images/create-alerts-manage-rules.png
  docs/en/observability/view-observability-alerts.asciidoc
Labels: docs, v8.7.0, v8.8.0, backport-8.7

#2790 Update alerting screenshots to include the AlertSummaryWidget
  docs/en/observability/images/alerts-overview.png
  docs/en/observability/images/alerts-page.png
  docs/en/observability/images/create-alerts-rules-details.png
Labels: backport-8.7

#2798 Update troubleshooting with file sharing tip for macOS
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.7

#2788 Add Fleet/Agent 8.7.0 release notes
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
Labels: Team:Docs, backport-8.7

#2786 Remove experimental banner on Fleet API docs page
  docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
Labels: backport-skip

#2792 [synthetics] Document that not all Playwright functionality is available in Synthetics
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport-8.7
