Repository elastic/observability-docs, pull requests merged in 2023-04, with the labels that each got.

#2820 Create a known issue for Elastic Agent
  docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
Labels: backport-8.7

#2814 Update elastic-agent diagnostic command files list
  docs/en/ingest-management/commands.asciidoc
Labels: backport-skip

#2729 [synthetics] Add lightweight monitor configuration options
  docs/en/observability/synthetics-lightweight.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/http.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/icmp.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/tcp.asciidoc
Labels: Synthetics, backport-8.7

#2823 Clarify behavior of copy fields processor
  docs/en/ingest-management/processors/processor-copy_fields.asciidoc
Labels: backport-7.17, backport-8.6, backport-8.7

#2752 [DOCS] Update queue statement in Elastic Agent
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: Team:Docs, backport-8.3, backport-8.1, backport-7.16, backport-8.2, backport-8.0, backport-7.17, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2804 Update docker provider documentation
  docs/en/ingest-management/elastic-agent/configuration/providers/docker-provider.asciidoc
Labels: Team:Cloudnative-Monitoring, backport-8.6, backport-8.7

#2817 Add Feature Flag page with new FQDN setting
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.7

#2811 Need to explicityly mention why agent is running as a super user
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport-skip

#2819 added ~ to ingest rate [universal-profiling.asciidoc]
  docs/en/observability/universal-profiling.asciidoc
Labels: backport-8.7

#2846 Add docs for Fleet UI FQDN setting
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport-8.7

#2822 Update documentation on Elastic Agent statuses
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/set-inactivity-timeout.asciidoc
  docs/en/ingest-management/images/agent-status-diagram.png
Labels: backport-8.7

#2848 Remove Elastic Serverless Forwarder source files from the obs guide (main branch only)
  docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder-configuration.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-serverless-transform.asciidoc
  docs/en/observability/aws-serverless-troubleshooting.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: Team:Docs, backport-skip

#2852 Revert "Remove Elastic Serverless Forwarder source files from the obs guide (main branch only)"
  docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder-configuration.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-serverless-transform.asciidoc
  docs/en/observability/aws-serverless-troubleshooting.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: backport-skip

#2860 Update metric fields
  docs/en/observability/monitor-infra/explore-metrics.asciidoc
  docs/en/observability/monitor-infra/monitor-servers.asciidoc
Labels: backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2857 Universal Profiling: add probabilistic profiling
  docs/en/observability/index.asciidoc
  docs/en/observability/profiling-advanced-configuration.asciidoc
  docs/en/observability/profiling-probabilistic-profiling.asciidoc
Labels: backport-skip, v8.8.0

#2866 Set expectations for the Synthetics Recorder
  docs/en/observability/synthetics-recorder.asciidoc
Labels: backport-8.3, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2867 Clarify when monitors run after creation
  docs/en/observability/synthetics-get-started-project.asciidoc
  docs/en/observability/synthetics-get-started-ui.asciidoc
Labels: backport-8.7

#2875 backport: Add 8.8 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#2869 Fix formatting and wording
  docs/en/observability/universal-profiling.asciidoc
Labels: backport-8.7, backport-8.8

#2856 Update CODEOWNERS
  .github/CODEOWNERS
Labels: backport-skip

#2853 Remove Elastic Serverless Forwarder source files from the obs guide (main branch only)
  docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder-configuration.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-serverless-transform.asciidoc
  docs/en/observability/aws-serverless-troubleshooting.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: backport-8.8

#2802 Amazon Kinesis Data Firehose input documentation
  docs/en/observability/aws-firehose-index.asciidoc
  docs/en/observability/aws-firehose/aws-firehose-setup.asciidoc
  docs/en/observability/aws-firehose/aws-firehose-troubleshooting.asciidoc
  docs/en/observability/aws-firehose/aws-firehose.asciidoc
  docs/en/observability/images/firehose-architecture.png
  docs/en/observability/images/firehose-config-1.png
  docs/en/observability/images/firehose-config-2.png
  docs/en/observability/images/firehose-config-3.png
  docs/en/observability/images/firehose-create-delivery-stream.png
  docs/en/observability/images/firehose-integration-data-stream.png
  docs/en/observability/images/firehose-integrations-install-assets.png
  docs/en/observability/images/firehose-integrations-page.png
  docs/en/observability/images/firehose-monitoring.png
Labels: backport-skip
