Repository elastic/observability-docs, pull requests merged in 2023-12, with the labels that each got.

#3397 update custom threshold redirect
  docs/en/observability/redirects.asciidoc
Labels: backport-8.10, backport-8.11

#3406 [Logs] Update data stream for streaming logs
  docs/en/observability/logs-stream.asciidoc
Labels: Area:Logs+, backport-8.10, backport-8.11

#3414 [mergify] Add 8.12 to `.mergify.yml`
  .mergify.yml
Labels: backport-skip

#3415 Point to `shared` files instead of Beats book
  docs/en/observability/logs-ecs-application.asciidoc
  docs/en/observability/logs-plaintext.asciidoc
Labels: backport-8.11, backport-8.12

#3448 [apm docs consolidation] Update `apm-server-root` references (main-8.10)
  docs/en/observability/traces-get-started.asciidoc
Labels: backport-8.10, backport-8.11, backport-8.12

#3425 [Logs] Add logs explorer docs
  docs/en/observability/explore-logs.asciidoc
  docs/en/observability/images/filter.png
  docs/en/observability/images/listAdd.png
  docs/en/observability/images/log-explorer.png
  docs/en/observability/images/log-menu.png
  docs/en/observability/images/minusInCircle.png
  docs/en/observability/images/plusInCircle.png
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-logs.asciidoc
Labels: backport-8.12

#3359 [Firehose] Add warning for upcoming default data stream change
  docs/en/aws-firehose/aws-firehose-setup.asciidoc
  docs/en/aws-firehose/aws-firehose.asciidoc
  docs/en/aws-firehose/images/aws-integrations-page.png
Labels: backport-skip

#3430 release: observability-docs automation
  .github/Makefile
  .github/workflows/run-minor-release.yml
Labels: backport-skip

#3496 [apm docs consolidation] Copy APM guide pages into Observability guide
  README.md
  docs/en/apm-server/anonymous-auth.asciidoc
  docs/en/apm-server/api-keys.asciidoc
  docs/en/apm-server/apm-distributed-tracing.asciidoc
  docs/en/apm-server/common-problems.asciidoc
  docs/en/apm-server/configure/outputs/elasticsearch.asciidoc
  docs/en/apm-server/configure/outputs/logstash.asciidoc
  docs/en/apm-server/configure/tls.asciidoc
  docs/en/apm-server/getting-started-apm-server.asciidoc
  docs/en/apm-server/integrations-index.asciidoc
  docs/en/apm-server/jaeger-integration.asciidoc
  docs/en/apm-server/manage-storage.asciidoc
  docs/en/apm-server/monitor-apm-server.asciidoc
  docs/en/apm-server/otel-metrics.asciidoc
  docs/en/apm-server/secret-token.asciidoc
  docs/en/apm-server/secure-comms.asciidoc
  docs/en/apm-server/setting-up-and-running.asciidoc
  docs/en/apm-server/shared-directory-layout.asciidoc
  docs/en/apm-server/shared-systemd.asciidoc
  docs/en/apm-server/ssl-input-settings.asciidoc
  docs/en/apm-server/tls-comms.asciidoc
  docs/en/apm-server/troubleshoot-apm.asciidoc
  docs/en/apm-server/upgrading-to-8.x.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/traces-get-started.asciidoc
Labels: backport-8.12
