Repository elastic/observability-docs, pull requests merged in 2023-10, with the labels that each got.

#3251 [DOCS] Rename Generative AI connector to OpenAI
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-skip, v8.11.0

#3255 backport: Add 8.11 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#3252 Remove uptime content from SLO alerting doc
  docs/en/observability/images/slo-action-frequency.png
  docs/en/observability/images/slo-action-variables.png
  docs/en/observability/slo-burn-rate-alert.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.10, backport-8.11

#3263 Change hosts to single string non-array
  docs/en/observability/synthetics-lightweight.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.10, backport-8.11

#3246 Create Filter and Aggregate log data section
  docs/en/observability/images/logs-kql-filter.png
  docs/en/observability/images/time-filter-icon.png
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-filter.asciidoc
  docs/en/observability/logs-overview.asciidoc
  docs/en/observability/logs-parse.asciidoc
  docs/en/observability/logs-stream.asciidoc
  docs/en/observability/logs-troubleshooting.asciidoc
Labels: backport-8.11

#3254 Profiling: improve known issues
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport, v8.10.0

#3286 [Logs] Update filter docs
  docs/en/observability/logs-filter.asciidoc
  docs/en/observability/logs-parse.asciidoc
Labels: backport-8.11

#3274 [DOCS] Refresh Case settings screenshots
  docs/en/observability/create-observability-connectors.asciidoc
  docs/en/observability/images/add-case-connector.png
  docs/en/observability/images/cases.png
Labels: backport-8.11

#3294 Clean up SLO and cases docs
  docs/en/observability/create-observability-connectors.asciidoc
  docs/en/observability/slo-create.asciidoc
Labels: backport-8.10, backport-8.11

#3297 [synthetics] Update docs to reflect the changes to `expect`
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport-8.11

#3298 Delete templates/ILM on profiling upgrade
  docs/en/observability/profiling-upgrade.asciidoc
Labels: Profiling, v8.12.0, backport-8.10, backport-8.11

#3293 [DOCS] Add custom fields to cases
  docs/en/observability/create-observability-connectors.asciidoc
  docs/en/observability/grant-cases-access.asciidoc
  docs/en/observability/images/cases-add-custom-field.png
  docs/en/observability/images/cases-custom-field-settings.png
  docs/en/observability/images/cases-settings.png
  docs/en/observability/manage-cases.asciidoc
Labels: v8.12.0, v8.11.0, backport-8.11

#3307 [Logs] Add serverless review updates
  docs/en/observability/images/logs-end-date.png
  docs/en/observability/images/logs-start-date.png
  docs/en/observability/logs-checklist.asciidoc
  docs/en/observability/logs-filter.asciidoc
  docs/en/observability/logs-parse.asciidoc
Labels: backport-8.11

#3311 Delete unused file
  docs/en/observability/ingest-traces.asciidoc
Labels: backport-8.11

#3262 Add note that the service is charged for
  docs/en/observability/synthetics-get-started-ui.asciidoc
  docs/en/observability/synthetics-migrate-integration.asciidoc
  docs/en/observability/synthetics-reference/global-managed-paid-for.asciidoc
  docs/en/observability/synthetics-support-matrix.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.10, backport-8.11

#3305 [Synthetics] Document how to disable Elastic managed locations
  docs/en/observability/images/synthetics-monitor-management-api-key.png
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-get-started-project.asciidoc
  docs/en/observability/synthetics-get-started-ui.asciidoc
  docs/en/observability/synthetics-role-read.asciidoc
  docs/en/observability/synthetics-role-write.asciidoc
  docs/en/observability/synthetics-roles.asciidoc
  docs/en/observability/synthetics-troubleshooting.asciidoc
Labels: backport-8.11

#3321 New issue templates and automation
  .github/ISSUE_TEMPLATE/8.10-request.yaml
  .github/ISSUE_TEMPLATE/8.11-request.yaml
  .github/ISSUE_TEMPLATE/community-request.yaml
  .github/ISSUE_TEMPLATE/elastic-request.yaml
  .github/ISSUE_TEMPLATE/other-request.yaml
  .github/advanced-issue-labeler.yml
  .github/workflows/add-issue-to-project.yml
  .github/workflows/issue-labeler.yml
Labels: backport-skip

#3322 Add info about "Untracked" alert status
  docs/en/observability/images/alerts-page.png
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport-8.11
