Repository elastic/observability-docs, pull requests merged in 2023-09, with the labels that each got.

#3157 Add onboarding troubleshooting
  docs/en/observability/logs-troubleshooting.asciidoc
Labels: backport-8.10

#3209 Update SLO role privileges
  docs/en/observability/images/slo-es-priv-all.png
  docs/en/observability/images/slo-es-priv-read.png
  docs/en/observability/slo-privileges.asciidoc
Labels: backport-8.10

#3208 Add custom metrics and histogram SLIs and partition by option
  docs/en/observability/slo-create.asciidoc
Labels: backport-8.10

#3214 Profiling: add upgrade notice of known issues for 8.9 versions
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport, backport-8.9, v8.9.0, backport-8.10

#3221 Small typo fix
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.10

#3226 Add typo fix to main (#3221)
  docs/en/observability/logs-stream.asciidoc
Labels: backport-skip

#3213 Explaining 'dotted lines' in metrics charts
  docs/en/observability/images/hosts-dashed-and-missing.png
  docs/en/observability/images/hosts-dashed.png
  docs/en/observability/images/hosts-missing-data.png
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
Labels: Team:Docs, backport-8.10

#3217 8.10 What’s new
  docs/en/observability/images/wn-ds.png
  docs/en/observability/images/wn-hosts.png
  docs/en/observability/images/wn-jvm.png
  docs/en/observability/images/wn-kql.png
  docs/en/observability/whats-new.asciidoc
Labels: docs

#3229 Flatten data stream in agent config
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.10

#3231 Update `/welcome-to-elastic` link in AWS firehose docs
  docs/en/aws-firehose/aws-firehose-troubleshooting.asciidoc
Labels: backport-skip

#2989 [Synthetics] Add advanced considerations doc
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-scale-and-architect.asciidoc
Labels: docs, backport-8.9, backport-8.10

#3234 Profiling 8.10 updates
  docs/en/observability/images/profiling-elastic-agent.png
  docs/en/observability/images/profiling-flamegraph-detailed-view.png
  docs/en/observability/images/profiling-flamegraph-differential-view.png
  docs/en/observability/images/profiling-flamegraph-view.png
  docs/en/observability/images/profiling-functions-default-view.png
  docs/en/observability/images/profiling-functions-differential-view.png
  docs/en/observability/images/profiling-setup-popup.png
  docs/en/observability/profiling-no-kernel-version-check.asciidoc
  docs/en/observability/profiling-probabilistic-profiling.asciidoc
  docs/en/observability/profiling-upgrade.asciidoc
  docs/en/observability/universal-profiling.asciidoc
Labels: backport-8.10

#3235 profiling: add edge case resolution in known issues
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-upgrade.asciidoc
Labels: backport, v8.10.0, backport-8.10

#3238 updated profiling version
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport-8.10

#3242 Fix the logs stream index template example
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9, backport-8.10

#3247 [Profiling] Improve docs on how to manage storage
  docs/en/observability/images/profiling-create-component-template.png
  docs/en/observability/index.asciidoc
  docs/en/observability/profiling-advanced-configuration.asciidoc
  docs/en/observability/profiling-index-lifecycle-management.asciidoc
  docs/en/observability/profiling-manage-storage.asciidoc
Labels: enhancement, backport-skip, Profiling, v8.11.0
