Repository elastic/observability-docs, pull requests merged in 2023-07, with the labels that each got.

#3044 Additional permission for creating Agent Policy
  docs/en/observability/synthetics-role-write.asciidoc
Labels: Synthetics, backport-8.9

#3046 [Profiling] Update name of filter fields
  docs/en/observability/profiling-tag-data-query.asciidoc
  docs/en/observability/universal-profiling.asciidoc
Labels: backport-8.9, v8.9.0

#3055 Update links for APM agents logs
  docs/en/observability/application-logs.asciidoc
Labels: backport-8.9, backport-8.8

#3065 [Profiling] Add new field to migration script
  docs/en/observability/profiling-upgrade-migrate.asciidoc
Labels: backport-8.9, v8.9.0

#3061 [DOCS] Add category field to cases
  docs/en/observability/images/cases.png
  docs/en/observability/manage-cases.asciidoc
Labels: backport-8.9, v8.9.0, v8.10.0

#3064 Universal profiling - update probabilistic profiling
  docs/en/observability/profiling-probabilistic-profiling.asciidoc
Labels: backport-8.9, backport-8.8

#3084 [Docs] Fix Table (was markdown)
  docs/en/integrations/system-testing.asciidoc
Labels: backport-skip

#3086 [synthetics] Add note about `--tags` and `--match` flags
  docs/en/observability/synthetics-command-reference.asciidoc
Labels: backport-8.9

#3073 [synthetics] Align CLI and config docs
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
Labels: backport-8.9

#3081 [synthetics] Add synthetics troubleshooting page
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-troubleshooting.asciidoc
  docs/en/observability/troubleshooting.asciidoc
Labels: backport-8.9

#3092 [DOCS] Refresh action-alert-summary.png
  docs/en/observability/images/action-alert-summary.png
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
Labels: backport-skip, v8.10.0

#3087 [synthetics] Update alerting docs
  docs/en/observability/images/synthetics-settings-disable-default-rules.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc
  docs/en/observability/synthetics-settings.asciidoc
Labels: backport-8.9

#3078 Add APM rules to list of rules
  docs/en/observability/create-alerts.asciidoc
Labels: backport-8.9

#3095 Update the profiling agent integration section
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport-8.9

#3101 Add conditional actions for observability alerts
  docs/en/observability/images/conditional-alerts.png
  docs/en/observability/images/logs-threshold-alert-default-message.png
  docs/en/observability/images/logs-threshold-conditional-alert.png
  docs/en/observability/images/metric-threshold-conditional-alerts.png
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: backport-8.9

#3058 Create Observability AI Assistant docs
  docs/en/observability/images/obs-ai-logs-prompts.png
  docs/en/observability/images/obs-ai-logs.gif
  docs/en/observability/images/obs-assistant.gif
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.9

#3083 Update host metrics docs and refactor files
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/images/add-custom-metric.png
  docs/en/observability/images/hosts.png
  docs/en/observability/images/kubernetes-filter.png
  docs/en/observability/images/metrics-app.png
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
  docs/en/observability/monitor-infra/analyze-metrics.asciidoc
  docs/en/observability/monitor-infra/aws-metrics.asciidoc
  docs/en/observability/monitor-infra/configure-metrics-sources.asciidoc
  docs/en/observability/monitor-infra/docker-container-metrics.asciidoc
  docs/en/observability/monitor-infra/explore-metrics.asciidoc
  docs/en/observability/monitor-infra/host-metrics.asciidoc
  docs/en/observability/monitor-infra/inspect-metric-anomalies.asciidoc
  docs/en/observability/monitor-infra/kubernetes-pod-metrics.asciidoc
  docs/en/observability/monitor-infra/metrics-reference.asciidoc
  docs/en/observability/monitor-infra/monitor-servers.asciidoc
  docs/en/observability/monitor-infra/view-infrastructure-metrics.asciidoc
Labels: backport-8.9, v8.9.0

#3108 Reverts #2995
  docs/en/observability/index.asciidoc
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-upgrade-fresh.asciidoc
  docs/en/observability/profiling-upgrade-migrate.asciidoc
  docs/en/observability/profiling-upgrade.asciidoc
Labels: backport-8.9, 8.9-candidate

#3074 Create a section on streaming and querying a log file
  docs/en/observability/images/add-custom-logs.png
  docs/en/observability/images/add-integrations.png
  docs/en/observability/images/custom-log-advanced-options.png
  docs/en/observability/images/standalone-link.png
  docs/en/observability/images/stream-logs-example.png
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-overview.asciidoc
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9
