Repository elastic/observability-docs, pull requests merged in 2023-06, with the labels that each got.

#2992 Remove Beats dependency
  docs/en/observability/index.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
  docs/en/shared/copied-from-beats/install-filebeat/install-widget-filebeat.asciidoc
  docs/en/shared/copied-from-beats/install-heartbeat/install-widget-heartbeat.asciidoc
  docs/en/shared/copied-from-beats/install-metricbeat/install-widget-metricbeat.asciidoc
  docs/en/shared/copied-from-beats/shared/install.asciidoc
  docs/en/shared/copied-from-beats/shared/start.asciidoc
  docs/en/shared/copied-from-beats/start-filebeat/start-filebeat.asciidoc
  docs/en/shared/copied-from-beats/start-filebeat/start-widget-filebeat.asciidoc
  docs/en/shared/copied-from-beats/start-heartbeat/start-widget-heartbeat.asciidoc
  docs/en/shared/copied-from-beats/start-metricbeat/start-widget-metricbeat.asciidoc
  docs/en/shared/install-configure-filebeat.asciidoc
  docs/en/shared/install-configure-metricbeat.asciidoc
Labels: backport-8.8

#2990 Update redirects file
  docs/en/observability/redirects.asciidoc
Labels: backport-8.8

#2998 Universal Profiling: Increase project ID limit to 4096
  docs/en/observability/profiling-tag-data-query.asciidoc
Labels: backport-skip

#3005 Update ingest-traces.asciidoc
  docs/en/observability/ingest-traces.asciidoc
Labels: backport-8.8

#2996 Added Profiling elastic agent integration
  docs/en/observability/images/profililing-elastic-agent-creds.png
  docs/en/observability/images/profiling-elastic-agent.png
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport-8.8

#2997 Add the logs resource guide
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-checklist.asciidoc
  docs/en/observability/logs-overview.asciidoc
Labels: backport-8.8

#3007 Update infra monitoring docs with UI changes
  docs/en/observability/images/hosts-inspect.png
  docs/en/observability/images/hosts-logs.png
  docs/en/observability/images/hosts-open-in-lens.png
  docs/en/observability/images/hosts-view-alerts.png
  docs/en/observability/images/hosts.png
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
  docs/en/observability/monitor-infra/configure-metrics-sources.asciidoc
  docs/en/observability/monitor-infra/explore-metrics.asciidoc
  docs/en/observability/monitor-infra/inspect-metric-anomalies.asciidoc
  docs/en/observability/monitor-infra/view-infrastructure-metrics.asciidoc
Labels: Team:Obs-InfraObs, backport-8.8

#3024 [DOCS] Create stub page for threshold rule
  docs/en/observability/redirects.asciidoc
Labels: backport-skip

#3027 backport: Add 8.9 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#3008 Update permissions for private locations
  docs/en/observability/synthetics-role-write.asciidoc
Labels: Synthetics, backport-8.9, v8.9.0

#3033 Update and rename 8.8-request.yaml to 8.10-request.yaml
  .github/ISSUE_TEMPLATE/8.10-request.yaml
Labels: backport-skip

#3026 Fix firehose documentation on es_datastream_name parameter
  docs/en/aws-firehose/aws-firehose-setup.asciidoc
Labels: backport-skip

#3039 Universal Profiling
  docs/en/observability/images/kibana-edit-user-settings.png
  docs/en/observability/images/profiling-elastic-agent.png
  docs/en/observability/images/profiling-enable-user-settings.png
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-upgrade.asciidoc
Labels: backport-8.9, v8.9.0

#2995 [Profiling] Add upgrade docs for 8.9
  docs/en/observability/index.asciidoc
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-upgrade-fresh.asciidoc
  docs/en/observability/profiling-upgrade-migrate.asciidoc
  docs/en/observability/profiling-upgrade.asciidoc
Labels: backport-8.9, v8.9.0

#3042 Clarify a direct connection to ES is required
  docs/en/observability/synthetics-private-location.asciidoc
  docs/en/observability/synthetics-support-matrix.asciidoc
Labels: Synthetics, backport-8.9, backport-8.4, backport-8.5, backport-8.6, backport-8.7, backport-8.8

#3038 Add missing log types into firehose documentation
  docs/en/aws-firehose/aws-firehose-setup.asciidoc
Labels: backport-skip
