Repository elastic/observability-docs, pull requests merged in 2023-11, with the labels that each got.

#3299 [synthetics] Add `retestOnFailure` option
  docs/en/observability/images/icons/refresh.svg
  docs/en/observability/images/synthetics-get-started-ui-lightweight.png
  docs/en/observability/images/synthetics-retest.png
  docs/en/observability/images/synthetics-ui-inline-script.png
  docs/en/observability/synthetics-analyze.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-get-started-ui.asciidoc
  docs/en/observability/synthetics-lightweight.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc
Labels: backport-8.11

#3325 Small fix for new templates
  .github/ISSUE_TEMPLATE/community-request.yaml
  .github/ISSUE_TEMPLATE/elastic-request.yaml
Labels: backport-skip

#3314 Add custom threshold rule
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/custom-threshold-preview-chart.png
  docs/en/observability/images/custom-threshold-rule.png
  docs/en/observability/images/custom-threshold-run-when.png
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/threshold-alert.asciidoc
Labels: Area:ActionableObs, backport-8.11

#3333 fix: update synthetics agent project id CLI option
  docs/en/observability/synthetics-command-reference.asciidoc
Labels: backport-8.9, backport-8.10, backport-8.11

#3326 [synthetics] Add `locations` and `private_locations` lightweight options
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc
Labels: backport-8.9, backport-8.10, backport-8.11

#3161 add alert details page docs
  docs/en/observability/images/alert-details-page.png
  docs/en/observability/images/view-alert-details.png
  docs/en/observability/view-observability-alerts.asciidoc
Labels: Area:ActionableObs, backport-8.10, backport-8.11

#3328 Update docs about inventory page to show new host details flyout
  docs/en/observability/images/anomalies-overlay.png
  docs/en/observability/images/expand-icon.png
  docs/en/observability/images/hosts.png
  docs/en/observability/images/logs-overlay.png
  docs/en/observability/images/metadata-overlay.png
  docs/en/observability/images/metrics-app.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/images/osquery-overlay.png
  docs/en/observability/images/table-view-icon.png
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
  docs/en/observability/monitor-infra/host-details-partial.asciidoc
  docs/en/observability/monitor-infra/host-metrics.asciidoc
  docs/en/observability/monitor-infra/view-infrastructure-metrics.asciidoc
Labels: v8.11.0, backport-8.11

#3352 Update OSquery image
  docs/en/observability/images/osquery-overlay.png
Labels: backport-8.11

#3300 Fix browser project monitor alert config
  docs/en/observability/synthetics-configuration.asciidoc
Labels: backport-8.10, backport-8.11

#3331 [SLO] Add info on "SLO Overview" panel for custom dashboards
  docs/en/observability/images/slo-overview-embeddable-widget.png
  docs/en/observability/slo-burn-rate-alert.asciidoc
  docs/en/observability/slo-create.asciidoc
  docs/en/observability/slo-overview.asciidoc
  docs/en/observability/slo-privileges.asciidoc
Labels: backport-skip

#3361 [Logs] update host connection troubleshooting
  docs/en/observability/logs-troubleshooting.asciidoc
Labels: backport-8.10, backport-8.11

#3364 Clarify path to anomaly detection page
  docs/en/observability/monitor-infra/inspect-metric-anomalies.asciidoc
Labels: backport-8.11

#3360 Update CODEOWNERS
  .github/CODEOWNERS
Labels: backport-skip

#3370 Fix minor issues found during testing
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
  docs/en/observability/monitor-infra/configure-metrics-sources.asciidoc
  docs/en/observability/monitor-infra/inspect-metric-anomalies.asciidoc
  docs/en/observability/monitor-infra/view-infrastructure-metrics.asciidoc
Labels: backport-8.11

#3374 Update connectors link in AI assistant guide
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: docs, backport-8.10, backport-8.11

#3382 Add documentation clarification
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/http.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/icmp.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/tcp.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.10, backport-8.11

#3378 Remove connector info for ingesting external data
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.10, backport-8.11
