Repository elastic/observability-docs, pull requests merged in 2023-01, with the labels that each got.

#2457 Add mention to Package Registry dedicated /health endpoint
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-7.17, backport-8.5, backport-8.6

#2456 [DOCS] Add server.publicBaseUrl to case setup
  docs/en/observability/grant-cases-access.asciidoc
Labels: docs, v8.7.0, v8.6.0, backport-8.6

#2465 Update Alerting screenshots
  docs/en/observability/images/alerts-page.png
  docs/en/observability/images/create-alerts-manage-rules.png
  docs/en/observability/images/create-alerts-rules-details.png
  docs/en/observability/images/view-alert-details.png
Labels: backport-8.6

#2477 [DOCS] Bulk actions in Cases
  docs/en/observability/manage-cases.asciidoc
Labels: docs, v8.7.0, v8.6.0, backport-8.6

#2462 Add info on adding a Fleet Server to a policy
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
  docs/en/ingest-management/images/add-fleet-server-to-policy.png
Labels: backport-8.6

#2479 Add unique input IDs to all agent policy examples.
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/providers/docker-provider.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/providers/local-dynamic-provider.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.yml
  docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-dynamic-inputs.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
  docs/en/ingest-management/elastic-agent/run-container-common/download-elastic-agent.asciidoc
Labels: Team:Elastic-Agent, backport-8.6

#2476 V2 Docs Update
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.6

#500 Add processor docs to Elastic Agent settings reference
  docs/en/ingest-management/elastic-agent/configuration/authentication/ssl-settings.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/images/add-processor.png
  docs/en/ingest-management/images/migration-add-processor.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/migrate-auditbeat-to-agent.asciidoc
  docs/en/ingest-management/processors/indexers-and-matchers.asciidoc
  docs/en/ingest-management/processors/processor-add_cloud_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_cloudfoundry_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_docker_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_fields.asciidoc
  docs/en/ingest-management/processors/processor-add_host_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_id.asciidoc
  docs/en/ingest-management/processors/processor-add_kubernetes_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_labels.asciidoc
  docs/en/ingest-management/processors/processor-add_locale.asciidoc
  docs/en/ingest-management/processors/processor-add_network_direction.asciidoc
  docs/en/ingest-management/processors/processor-add_nomad_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_observer_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_process_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_tags.asciidoc
  docs/en/ingest-management/processors/processor-communityid.asciidoc
  docs/en/ingest-management/processors/processor-convert.asciidoc
  docs/en/ingest-management/processors/processor-copy_fields.asciidoc
  docs/en/ingest-management/processors/processor-decode_base64_field.asciidoc
  docs/en/ingest-management/processors/processor-decode_cef.asciidoc
  docs/en/ingest-management/processors/processor-decode_csv_fields.asciidoc
  docs/en/ingest-management/processors/processor-decode_json_fields.asciidoc
  docs/en/ingest-management/processors/processor-decode_xml.asciidoc
  docs/en/ingest-management/processors/processor-decode_xml_wineventlog.asciidoc
  docs/en/ingest-management/processors/processor-decompress_gzip_field.asciidoc
  docs/en/ingest-management/processors/processor-detect_mime_type.asciidoc
  docs/en/ingest-management/processors/processor-dissect.asciidoc
  docs/en/ingest-management/processors/processor-dns.asciidoc
  docs/en/ingest-management/processors/processor-drop_event.asciidoc
  docs/en/ingest-management/processors/processor-drop_fields.asciidoc
  docs/en/ingest-management/processors/processor-extract_array.asciidoc
  docs/en/ingest-management/processors/processor-fingerprint.asciidoc
  docs/en/ingest-management/processors/processor-include_fields.asciidoc
  docs/en/ingest-management/processors/processor-parse_aws_vpc_flow_log.asciidoc
  docs/en/ingest-management/processors/processor-rate_limit.asciidoc
  docs/en/ingest-management/processors/processor-registered_domain.asciidoc
  docs/en/ingest-management/processors/processor-rename.asciidoc
  docs/en/ingest-management/processors/processor-replace.asciidoc
  docs/en/ingest-management/processors/processor-script.asciidoc
  docs/en/ingest-management/processors/processor-syntax.asciidoc
  docs/en/ingest-management/processors/processor-syslog.asciidoc
  docs/en/ingest-management/processors/processor-timestamp.asciidoc
  docs/en/ingest-management/processors/processor-translate_sid.asciidoc
  docs/en/ingest-management/processors/processor-truncate_fields.asciidoc
  docs/en/ingest-management/processors/processor-urldecode.asciidoc
  docs/en/ingest-management/processors/processors-list.asciidoc
  docs/en/ingest-management/processors/processors.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.3.asciidoc
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, backport-8.6

#2436 Customer request to highlight the order they need to upgrade in when …
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-8.5, backport-8.6

#2450 Add Fleet/Agent 8.6.0 release notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: Team:Docs, backport-8.6

#2445 [synthetics] Document migrating from the Synthetics Integration
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-get-started.asciidoc
  docs/en/observability/synthetics-migrate-integration.asciidoc
Labels: Synthetics, backport-8.6

#2490 Move relnotes item from features to enhancements
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: backport-8.6

#2471 [DOCS] Notify assignees when assigned to a case
  README.md
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases.asciidoc
Labels: v8.7.0, v8.6.0, backport-8.6

#2506 Remove relontes entry for Kibana #142369 in 8.6
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: backport-8.6

#2467 remove conf `xpack.security.enabled: true`
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.6

#2517 remove conf `xpack.security.enabled: true` (#2467)
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport

#2511 Fix numbering problem caused by linter comment
  docs/en/observability/ingest-logs-metrics-uptime.asciidoc
Labels: backport-8.3, backport-8.4, backport-8.5, backport-8.6

#2515 Fix app log ingest doc
  docs/en/observability/tab-widgets/filebeat-logs/content.asciidoc
Labels: backport-8.6

#2527 Fix list formatting in air gapped docs
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-8.5, backport-8.6

#2491 Excluding APM server from the output section of compatibility page
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-8.6

#2525 Add new known issue to 8.6 agent release notes
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: Team:Docs, backport-8.6

#2513 Correction to the processor document for agent
  docs/en/ingest-management/processors/processors.asciidoc
Labels: backport-8.6

#2514 Document elastic-agent required resources
  docs/en/ingest-management/elastic-agent/run-container-common/download-elastic-agent.asciidoc
Labels: backport-8.5, backport-8.6

#2512 Update link to integrations in the Fleet/Agent overview
  docs/en/ingest-management/overview.asciidoc
Labels: backport-8.5, backport-8.6

#2551 Replace outdated ingest-guide attribute
  docs/en/ingest-management/tab-widgets/run.asciidoc
Labels: backport-skip

#2544 Add Fleet/Agent 8.6.1 relnotes
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, backport-8.6, v8.6.1

#2542 docs: Finish Application logging docs
  docs/en/observability/application-logs.asciidoc
  docs/en/observability/tab-widgets/filebeat-logs/content.asciidoc
Labels: docs, backport-8.6

#2559 Fix broken automation
  .github/workflows/add-pr-to-project.yml
Labels: backport-skip

#2560 Update GitHub actions project ID
  .github/workflows/add-pr-to-project.yml
Labels: backport-skip

#2565 Add Fleet and Elastic Agent 7.17.9 release notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: v7.17.9

#2552 Update kubernetes provider documentation and 8.6 release notes
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: backport-skip, Team:Cloudnative-Monitoring

#2473 [observability] update documentation for esf lambda-v1.6.0 release (n…
  docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-serverless-troubleshooting.asciidoc
Labels: backport-8.3, backport-8.1, backport-7.16, backport-8.2, backport-8.0, backport-7.17, backport-8.4, backport-8.5, backport-8.6

#2576 remove checks from backports
  .github/workflows/add-issue-to-project.yml
  .github/workflows/add-pr-to-project.yml
  .github/workflows/add-to-dev-projects.yml
Labels: backport-8.3, backport-8.4, backport-8.5

#2561 Update mergify, issue template, and codeowners
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/8.8-request.yaml
  .github/workflows/add-pr-to-project.yml
  .mergify.yml
Labels: backport-skip
