Repository elastic/observability-docs, pull requests merged in 2023-02, with the labels that each got.

#2579 Add section to monitoring page about agent diagnostics
  docs/en/ingest-management/fleet/images/collect-agent-diagnostics.png
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: Team:Fleet, backport-skip

#2584 docs: link to new java docs
  docs/en/observability/application-logs.asciidoc
Labels: backport-8.6

#2587 [main] Including backslash in docker run command (#2586)
  docs/en/observability/synthetics-private-location.asciidoc
Labels: backport

#2296 Remote Elasticsearch cluster is not supported
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport-8.6, backport-8.7

#2591 Added system audit reference docs
  docs/en/ingest-management/migrate-auditbeat-to-agent.asciidoc
Labels: Team:Security-External Integrations, backport-8.7

#2580 Update Fleet Server diagram
  docs/en/ingest-management/fleet/diagrams/fleet-server-diagram.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/fleet/images/fleet-server-communication.png
Labels: docs, backport-8.6, backport-8.7

#2594 docs: fix add issue to project automation
  .github/workflows/add-issue-to-project.yml
Labels: backport-skip

#2582 Add docs for scaling private locations
  docs/en/observability/synthetics-private-location.asciidoc
Labels: docs, enhancement, Team:Uptime, v8.7.0, backport-8.7

#2610 Update synthetics-private-location.asciidoc
  docs/en/observability/synthetics-private-location.asciidoc
Labels: Team:Uptime, v8.7.0, backport-8.7

#2583 Add docs for monitoring private networks via synthetics service
  docs/en/observability/synthetics-private-location.asciidoc
Labels: enhancement, v8.7.0, backport-8.6, backport-8.7

#2518 max number of policies
  docs/en/ingest-management/agent-policies.asciidoc
Labels: backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#1722 [opentelemetry][ci-cd] add section for Ansible tower
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/images/ansible-automation-apm-endpoint.png
  docs/en/observability/images/ansible-automation-apm-service-details.png
Labels: backport-8.5, backport-8.6, backport-8.7

#2463 clarificaton on the comment for root permissions on Agent
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-8.3, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2500 Elastic Serverless Forwarder support for Logstash
  docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
  docs/en/observability/aws-elastic-serverless-forwarder.asciidoc
  docs/en/observability/images/aws-serverless-lambda-flow.png
Labels: backport-8.3, backport-8.1, backport-7.16, backport-8.2, backport-8.0, backport-7.17, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2644 Add Fleet and Elastic Agent 8.6.2 release notes
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet, backport-8.6

#2642 Update release-notes-8.6.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: backport-8.5

#2663 Update Agent metrics dashboard in Fleet Server monitoring docs
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/images/dashboard-datastream.png
  docs/en/ingest-management/fleet/images/dashboard-datastream01.png
Labels: backport-8.7

#2662 Add ventura installation known issue
  docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Labels: Team:Elastic-Agent, Team:Fleet

#2647 [DOCS] Refresh screenshots for metrics threshold rule
  docs/en/observability/images/action-alert-summary.png
  docs/en/observability/images/alert-action-types.png
  docs/en/observability/images/metrics-alert-filters-and-group.png
  docs/en/observability/images/metrics-threshold-alert-default-message.png
  docs/en/observability/images/run-when-selection.png
  docs/en/observability/metrics-threshold-alert.asciidoc
Labels: v8.7.0, v8.8.0, backport-8.7

#1292 Update troubleshooting.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-8.3, backport-8.1, backport-7.16, backport-8.2, backport-8.0, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2678 Fix TOC for troubleshooting
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.3, backport-8.1, backport-8.2, backport-8.0, backport-7.17, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2691 [7.17](backport #2678) Fix TOC for troubleshooting
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport

#2694 ESF: add details on using encrypted S3 buckets
  docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
Labels: backport-8.3, backport-8.1, backport-7.16, backport-8.2, backport-8.0, backport-7.17, backport-8.4, backport-8.5, backport-8.6, backport-8.7

#2693 Updating the fleet server scalability resources
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Labels: backport-skip

#2692 Update Cases screenshot
  docs/en/observability/images/cases.png
Labels: backport-8.7

#2706 Remove -f option from elastic-agent install commands
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: Team:Elastic-Agent, backport-7.17, backport-8.6, backport-8.7

#2708 Ensure all known issues are documented for Agent in 8.6.x
  docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Labels: Team:Elastic-Agent, backport-8.6

#2668 Add compatibility statement to ESF docs
  docs/en/observability/aws-elastic-serverless-forwarder.asciidoc
Labels: backport-8.7

#2719 Fix broken link to Azure Activity Logs
  docs/en/observability/monitor-azure-agent.asciidoc
Labels: Team:Cloud-Monitoring, backport-8.4, backport-8.5, backport-8.6, backport-8.7
