Repository elastic/observability-docs, pull requests merged in 2023-08, with the labels that each got.

#3112 Added the --no-headless option back in
  docs/en/observability/synthetics-command-reference.asciidoc
Labels: backport-skip

#3113 Update logs stream
  docs/en/observability/images/es-endpoint-cluster-id.png
  docs/en/observability/logs-stream.asciidoc
  docs/en/observability/tab-widgets/logs/agent-location-content.asciidoc
  docs/en/observability/tab-widgets/logs/agent-location-widget.asciidoc
Labels: backport-8.9

#3111 Rearrange the profiler docs for UP agent
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport-8.9, backport-8.8

#3105 Add cases to troubleshooting and support matrix pages
  docs/en/observability/synthetics-support-matrix.asciidoc
  docs/en/observability/synthetics-troubleshooting.asciidoc
Labels: backport-8.9, backport-8.8

#3133 Create a logs troubleshooting page
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-troubleshooting.asciidoc
Labels: backport-skip

#3118 add enhance logs and extract timestamp docs
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9

#3135 [DOCS] Remove content reuse for cases
  README.md
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases.asciidoc
Labels: backport-8.9, v8.10.0

#3138 Remove book-scoped attributes
  docs/en/observability/exploratory-data-visualizations.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/monitor-aws-beats.asciidoc
  docs/en/observability/monitor-azure-beats.asciidoc
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/shared/install-configure-filebeat.asciidoc
  docs/en/shared/install-configure-metricbeat.asciidoc
Labels: backport-8.9

#3148 Remove duplicate _index in search response
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9

#3141 Profiling: replace ela.st with artifacts.elastic.co
  docs/en/observability/profiling-add-symbols.asciidoc
Labels: backport-skip, 8.10-candidate, v8.10.0

#3144 [8.8][DOCS] Remove content reuse for cases (#3135)
  README.md
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases.asciidoc
Labels: backport

#3145 [8.7][DOCS] Remove content reuse for cases (#3135)
  README.md
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases.asciidoc
Labels: backport

#3146 [8.6][DOCS] Remove content reuse for cases (#3135)
  README.md
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases.asciidoc
Labels: backport

#3151 backport: Add 8.10 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#3143 Add the Extract the log level field section
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9, backport-8.10

#3155 add Extract host IP section to logs stream docs
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9, backport-8.10

#3162 Remove unnecessary links
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9, backport-8.10

#3140 [Logs] Update docs processing docs
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9, backport-8.10

#3169 [Profiling] correctly document minimum kernel for ARM64
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport-8.9, backport-8.10

#3165 Add reroute processor to stream a log page
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9, backport-8.10

#3175 Update reroute processor config
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9, backport-8.10

#3179 [Profiling] Clarify index cleanup instructions
  docs/en/observability/profiling-upgrade.asciidoc
Labels: Profiling, v8.10.0, backport-8.10

#3184 [Profiling] Improve wording in upgrade docs
  docs/en/observability/profiling-upgrade.asciidoc
Labels: Profiling, v8.10.0, backport-8.10

#3187 Update splunk-get-started.asciidoc
  docs/en/observability/splunk-get-started.asciidoc
Labels: backport-8.9, backport-8.10

#3190 [DOCS] Add conditional actions highlight
  docs/en/observability/images/conditional-actions.png
  docs/en/observability/whats-new.asciidoc
Labels: backport-8.10

#3181 Update SLO privileges screenshot
  docs/en/observability/images/slo-es-priv-all.png
Labels: backport-8.9, backport-8.8, backport-8.10

#3183 Update logs docs for consistency and formatting
  docs/en/observability/logs-stream.asciidoc
Labels: backport-8.9, backport-8.10

#3199 Add links to other Observability guides
  docs/en/observability/observability-get-started.asciidoc
Labels: backport-8.9, backport-8.10

#3200 docs: remove old videos
  docs/en/observability/apm.asciidoc
  docs/en/observability/monitor-infra/analyze-metrics.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/tail-logs.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport-8.9, backport-8.10
