Repository elastic/observability-docs, pull requests merged in 2023-05, with the labels that each got.

#2895 Fix structure of Kinesis TOC
  docs/en/aws-firehose/aws-firehose-setup.asciidoc
  docs/en/aws-firehose/aws-firehose-troubleshooting.asciidoc
  docs/en/aws-firehose/aws-firehose.asciidoc
  docs/en/aws-firehose/images/firehose-architecture.png
  docs/en/aws-firehose/images/firehose-config-1.png
  docs/en/aws-firehose/images/firehose-config-2.png
  docs/en/aws-firehose/images/firehose-config-3.png
  docs/en/aws-firehose/images/firehose-create-delivery-stream.png
  docs/en/aws-firehose/images/firehose-integration-data-stream.png
  docs/en/aws-firehose/images/firehose-integrations-install-assets.png
  docs/en/aws-firehose/images/firehose-integrations-page.png
  docs/en/aws-firehose/images/firehose-monitoring.png
  docs/en/aws-firehose/index.asciidoc
  docs/en/observability/aws-firehose-index.asciidoc
Labels: docs, backport-skip

#2899 Remove unnecessary `=` in build command
  README.md
Labels: backport-8.8

#2880 Spacetime revamp
  docs/en/observability/add-observability-data.asciidoc
  docs/en/observability/application-logs.asciidoc
  docs/en/observability/create-cases.asciidoc
  docs/en/observability/deploy-agent-to-send-data.asciidoc
  docs/en/observability/deploy-beats-to-send-data.asciidoc
  docs/en/observability/gcp-dataflow.asciidoc
  docs/en/observability/images/get-started.svg
  docs/en/observability/images/what-is-observability.svg
  docs/en/observability/index.asciidoc
  docs/en/observability/ingest-logs.asciidoc
  docs/en/observability/ingest-metrics.asciidoc
  docs/en/observability/ingest-traces.asciidoc
  docs/en/observability/ingest-uptime.asciidoc
  docs/en/observability/instrument-apps.asciidoc
  docs/en/observability/logs-metrics-get-started.asciidoc
  docs/en/observability/monitor-aws-agent.asciidoc
  docs/en/observability/monitor-aws-beats.asciidoc
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/monitor-infra/view-infrastructure-metrics.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-overview.asciidoc
  docs/en/observability/observability-get-started.asciidoc
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/observability-ui.asciidoc
  docs/en/observability/redirects.asciidoc
  docs/en/observability/spin-up-stack.asciidoc
  docs/en/observability/splunk-get-started.asciidoc
  docs/en/observability/synthetics-private-location.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport-8.7, 🚀 spacetime 🚀, backport-8.8

#2898 [DOCS] List privileges to add alerts to cases
  docs/en/observability/grant-cases-access.asciidoc
Labels: v8.8.0, v8.9.0, backport-8.8

#2905 Update doc-preview.yml
  .github/workflows/doc-preview.yml
Labels: backport-skip

#2909 Update examples to valid schedules
  docs/en/observability/synthetics-lightweight.asciidoc
Labels: backport-8.5, backport-8.6, backport-8.7

#2924 [synthetics] Typo fix: `module` -> `monitor`
  docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc
Labels: backport-8.7, backport-8.8

#2920 Universal Profiling: add integration installation
  docs/en/observability/profiling-get-started.asciidoc
Labels: v8.8.0, backport-8.8

#2925 [synthetics] Change how enabling monitor management is documented
  docs/en/observability/images/synthetics-enable-monitor-management.png
  docs/en/observability/synthetics-get-started-project.asciidoc
  docs/en/observability/synthetics-get-started-ui.asciidoc
  docs/en/observability/synthetics-get-started.asciidoc
  docs/en/observability/synthetics-role-setup.asciidoc
Labels: backport-8.8

#2935 Universal Profiling: update native symbol upload instructions
  docs/en/observability/images/profiling-apm-cluster-id.png
  docs/en/observability/images/profiling-cloud-id.png
  docs/en/observability/images/profiling-symbolizer-url.png
  docs/en/observability/profiling-add-symbols.asciidoc
Labels: v8.8.0, backport-8.8

#2906 [spacetime] Observability guide landing page
  docs/en/observability/index.asciidoc
  docs/en/observability/landing-page/data/intro-data.json
  docs/en/observability/landing-page/data/recommended-data.json
  docs/en/observability/landing-page/data/related-docs-data.json
  docs/en/observability/landing-page/data/use-cases-data.json
  docs/en/observability/landing-page/images/application-logs.png
  docs/en/observability/landing-page/images/framework-integrations.png
  docs/en/observability/landing-page/images/ingest-logs-metrics-uptime.png
  docs/en/observability/landing-page/images/ingest-traces.png
  docs/en/observability/landing-page/images/integrations.png
  docs/en/observability/landing-page/images/intro.png
  docs/en/observability/landing-page/images/open-telemetry.png
  docs/en/observability/landing-page/images/placeholder.png
  docs/en/observability/landing-page/images/profiling-get-started.png
  docs/en/observability/landing-page/images/rum-js-intro.png
  docs/en/observability/landing-page/images/synthetics-analyze.png
  docs/en/observability/landing-page/images/synthetics-create-test.png
  docs/en/observability/landing-page/images/synthetics-get-started.png
  docs/en/observability/landing-page/images/universal-profiling.png
  docs/en/observability/landing-page/images/user-experience.png
  docs/en/observability/landing-page/page.asciidoc
  docs/en/observability/landing-page/temp/images/apmApp.svg
  docs/en/observability/landing-page/temp/images/fleetApp.svg
  docs/en/observability/landing-page/temp/images/logoCloud.svg
  docs/en/observability/landing-page/temp/images/logoElastic.svg
  docs/en/observability/landing-page/temp/images/logoKibana.svg
  docs/en/observability/landing-page/temp/images/logoUptime.svg
  docs/en/observability/landing-page/temp/images/logsApp.svg
  docs/en/observability/landing-page/temp/images/metricsApp.svg
  docs/en/observability/landing-page/temp/images/profilingApp.svg
  docs/en/observability/landing-page/temp/images/rumApp.svg
  docs/en/observability/landing-page/temp/script.asciidoc
  docs/en/observability/landing-page/temp/style.asciidoc
Labels: backport-8.8

#2937 Add info on enabling profiling in Kibana.
  docs/en/observability/images/kibana-edit-user-settings.png
  docs/en/observability/images/profiling-enable-user-settings.png
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport-8.8

#2943 Universal Profiling: Fix markup
  docs/en/observability/profiling-troubleshooting.asciidoc
Labels: bug, quick fix, v8.8.0, backport-8.8

#2915 Add SLO docs to the Observability docs
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/create-new-alert-rule-menu.png
  docs/en/observability/images/slo-dashboard.png
  docs/en/observability/images/slo-detailed-view.png
  docs/en/observability/images/slo-es-priv-all.png
  docs/en/observability/images/slo-es-priv-read.png
  docs/en/observability/images/slo-kibana-priv-all.png
  docs/en/observability/images/slo-kibana-priv-read.png
  docs/en/observability/index.asciidoc
  docs/en/observability/slo-burn-rate-alert.asciidoc
  docs/en/observability/slo-create.asciidoc
  docs/en/observability/slo-overview.asciidoc
  docs/en/observability/slo-privileges.asciidoc
Labels: backport-8.8

#2923 [synthetics] Document additional lightweight monitor config options
  docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/http.asciidoc
Labels: backport-8.8

#2930 [synthetics] Update setup role privileges
  docs/en/observability/synthetics-role-setup.asciidoc
Labels: backport-8.8

#2938 [Synthetics] Document the support matrix for the various Synthetics components
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-support-matrix.asciidoc
Labels: backport-8.8

#2922 [synthetics] Document param support for lightweight monitors
  docs/en/observability/images/synthetics-params-secrets-kibana-define.png
  docs/en/observability/images/synthetics-params-secrets-kibana-use-browser.png
  docs/en/observability/images/synthetics-params-secrets-kibana-use-lightweight.png
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
Labels: backport-8.8

#2929 [synthetics] Remove beta labels
  docs/en/observability/index.asciidoc
  docs/en/observability/observability-introduction.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-get-started-project.asciidoc
  docs/en/observability/synthetics-get-started-ui.asciidoc
  docs/en/observability/synthetics-get-started.asciidoc
  docs/en/observability/synthetics-intro.asciidoc
  docs/en/observability/synthetics-journeys.asciidoc
  docs/en/observability/synthetics-lightweight.asciidoc
  docs/en/observability/synthetics-manage-monitors.asciidoc
  docs/en/observability/synthetics-manage-retention.asciidoc
  docs/en/observability/synthetics-migrate-integration.asciidoc
  docs/en/observability/synthetics-monitor-use.asciidoc
  docs/en/observability/synthetics-params-secrets.asciidoc
  docs/en/observability/synthetics-private-location.asciidoc
  docs/en/observability/synthetics-recorder.asciidoc
  docs/en/observability/synthetics-settings.asciidoc
Labels: backport-8.8

#2946 enhance application logs
  docs/en/observability/application-logs.asciidoc
  docs/en/observability/tab-widgets/filebeat-logs/widget.asciidoc
Labels: backport-8.7, backport-8.8

#2952 [synthetics] Add a note about timeout types and defaults
  docs/en/observability/synthetics-configuration.asciidoc
Labels: backport-8.8

#2957 Update recorder download location
  docs/en/observability/synthetics-recorder.asciidoc
Labels: Synthetics, backport-8.8

#2964 Add secret token to step two
  docs/en/observability/tab-widgets/add-apm-integration/content.asciidoc
Labels: backport-8.8

#2970 [DOCS] Maintenance windows
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/alert-table-toolbar-buttons.png
  docs/en/observability/view-observability-alerts.asciidoc
Labels: docs, v8.8.0, v8.9.0, backport-8.8

#2564 Add AWS monitoring docs to the observability guide
  docs/en/observability/cloud-monitoring/aws/images/ec2-overview-dashboard.png
  docs/en/observability/cloud-monitoring/aws/images/kinesis-dashboard.png
  docs/en/observability/cloud-monitoring/aws/images/s3-dashboard.png
  docs/en/observability/cloud-monitoring/aws/images/sqs-dashboard.png
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-ec2.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-kinesis.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-s3.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-sqs.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/shared/integrations-quick-guide.asciidoc
Labels: backport-8.7, backport-8.8

#2981 [DOCS] Refresh log-threshold-rul-when-selection.png
  docs/en/observability/images/log-threshold-run-when-selection.png
Labels: docs, v8.8.0, v8.9.0, backport-8.8

#2977 Universal Profiling: Describe range for project-id, remove Elastic Agent
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-tag-data-query.asciidoc
Labels: Profiling, backport-8.8

#2971 Add spacetime changes we missed
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-intro.asciidoc
  docs/en/observability/uptime-intro.asciidoc
  docs/en/observability/user-experience.asciidoc
Labels: backport-8.8

#2985 Update Azure monitoring tutorial to show new naming and screens
  docs/en/observability/images/monitor-azure-native-create-elastic-resource.png
  docs/en/observability/images/monitor-azure-native-elastic-config-logs-metrics.png
  docs/en/observability/images/monitor-azure-native-elastic-deployment.png
  docs/en/observability/images/monitor-azure-native-elastic-vms.png
  docs/en/observability/images/monitor-azure-native-kibana-logs-app.png
  docs/en/observability/images/monitor-azure-native-kibana-observability-page-data.png
  docs/en/observability/images/monitor-azure-native-kibana-vms-logs.png
  docs/en/observability/images/monitor-azure-native-kibana-vms-metrics-detail.png
  docs/en/observability/images/monitor-azure-native-kibana-vms-metrics.png
  docs/en/observability/monitor-azure-native.asciidoc
Labels: backport-8.8

#2953 [Synthetics] Add docs on encryption and security
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-security-encryption.asciidoc
Labels: docs, enhancement, Team:Uptime, backport-skip
