Repository elastic/observability-docs, pull requests merged in 2024-08, with the labels that each got.

#4103 Add docs for Quality Issues table
  docs/en/serverless/logging/view-and-monitor-logs.mdx
Labels: backport-skip, ci:doc-build

#4093 Add region doc link
  docs/en/serverless/projects/create-an-observability-project.mdx
Labels: backport-skip, ci:doc-build

#3687 [DOCS] Clarify AI Assistant will spawn ML nodes
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.9, backport-8.10, backport-8.11, backport-8.12, backport-8.13, backport-8.14, backport-8.15

#4109 Update .mergify.yml
  .mergify.yml
Labels: backport-skip

#4104 [main] Update sampling.asciidoc (#4101)
  docs/en/observability/apm/sampling.asciidoc
Labels: backport-8.15

#4119 Add missing dash in probabilistic profiling docs
  docs/en/observability/profiling-probabilistic-profiling.asciidoc
Labels: backport-8.15

#4097 Add doc for diagnosing backpressure from Elasticsearch
  docs/en/observability/apm/apm-performance-diagnostic.asciidoc
  docs/en/observability/apm/troubleshoot-apm.asciidoc
Labels: backport-8.15

#4084 Case custom fields GA
  docs/en/observability/images/cases-custom-field-settings.png
  docs/en/observability/images/cases-settings.png
  docs/en/observability/manage-cases-settings.asciidoc
  docs/en/observability/manage-cases.asciidoc
  docs/en/serverless/cases/create-manage-cases.mdx
  docs/en/serverless/cases/manage-cases-settings.mdx
  docs/en/serverless/images/observability-cases-custom-fields.png
  docs/en/serverless/images/observability-cases-settings.png
Labels: ci:doc-build, backport-8.15

#4116 Port logs service.name docs to stateful
  docs/en/observability/images/add-field-processor.png
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-add-service-name.asciidoc
Labels: backport-8.15

#4113 Port EEM and new services experience docs to stateful
  docs/en/observability/apm-ui/index.asciidoc
  docs/en/observability/apm-ui/new-experience-services.asciidoc
  docs/en/observability/apm-ui/services.asciidoc
  docs/en/observability/apm/images/entity-centric-services-inventory.png
  docs/en/observability/elastic-entity-model.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/reference.asciidoc
  docs/en/serverless/elastic-entity-model.mdx
Labels: ci:doc-build, backport-8.15

#4131 Fix typo and duplication
  docs/en/integrations/quick-start.asciidoc
Labels: backport-skip

#4135 Fix outdated screenshot in logs and metrics GS guide
  docs/en/observability/images/kibana-agent-system-integration-visualizations.png
Labels: backport-8.15

#4130 [DOCS] Private LLMs & free-tier is not likely enough
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.14, backport-8.15

#4073 Add hosts/auto-detection + K8s quick start plus overview
  docs/en/serverless/images/quickstart-autodetection-command.png
  docs/en/serverless/images/quickstart-host-overview.png
  docs/en/serverless/images/quickstart-k8s-entry-point.png
  docs/en/serverless/images/quickstart-k8s-overview.png
  docs/en/serverless/quickstarts/k8s-logs-metrics.mdx
  docs/en/serverless/quickstarts/monitor-hosts-with-elastic-agent.mdx
  docs/en/serverless/quickstarts/overview.mdx
  docs/en/serverless/serverless-observability.docnav.json
  docs/en/serverless/what-is-observability-serverless.mdx
Labels: backport-skip, ci:doc-build

#4100 Update APM OTel page
  docs/en/observability/apm/diagrams/apm-otel-architecture.asciidoc
  docs/en/observability/apm/images/apm-otel-api-sdk-collector.png
  docs/en/observability/apm/images/apm-otel-api-sdk-elastic-agent.png
  docs/en/observability/apm/images/apm-otel-distro.png
  docs/en/observability/apm/images/apm-otel-lambda.png
  docs/en/observability/apm/open-telemetry.asciidoc
  docs/en/observability/apm/otel-direct.asciidoc
  docs/en/observability/apm/otel-other.asciidoc
  docs/en/observability/apm/otel-with-elastic.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: backport-8.15

#4147 Add tags to fix chunking in obs guide
  docs/en/observability/apm-ui/api.asciidoc
  docs/en/observability/apm/configure/outputs/console.asciidoc
  docs/en/observability/apm/configure/outputs/elasticsearch.asciidoc
  docs/en/observability/apm/configure/outputs/kafka.asciidoc
  docs/en/observability/apm/configure/outputs/logstash.asciidoc
  docs/en/observability/apm/configure/outputs/output-cloud.asciidoc
  docs/en/observability/apm/configure/outputs/redis.asciidoc
  docs/en/observability/apm/sampling.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14, backport-8.15

#4157 Add tags to fix chunking
  docs/en/observability/apm-ui/apm-app-users.asciidoc
  docs/en/observability/apm/feature-roles.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14, backport-8.15

#4169 Fix broken image links in data quality topic
  docs/en/observability/logs-monitor-datasets.asciidoc
Labels: backport-skip, backport-8.15

#4162 Update profiling upgrade hint
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14, backport-8.15

#4144 Jaeger deprecation warning
  docs/en/observability/apm/jaeger-integration.asciidoc
Labels: backport-skip

#4176 Fix typos in k8s-logs-metrics.mdx
  docs/en/serverless/quickstarts/k8s-logs-metrics.mdx
Labels: backport-skip

#4170 Profiling: update backend API role permissions
  docs/en/observability/profiling-self-managed.asciidoc
Labels: backport-8.15

#4156 Update serverless APM OTel page
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-opentelemetry-apisdk-with-elastic-apm-agents.mdx
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-opentelemetry-native-support.mdx
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-other-execution-environments.mdx
  docs/en/serverless/apm-agents/apm-agents-opentelemetry.mdx
  docs/en/serverless/apm-agents/images/apm-otel-api-sdk-collector.png
  docs/en/serverless/apm-agents/images/apm-otel-api-sdk-elastic-agent.png
  docs/en/serverless/apm-agents/images/apm-otel-distro.png
  docs/en/serverless/serverless-observability.docnav.json
Labels: backport-skip, ci:doc-build

#4137 Update .Net Label link to non-deprecated version
  docs/en/observability/apm/data-model.asciidoc
Labels: backport-8.14, backport-main

#4165 [apm] Update agent key privileges to include access to Kibana
  docs/en/observability/apm-ui/api.asciidoc
Labels: backport-8.14, backport-8.15

#4185 Fix heading levels in Java tutorial
  docs/en/observability/monitor-java-app.asciidoc
Labels: backport-8.14, backport-8.15

#4191 Remove anchor from link to Kibana dashboards page
  docs/en/observability/monitor-java-app.asciidoc
Labels: Team:Docs, backport-skip

#4184 Add docs on how to opt-out of complex object parsing
  docs/en/observability/apm/configure/env.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14, backport-8.15

#4168 Add hosts and K8s quickstarts to stateful docs
  docs/en/observability/images/quickstart-autodetection-command.png
  docs/en/observability/images/quickstart-host-overview.png
  docs/en/observability/images/quickstart-k8s-entry-point.png
  docs/en/observability/images/quickstart-k8s-overview.png
  docs/en/observability/index.asciidoc
  docs/en/observability/quickstarts/monitor-hosts-with-elastic-agent.asciidoc
  docs/en/observability/quickstarts/monitor-k8s-logs-metrics.asciidoc
  docs/en/observability/quickstarts/quickstarts-overview.asciidoc
  docs/en/serverless/quickstarts/k8s-logs-metrics.mdx
  docs/en/serverless/quickstarts/monitor-hosts-with-elastic-agent.mdx
Labels: backport-skip, ci:doc-build

#4146 feat(apm/otel): include processors in pipelines example
  docs/en/observability/apm/otel-direct.asciidoc
Labels: backport-8.14, backport-main

#4199 Update the data set quality page
  docs/en/observability/logs-monitor-datasets.asciidoc
  docs/en/serverless/logging/monitor-datasets.mdx
Labels: backport-skip, ci:doc-build

#4183 Add topic about missing fields
  docs/en/observability/handle-no-results-found-message.asciidoc
  docs/en/observability/images/turn-on-system-metrics.png
  docs/en/observability/index.asciidoc
  docs/en/observability/troubleshooting-infra.asciidoc
Labels: backport-skip

#4167 [apm] Add examples using `trace_continuation_strategy` to sampling docs
  docs/en/observability/apm/images/dt-sampling-continuation-strategy-restart.png
  docs/en/observability/apm/images/dt-sampling-continuation-strategy-restart_external.png
  docs/en/observability/apm/images/dt-sampling-example-1.png
  docs/en/observability/apm/images/dt-sampling-example-2.png
  docs/en/observability/apm/images/dt-sampling-example-3.png
  docs/en/observability/apm/sampling.asciidoc
Labels: backport-8.14, backport-8.15

#4204 Port PR #4183 to serverless
  docs/en/serverless/images/turn-on-system-metrics.png
  docs/en/serverless/infra-monitoring/handle-no-results-found-message.mdx
  docs/en/serverless/infra-monitoring/troubleshooting-infra.mdx
  docs/en/serverless/serverless-observability.docnav.json
Labels: backport-skip, ci:doc-build
