Repository elastic/observability-docs, pull requests merged in 2024-03, with the labels that each got.

#3650 Add Kibana privileges for Logs Explorer
  docs/en/observability/explore-logs.asciidoc
Labels: backport-8.13

#3647 apm: Add known issue for excessive rollover
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.12, backport-8.13

#3581 [Logs] Update the Monitor K8s tutorial to use Standalone Agent and the K8s integration
  docs/en/observability/images/standalone-mode-link.png
  docs/en/observability/logs-checklist.asciidoc
  docs/en/observability/monitor-k8s/images/add-kubernetes-button.png
  docs/en/observability/monitor-k8s/images/apm-app-kubernetes-filter.png
  docs/en/observability/monitor-k8s/images/k8s-monitoring-architecture.png
  docs/en/observability/monitor-k8s/images/log-explorer.png
  docs/en/observability/monitor-k8s/images/logs-explorer-applications.png
  docs/en/observability/monitor-k8s/images/metadata-processors.png
  docs/en/observability/monitor-k8s/images/run-standalone-option.png
  docs/en/observability/monitor-k8s/monitor-k8s-add-integration.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-explore-logs-and-metrics.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-metrics.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-overview.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s.asciidoc
Labels: backport-8.13

#3657 [DOCS] screenshot/video limitation
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport-skip

#3587 Update APM agent instructions
  docs/en/observability/apm/tab-widgets/install-agents.asciidoc
Labels: backport-8.12, backport-8.13

#3665 [DOCS] Case custom field default values
  docs/en/observability/images/cases-add-custom-field.png
  docs/en/observability/manage-cases.asciidoc
Labels: backport-8.13

#3667 [DOCS] Alert creation delay
  docs/en/observability/infrastructure-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/slo-burn-rate-alert.asciidoc
Labels: backport-8.13

#3671 Add `ingest-docs` as a dependency and remove `beats`
  README.md
Labels: backport-skip

#3677 Fix spelling error
  docs/en/observability/ci-cd-observability.asciidoc
Labels: backport-8.12, backport-8.13

#3678 Remove tech preview badge from docs about viewing alerts
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport-8.12, backport-8.13

#3664 Update docs to indicate that SLO burn rate rule is created automatically
  docs/en/observability/slo-burn-rate-alert.asciidoc
  docs/en/observability/slo-create.asciidoc
Labels: 8.1.3, backport-8.13

#3663 Update observability AI assistant docs with latest changes
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.13

#3688 Temporarily comment out release note redirects
  docs/en/apm-server/redirects.asciidoc
Labels: backport-8.13

#3691 Clarify synthetics params / secrets docs
  docs/en/observability/synthetics-params-secrets.asciidoc
Labels: backport-8.11, backport-8.12, backport-8.13

#3699 Fix URL for AWS EC2 (#3698)
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-ec2.asciidoc
Labels: backport-8.13

#3693 [Alerting] Add list of action variables to Observability alerting docs
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/inventory-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/slo-burn-rate-alert.asciidoc
  docs/en/observability/threshold-alert.asciidoc
Labels: backport-8.13

#3690 [Alerting] Add list of valid connectors to alerting rules docs
  docs/en/observability/inventory-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/slo-burn-rate-alert.asciidoc
  docs/en/observability/threshold-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/shared/alerting-connectors.asciidoc
Labels: backport-8.13

#3704 Add link in apm sampling to otel sampling limitations
  docs/en/observability/apm/sampling.asciidoc
Labels: backport-8.12, backport-8.13

#3630 security: add permissions block to workflows
  .github/workflows/add-issue-to-project.yml
  .github/workflows/add-pr-to-project.yml
  .github/workflows/add-to-dev-projects.yml
Labels: backport-skip
