Repository elastic/observability-docs, pull requests merged in 2024-12, with the labels that each got.

#4594 Use official serverless product names
  docs/en/observability/landing-page/page.asciidoc
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-limitations.asciidoc
  docs/en/serverless/apm-agents/apm-agents-opentelemetry.asciidoc
  docs/en/serverless/apm/apm-ui-trace-sample-timeline.asciidoc
  docs/en/serverless/cases/cases.asciidoc
  docs/en/serverless/cases/manage-cases-settings.asciidoc
  docs/en/serverless/index.asciidoc
  docs/en/serverless/logging/log-monitoring.asciidoc
  docs/en/serverless/observability-get-started.asciidoc
  docs/en/serverless/projects/billing.asciidoc
  docs/en/serverless/reference/elastic-entity-model.asciidoc
  docs/en/serverless/synthetics/synthetics-get-started-project.asciidoc
  docs/en/serverless/synthetics/synthetics-settings.asciidoc
  docs/en/serverless/transclusion/apm/guide/diagrams/apm-otel-architecture.asciidoc
  docs/en/serverless/transclusion/synthetics/global-managed-paid-for.asciidoc
  docs/en/serverless/what-is-observability-serverless.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4616 Make hero text on obs landing page smaller
  docs/en/observability/landing-page/temp/style.asciidoc
Labels: backport-8.9, needs-writer-review, backport-8.8, backport-8.10, backport-8.11, backport-8.12, backport-8.13, backport-8.14, backport-8.15, backport-8.x, backport-8.16, backport-8.17

#4611 Port #4349 to serverless
  docs/en/serverless/alerting/create-custom-threshold-alert-rule.asciidoc
Labels: backport-skip, needs-writer-review

#4632 Stateful - crop images that show old navigation
  docs/en/observability/images/monitor-azure-kibana-deployment.png
  docs/en/observability/images/monitor-azure-kibana-security.png
  docs/en/observability/images/monitor-azure-native-kibana-observability-page-data.png
  docs/en/observability/images/monitor-azure-native-kibana-vms-logs.png
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4633 Serverless - crop images that show old navigation
  docs/en/observability/images/quickstart-k8s-otel-dashboard.png
  docs/en/serverless/images/cases.png
  docs/en/serverless/images/entity-detailed-view.png
  docs/en/serverless/images/inventory-catalog.png
  docs/en/serverless/images/observability-cases-settings.png
  docs/en/serverless/images/quickstart-k8s-otel-dashboard.png
  docs/en/serverless/images/quickstart-k8s-overview.png
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4584 Tell users to contact support for rate limiting issues
  docs/en/serverless/limitations.asciidoc
Labels: backport-skip, needs-writer-review

#4646 add logs explorer note to settings page
  docs/en/observability/configure-logs-sources.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4656 Remove Enterprise subscription mention
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: needs-writer-review, backport-8.10, backport-8.11, backport-8.12, backport-8.13, backport-8.14, backport-8.15, backport-8.x, backport-8.16, backport-8.17

#4641 Update serverless billing dimensions for GA
  docs/en/serverless/projects/billing.asciidoc
Labels: backport-skip, needs-writer-review

#4667 Reword ILM how to guide for revert to ILM policies
  docs/en/observability/apm/manage-storage/ilm-how-to.asciidoc
Labels: needs-writer-review, backport-8.17

#4657 Add Synthetic `_source` callout to APM + UP docs
  docs/en/observability/apm/manage-storage/data-streams.asciidoc
  docs/en/observability/profiling-manage-storage.asciidoc
Labels: needs-writer-review, backport-8.17

#4599 Clean up APM getting started intro page
  docs/en/observability/apm/getting-started-apm/index.asciidoc
Labels: needs-writer-review, backport-8.x, needs-dev-review, backport-8.16, backport-8.17

#4695 apm shared-docker: add note for wolfi image
  docs/en/observability/apm/shared-docker.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4691 apm-ilm: update apm-ilm-how-to expand dsl migration note
  docs/en/observability/apm/manage-storage/ilm-how-to.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.17

#4686 o11y AI assistant: add doc entry about the product doc
  docs/en/observability/observability-ai-assistant.asciidoc
  docs/en/serverless/ai-assistant/ai-assistant.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.17

#4703 [apm] Update custom filters page
  docs/en/observability/apm/security/data-security/custom-filter.asciidoc
  docs/en/observability/apm/security/data-security/index.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4713 [apm] Update APM decision tree diagram
  docs/en/observability/apm/diagrams/apm-decision-tree.asciidoc
  docs/en/observability/apm/getting-started-apm/index.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17
