Repository elastic/observability-docs, pull requests merged in 2024-05, with the labels that each got.

#3849 [SLO] Add manage_ingest_pipelines to list of required privileges
  docs/en/observability/images/slo-es-priv-all.png
  docs/en/observability/slo-privileges.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14

#3826 Create NGINX onboarding tutorial
  docs/en/observability/images/nginx-data-selector.png
  docs/en/observability/images/nginx-logs-access-error-dashboard.png
  docs/en/observability/images/nginx-logs-explorer.png
  docs/en/observability/images/nginx-logs-overview-dashboard.png
  docs/en/observability/images/nginx-metrics-dashboard.png
  docs/en/observability/monitor-nginx.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: backport-8.13, backport-8.14

#3854 Profiling: upgrade guide for self-hosted profiling agents
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-self-managed-ops.asciidoc
  docs/en/observability/profiling-upgrade.asciidoc
Labels: backport-skip, Request:8.15

#3857 Update APM anomaly known issue re: 8.13.3
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.13, backport-8.14

#3823 Add a new section on how to collect CloudTrail events using Amazon Data Firehose
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudtrail-cloudwatch.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudtrail-dashboard.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudtrail-discover.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudtrail-logsexplorer.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-delivery-stream.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-failed-delivery-stream.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-monitor-cloudtrail-logs.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-subscription-filter.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-verify-events-cloudwatch.png
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-agent.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudtrail-firehose.asciidoc
Labels: docs, enhancement, backport-skip

#3845 Add quick start to Integrations Dev Guide
  docs/en/integrations/images/datastream-log-message.png
  docs/en/integrations/images/package-installed.png
  docs/en/integrations/index.asciidoc
  docs/en/integrations/quick-start.asciidoc
Labels: Team:Docs, backport-8.13, backport-8.14

#3836 Expand contents of Integrations Developer Guide
  docs/en/integrations/build-integration.asciidoc
  docs/en/integrations/images/colors-in-visualizations.png
  docs/en/integrations/images/filter-in-visualization.png
  docs/en/integrations/images/grouping-in-visualizations.png
  docs/en/integrations/images/markdown-grouping.png
  docs/en/integrations/images/rows-in-visualizations.png
  docs/en/integrations/images/titles-in-visualizations.png
  docs/en/integrations/index.asciidoc
  docs/en/integrations/integrations-guidelines.asciidoc
  docs/en/integrations/integrations-tsds-synthetic-source.asciidoc
  docs/en/integrations/what-is-an-integration.asciidoc
Labels: Team:Docs, backport-8.13, backport-8.14

#3867 Fix formatting in topic about logs explorer
  docs/en/observability/monitor-logs.asciidoc
Labels: Area:Logs+, backport-8.12, backport-8.13, backport-8.14

#3792 Add a detailed explanation about the different field definition fields.
  docs/en/integrations/build-integration.asciidoc
Labels: backport-8.13, backport-8.14

#3875 Add additional dev guides
  docs/en/integrations/build-integration.asciidoc
  docs/en/integrations/developer-workflow-fleet.asciidoc
  docs/en/integrations/developer-workflow-import-beat.asciidoc
  docs/en/integrations/developer-workflow-old-bugfix.asciidoc
  docs/en/integrations/developer-workflows.asciidoc
  docs/en/integrations/images/backport_input_step.png
  docs/en/integrations/images/browse_package_commits.png
  docs/en/integrations/images/merge_commit_message.png
  docs/en/integrations/index.asciidoc
Labels: backport-skip

#3876 Update docs about disk usage metrics
  docs/en/observability/images/hosts.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/monitor-infra/host-metrics.asciidoc
Labels: backport-8.14

#3888 github-action: delete opentelemetry workflow
  .github/workflows/opentelemetry.yml
Labels: backport-skip

#3850 Add a new section on how to collect WAF logs using Amazon Data Firehose
  docs/en/observability/cloud-monitoring/aws/images/firehose-waf-logs.png
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-waf-firehose.asciidoc
Labels: docs, enhancement, backport-8.13, backport-8.14

#3871 Add docs about custom threshold alert details page
  docs/en/observability/images/log-threshold-breach.png
  docs/en/observability/index.asciidoc
  docs/en/observability/triage-slo-burn-rate-breaches.asciidoc
  docs/en/observability/triage-threshold-breaches.asciidoc
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport-8.13, backport-8.14

#3879 Add enhanced alerting details to host monitoring docs
  docs/en/observability/images/hosts.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
  docs/en/observability/monitor-infra/host-details-partial.asciidoc
Labels: backport-8.14

#3877 Document the lack of RUM global labels support in aggregations
  docs/en/observability/apm/data-model.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14

#3920 Add docs builder
  .github/CODEOWNERS
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#3921 Update observability-overview.mdx
  docs/en/serverless/observability-overview.mdx
Labels: backport-skip, ci:doc-build

#3922 Revert "Add docs builder"
  .github/CODEOWNERS
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#3928 Remove leading slash from subdirectory
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#3930 Trigger build for testing purposes
  docs/en/serverless/ai-assistant/ai-assistant.mdx
Labels: backport-skip, ci:doc-build

#3934 Remove non-existent traces-apm.rum data stream from 7.x docs
  docs/en/apm-server/data-streams.asciidoc
Labels: backport-7.16

#3935 Update Docsmobile action to fix issues
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#3938 Remove `author_association` check in `co-docs-builder.yml`
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#3931 Update serverless pricing link
  docs/en/serverless/projects/billing.mdx
  docs/en/serverless/transclusion/synthetics/global-managed-paid-for.mdx
Labels: backport-skip, Docset:Serverless, ci:doc-build

#3943 Revert "Enable automatic elastic.co doc builds for internal users (#3…
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#3944 [7.16] Remove non-existent traces-apm.rum data stream from 7.x docs (#3934)
  docs/en/apm-server/data-streams.asciidoc
Labels: backport

#3941 Fix inventory threshold rule preview description
  docs/en/observability/images/inventory-alert.png
  docs/en/observability/inventory-threshold-alert.asciidoc
Labels: backport-7.16, backport-7.17, backport-8.13, backport-8.14

#3939 Add docs about the Hosts metrics tab
  docs/en/observability/images/anomalies-overlay.png
  docs/en/observability/images/hosts-open-in-lens.png
  docs/en/observability/images/logs-overlay.png
  docs/en/observability/images/metadata-overlay.png
  docs/en/observability/images/metrics-overlay.png
  docs/en/observability/images/overview-overlay.png
  docs/en/observability/images/universal-profiling-overlay.png
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
  docs/en/observability/monitor-infra/host-details-partial.asciidoc
Labels: backport-8.14

#3878 add nginx ML module tutorial
  docs/en/observability/monitor-nginx-ml.asciidoc
  docs/en/observability/monitor-nginx.asciidoc
Labels: backport-8.13, backport-8.14

#3906 Add section about AI connector
  docs/en/observability/images/obs-ai-assistant-action-high-cpu.png
  docs/en/observability/images/obs-ai-assistant-action.png
  docs/en/observability/images/obs-ai-assistant-output.png
  docs/en/observability/images/obs-ai-assistant-slack-message.png
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.14

#3956 Fix inventory threshold rule preview description in serverless
  docs/en/serverless/alerting/create-inventory-threshold-alert-rule.mdx
  docs/en/serverless/images/inventory-alert.png
Labels: backport-skip, ci:doc-build

#3957 Add link to published Obs AI Assistant docs
  docs/en/observability/observability-ai-assistant.asciidoc
  docs/en/shared/alerting-connectors.asciidoc
Labels: backport-8.14
