Repository elastic/observability-docs, pull requests merged in 2024-10, with the labels that each got.

#4239 Update docs after migrating from apm integration package to ES apm-data plugin in 8.15
  docs/en/observability/apm/custom-index-template.asciidoc
  docs/en/observability/apm/data-streams.asciidoc
  docs/en/observability/apm/ingest-pipelines.asciidoc
Labels: needs-writer-review, backport-8.15, backport-8.x

#4323 Add screenshot for new build from integrations-backport
  docs/en/integrations/developer-workflow-old-bugfix.asciidoc
  docs/en/integrations/images/build.png
Labels: backport-skip, needs-writer-review

#4083 Fix apm agentcfg api key privileges
  docs/en/observability/apm/access-api-keys.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14, backport-8.15, backport-8.x

#4320 Port #4301 to serverless
  docs/en/serverless/alerting/triage-slo-burn-rate-breaches.mdx
  docs/en/serverless/alerting/triage-threshold-breaches.mdx
  docs/en/serverless/images/log-threshold-breach-alert-history-chart.png
  docs/en/serverless/images/log-threshold-breach-condition-chart.png
  docs/en/serverless/images/log-threshold-breach-log-rate-analysis.png
  docs/en/serverless/images/slo-burn-rate-breach.png
Labels: backport-skip, needs-writer-review, ci:doc-build

#4338 Port #4319 to serverless
  docs/en/serverless/images/synthetics-analyze-individual-monitor-details.png
  docs/en/serverless/synthetics/synthetics-command-reference.mdx
  docs/en/serverless/transclusion/synthetics/configuration/monitor-config-options.mdx
  docs/en/serverless/transclusion/synthetics/reference/lightweight-config/common.mdx
Labels: backport-skip, needs-writer-review, ci:doc-build

#4276 [hosts] Add troubleshooting section with info on hosts detected by APM
  docs/en/observability/images/icons/questionInCircle.svg
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
  docs/en/serverless/infra-monitoring/analyze-hosts.mdx
Labels: ci:doc-build, backport-8.x

#4232 Add all data set types to quality page
  docs/en/observability/images/data-set-quality-overview.png
  docs/en/observability/images/logs-dataset-overview.png
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-monitor-datasets.asciidoc
  docs/en/serverless/monitor-datasets.mdx
  docs/en/serverless/serverless-observability.docnav.json
Labels: needs-writer-review, ci:doc-build, backport-8.x

#4341 [Inventory] Create new Inventory docs
  docs/en/serverless/images/entity-detailed-view.png
  docs/en/serverless/images/inventory-catalog.png
  docs/en/serverless/inventory.mdx
  docs/en/serverless/serverless-observability.docnav.json
Labels: backport-skip, needs-writer-review, ci:doc-build

#4342 [Inventory] Remove the new services inventory docs
  docs/en/serverless/apm/apm-ui-services.mdx
  docs/en/serverless/apm/new-experience-services.mdx
  docs/en/serverless/serverless-observability.docnav.json
Labels: backport-skip, needs-writer-review, ci:doc-build

#4193 [apm] Update APM feature roles docs
  docs/en/apm-server/redirects.asciidoc
  docs/en/observability/apm/configure/advanced-setup/command-reference.asciidoc
  docs/en/observability/apm/security/elastic-stack/feature-roles.asciidoc
  docs/en/observability/apm/security/elastic-stack/index.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: needs-writer-review, backport-8.14, backport-8.15, backport-8.x

#4293 Ports #3975 to serverless
  docs/en/serverless/ai-assistant/ai-assistant.mdx
Labels: backport-skip, needs-writer-review, ci:doc-build

#4200 [APM] Add note about `@custom` component templates
  docs/en/observability/apm/configure/outputs/logstash.asciidoc
Labels: needs-writer-review, backport-8.14, backport-8.15, backport-8.x

#4351 [Synthetics] Add client certificate reference to docs
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/serverless/synthetics/synthetics-configuration.mdx
Labels: needs-writer-review, ci:doc-build, backport-8.15, backport-8.x

#4362 Deprecate the Logs Stream app
  docs/en/observability/index.asciidoc
  docs/en/observability/tail-logs.asciidoc
Labels: backport-8.x

#4371 Update Hosts documentation to reflect GA
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
Labels: docs, needs-writer-review, backport-8.x

#4376 [Hosts docs] Remove the feedback link inline
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
Labels: docs, needs-writer-review, backport-8.x

#4375 profiling: add information around environment variables
  docs/en/observability/index.asciidoc
  docs/en/observability/profiling-advanced-configuration.asciidoc
  docs/en/observability/profiling-envs.asciidoc
  docs/en/observability/profiling-no-kernel-version-check.asciidoc
  docs/en/observability/profiling-probabilistic-profiling.asciidoc
  docs/en/observability/profiling-tag-data-query.asciidoc
Labels: backport-skip, needs-writer-review

#4346 [synthetics] Document Synthetics availability SLI
  docs/en/observability/slo-create.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
  docs/en/serverless/slos/create-an-slo.mdx
  docs/en/serverless/transclusion/synthetics/configuration/monitor-config-options.mdx
Labels: needs-writer-review, backport-8.14, ci:doc-build, backport-8.15, backport-8.x, needs-dev-review

#4300 SLO roles privileges changed
  docs/en/observability/images/slo-es-priv-all.png
  docs/en/observability/images/slo-es-priv-editor.png
  docs/en/observability/images/slo-es-priv-read.png
  docs/en/observability/images/slo-es-priv-viewer.png
  docs/en/observability/slo-privileges.asciidoc
  docs/en/serverless/slos/create-an-slo.mdx
Labels: needs-writer-review, backport-8.x

#4326 AI Assistant docs updates for 8.16
  docs/en/observability/images/ai-assistant-button.png
  docs/en/observability/images/icons/ai-assistant-bw.svg
  docs/en/observability/images/icons/ai-assistant.svg
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.x

#4388 fix(new minor automation) change the location for `mergify` and use `8.x` instead of `main`
  .github/Makefile
Labels: backport-skip, needs-writer-review

#4389 Update links to search connectors docs
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: needs-writer-review, backport-8.16

#4397 Update Sample otelcol config
  docs/en/observability/apm/collect-application-data/open-telemetry/otel-direct.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4384 Add docs for new central log source setting
  docs/en/observability/categorize-logs.asciidoc
  docs/en/observability/configure-logs-sources.asciidoc
  docs/en/observability/explore-logs.asciidoc
  docs/en/observability/inspect-log-anomalies.asciidoc
  docs/en/serverless/logging/view-and-monitor-logs.mdx
Labels: backport-8.x, backport-8.16

#4386 Update metrics and add legacy section
  docs/en/observability/monitor-infra/host-metrics.asciidoc
  docs/en/serverless/infra-monitoring/host-metrics.mdx
Labels: ci:doc-build, backport-8.x, backport-8.16

#4143 O11y AI Assistant - Google Gemini support
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-main, backport-8.x, backport-8.16

#4411 Fix typo in observability-ai-assistant.asciidoc
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: needs-writer-review

#4367 Profiling: fix stack version to profiling version alignment
  docs/en/observability/profiling-get-started.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4412 Port #4143 to serverless
  docs/en/serverless/ai-assistant/ai-assistant.mdx
Labels: backport-skip, ci:doc-build

#4391 ci: fix branch creation and mergify file
  .github/Makefile
  .github/workflows/run-minor-release.yml
Labels: backport-skip, needs-writer-review

#4327 [APM] Adds information on excluding data tiers from searches
  docs/en/observability/apm/view-and-analyze/filter-and-search/cross-cluster-search.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4396 Add disk metrics to list of docker container metrics
  docs/en/observability/images/metrics-overlay-containers.png
  docs/en/observability/monitor-infra/container-details-partial.asciidoc
  docs/en/observability/monitor-infra/container-metrics.asciidoc
  docs/en/serverless/images/metrics-overlay-containers.png
  docs/en/serverless/infra-monitoring/container-metrics.mdx
  docs/en/serverless/transclusion/container-details.mdx
Labels: ci:doc-build, backport-8.x, backport-8.16

#4345 [synthetics] Update monitor status rule docs
  docs/en/observability/images/synthetic-monitor-action-types-each-alert.png
  docs/en/observability/images/synthetic-monitor-action-types-more-options.png
  docs/en/observability/images/synthetic-monitor-action-types-summary.png
  docs/en/observability/images/synthetic-monitor-action-variables.png
  docs/en/observability/images/synthetic-monitor-conditions.png
  docs/en/observability/images/synthetic-monitor-filters.png
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/serverless/alerting/synthetic-monitor-status-alert.mdx
  docs/en/serverless/images/synthetic-monitor-action-types-each-alert.png
  docs/en/serverless/images/synthetic-monitor-action-types-more-options.png
  docs/en/serverless/images/synthetic-monitor-action-types-summary.png
  docs/en/serverless/images/synthetic-monitor-action-variables.png
  docs/en/serverless/images/synthetic-monitor-conditions.png
  docs/en/serverless/images/synthetic-monitor-filters.png
  docs/en/serverless/serverless-observability.docnav.json
Labels: ci:doc-build, backport-8.x, backport-8.16

#4333 [apm] Update APM docs to reflect changes related to the Elasticsearch apm-data plugin
  docs/en/observability/apm/configure/general.asciidoc
  docs/en/observability/apm/configure/outputs/console.asciidoc
  docs/en/observability/apm/configure/outputs/kafka.asciidoc
  docs/en/observability/apm/configure/outputs/logstash.asciidoc
  docs/en/observability/apm/configure/outputs/redis.asciidoc
  docs/en/observability/apm/getting-started-apm/get-started-with-apm-server-binary.asciidoc
  docs/en/observability/apm/getting-started-apm/get-started-with-fleet-apm-server.asciidoc
  docs/en/observability/apm/getting-started-apm/index.asciidoc
  docs/en/observability/apm/images/bin-ov.png
  docs/en/observability/apm/manage-storage/data-streams.asciidoc
  docs/en/observability/apm/manage-storage/ilm-how-to.asciidoc
  docs/en/observability/apm/manage-storage/ingest-pipelines.asciidoc
  docs/en/observability/apm/shared-kibana-endpoint.asciidoc
  docs/en/observability/apm/shared/install-apm-integration-no-internet.asciidoc
  docs/en/observability/apm/troubleshooting/common-problems.asciidoc
  docs/en/observability/apm/upgrading-to-8.x.asciidoc
  docs/en/observability/apm/view-and-analyze/interpret/mobile-session-explorer.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#4418 Document no data settings for custom threshold rule
  docs/en/observability/threshold-alert.asciidoc
Labels: needs-writer-review, backport-8.x, needs-dev-review, backport-8.16

#4366 Align formatting of APM rules with other rules docs
  docs/en/observability/apm-alerts.asciidoc
  docs/en/observability/apm-anomaly-rule.asciidoc
  docs/en/observability/apm-error-count-threshold-rule.asciidoc
  docs/en/observability/apm-failed-transaction-rate-threshold-rule.asciidoc
  docs/en/observability/apm-latency-threshold-rule.asciidoc
  docs/en/observability/apm/act-on-data/alerts.asciidoc
  docs/en/observability/apm/act-on-data/index.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/apm-anomaly-rule-action-variables.png
  docs/en/observability/images/apm-anomaly-rule-filters-conditions.png
  docs/en/observability/images/apm-error-count-rule-action-variables.png
  docs/en/observability/images/apm-error-count-rule-filters-conditions.png
  docs/en/observability/images/apm-failed-transaction-rate-threshold-rule-action-variables.png
  docs/en/observability/images/apm-failed-transaction-rate-threshold-rule-filters-conditions.png
  docs/en/observability/images/apm-latency-threshold-rule-action-variables.png
  docs/en/observability/images/apm-latency-threshold-rule-filters-conditions.png
  docs/en/observability/inventory-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/slo-burn-rate-alert.asciidoc
  docs/en/observability/threshold-alert.asciidoc
  docs/en/observability/uptime-duration-anomaly-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
  docs/en/shared/alerting-and-rules/alerting-connectors.asciidoc
  docs/en/shared/alerting-and-rules/generic-apm-action-frequency.asciidoc
  docs/en/shared/alerting-and-rules/generic-apm-advanced-options.asciidoc
  docs/en/shared/alerting-and-rules/generic-apm-group-by.asciidoc
  docs/en/shared/alerting-and-rules/generic-apm-rule-schedule.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4442 Rename Inventory to Infrastructure Inventory
  docs/en/serverless/images/kubernetes-filter.png
  docs/en/serverless/images/metrics-app.png
  docs/en/serverless/infra-monitoring/view-infrastructure-metrics.mdx
Labels: backport-skip, needs-writer-review, Docset:Serverless, ci:doc-build

#4445 Port #4418 to serverless
  docs/en/serverless/alerting/create-custom-threshold-alert-rule.mdx
Labels: backport-skip, needs-writer-review, ci:doc-build

#4385 Port to serverless: Add Osquery tab to host monitoring page
  docs/en/serverless/images/osquery-overlay.png
  docs/en/serverless/transclusion/host-details.mdx
Labels: backport-skip, needs-writer-review, ci:doc-build

#4438 Port #4341 to stateful docs: Add new page on inventory
  docs/en/observability/apm/images/inventory-catalog.png
  docs/en/observability/apm/images/inventory-entity-detailed-view.png
  docs/en/observability/apm/view-and-analyze/index.asciidoc
  docs/en/observability/apm/view-and-analyze/inventory.asciidoc
Labels: needs-writer-review, Docset:Stateful, backport-8.x, backport-8.16

#4459 APM: add known issue of lazy rollover bug
  docs/en/observability/apm/known-issues.asciidoc
Labels: needs-writer-review, backport-8.15, backport-8.x

#4463 Clean up new APM known issue
  docs/en/observability/apm/known-issues.asciidoc
Labels: needs-writer-review, backport-8.15, backport-8.x
