Repository elastic/observability-docs, pull requests merged in 2024-06, with the labels that each got.

#3932 profiling: add tips for kubernetes self-managed deployment
  docs/en/observability/profiling-self-managed-ops.asciidoc
Labels: backport-skip, Request:8.15

#3914 add set_es_document_id parameter in doc and fix es_datastream_name
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose.asciidoc
Labels: backport-skip

#3964 Fix nginx ML tutorial heading
  docs/en/observability/monitor-nginx-ml.asciidoc
Labels: backport-8.13, backport-8.14

#3969 Update co-docs-builder.yml to fix wordlake builds
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#3971 Update observability-overview.mdx to force a build
  docs/en/serverless/observability-overview.mdx
Labels: backport-skip, ci:doc-build

#3962 [Serverless] Add new connectors to alerting action list
  docs/en/serverless/alerting/alerting-connectors.mdx
Labels: backport-skip, ci:doc-build

#3791 [Azure docs] Add Azure monitoring docs
  docs/en/observability/cloud-monitoring/azure/monitor-azure-agent.asciidoc
  docs/en/observability/cloud-monitoring/azure/monitor-azure-beats.asciidoc
  docs/en/observability/cloud-monitoring/azure/monitor-azure-intro.asciidoc
  docs/en/observability/cloud-monitoring/azure/monitor-azure-native.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: docs, backport-8.13, backport-8.14, ci:doc-build

#3885 Add a new section on how to collect AWS Network Firewall using Firehose
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudwatch-log-events.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-networkfirewall-data-stream.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-networkfirewall-discover.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-networkfirewall-firewall.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-networkfirewall-logging.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-networkfirewall-stream.png
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firewall-firehose.asciidoc
Labels: docs, enhancement, backport-8.13, backport-8.14

#3887 Add a new section on how to collect any log from CloudWatch using Firehose
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudwatch-data-stream.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudwatch-destination-errors.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudwatch-firehose-stream.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudwatch-log-group.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudwatch-sample-logs.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudwatch-subscription-filter.png
  docs/en/observability/cloud-monitoring/aws/images/firehose-cloudwatch-verify-discover.png
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudwatch-firehose.asciidoc
Labels: docs, enhancement, backport-8.13, backport-8.14

#3985 Add license
  LICENSE
  README.md
Labels: backport-7.17, backport-8.14

#3986 Add smart fields section to stateful docs
  docs/en/observability/explore-logs.asciidoc
  docs/en/observability/images/apmTrace-icon.png
  docs/en/observability/images/expand-icon.png
  docs/en/observability/images/pagesSelect-icon.png
Labels: backport-8.14

#3955 Add docs about the Hosts metrics tab to serverless
  docs/en/serverless/images/anomalies-overlay.png
  docs/en/serverless/images/hosts-open-in-lens.png
  docs/en/serverless/images/logs-overlay.png
  docs/en/serverless/images/metadata-overlay.png
  docs/en/serverless/images/metrics-overlay.png
  docs/en/serverless/images/overview-overlay.png
  docs/en/serverless/infra-monitoring/analyze-hosts.mdx
  docs/en/serverless/transclusion/host-details.mdx
Labels: backport-skip, ci:doc-build

#3958 Add section about AI connector to serverless
  docs/en/observability/observability-ai-assistant.asciidoc
  docs/en/serverless/ai-assistant/ai-assistant.mdx
  docs/en/serverless/images/obs-ai-assistant-action-high-cpu.png
  docs/en/serverless/images/obs-ai-assistant-action.png
  docs/en/serverless/images/obs-ai-assistant-output.png
  docs/en/serverless/images/obs-ai-assistant-slack-message.png
Labels: backport-skip, ci:doc-build

#3991 Fix AWS Firehose documentation
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose.asciidoc
Labels: backport-8.13, backport-8.14

#3978 [DO NOT MERGE] Update publish_docs_co.yml to point to elastic.co/docs
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#4004 Update what-is-observability-serverless.mdx to force a build
  docs/en/serverless/what-is-observability-serverless.mdx
Labels: backport-skip, ci:doc-build

#4006 github-actions: use github secrets
  .github/workflows/run-minor-release.yml
Labels: backport-skip

#4007 Remove unneed code marking in monitor-amazon-sqs section
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-sqs.asciidoc
Labels: backport-8.13

#3989 Remove the `ecs.yml` section
  docs/en/integrations/build-integration.asciidoc
Labels: docs, backport-8.13, backport-8.14

#3982 profiling on-prem: fix kubernetes secret instructions
  docs/en/observability/profiling-self-managed-ops.asciidoc
Labels: backport-skip, Request:8.15

#3916 Delete serverless directory on backport PRs
  .github/workflows/delete-serverless-dir-on-backports.yml
  README.md
Labels: backport-7.17, needs-writer-review, backport-8.13, backport-8.14

#3953 Clarify descriptions of APM indicators for SLOs
  docs/en/observability/slo-create.asciidoc
  docs/en/serverless/slos/create-an-slo.mdx
Labels: backport-8.13, backport-8.14, ci:doc-build

#4009 [main] Update monitor-amazon-sqs.asciidoc (#4007)
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-sqs.asciidoc
Labels: backport, needs-writer-review

#4019 Clarify index used in SLO privileges example
  docs/en/observability/slo-privileges.asciidoc
Labels: backport-8.13, backport-8.14

#4022 Add nginx tutorial to navigation
  docs/en/observability/tutorials.asciidoc
Labels: backport-8.13, backport-8.14

#4030 Remove BETA mention from UP
  docs/en/observability/observability-introduction.asciidoc
Labels: backport-8.9, backport-8.10, backport-8.11, backport-8.12, backport-8.13, backport-8.14

#4042 Update the Azure OpenAI docs to include example app updates
  docs/en/observability/cloud-monitoring/azure/monitor-azure-openai-apm.asciidoc
Labels: backport-8.14
