Repository elastic/observability-docs, pull requests merged in 2024-07, with the labels that each got.

#4041 Profiling: Drop known issues section about no longer supported versions
  docs/en/observability/profiling-get-started.asciidoc
Labels: backport-skip

#3960 Create log data set monitoring docs
  docs/en/serverless/images/green-dot-icon.png
  docs/en/serverless/images/logs-dataset-overview.png
  docs/en/serverless/images/red-dot-icon.png
  docs/en/serverless/images/yellow-dot-icon.png
  docs/en/serverless/logging/log-monitoring.mdx
  docs/en/serverless/logging/monitor-datasets.mdx
  docs/en/serverless/logging/view-and-monitor-logs.mdx
  docs/en/serverless/serverless-observability.docnav.json
Labels: backport-skip, ci:doc-build

#4046 Add metrics support for firehose into documentation
  docs/en/observability/cloud-monitoring/aws/ingest-aws-options.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose.asciidoc
Labels: backport-8.14

#4051 Update .mergify.yml (add 8.15)
  .mergify.yml
Labels: backport-skip

#4050 Remove unused callout
  docs/en/observability/logs-filter.asciidoc
Labels: backport-8.14, backport-8.15

#4049 Add Observability case templates
  docs/en/observability/create-cases.asciidoc
  docs/en/observability/images/cases-custom-field-settings.png
  docs/en/observability/manage-cases.asciidoc
Labels: backport-8.15

#4063 [Monitor AWS with Firehose] Change file name
  docs/en/observability/cloud-monitoring/aws/ingest-aws-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudtrail-firehose.asciidoc
Labels: docs, backport-8.15

#4072 Add case templates in serverless Observability docs
  docs/en/serverless/alerting/alerting.mdx
  docs/en/serverless/cases/cases.mdx
  docs/en/serverless/cases/create-manage-cases.mdx
  docs/en/serverless/cases/manage-cases-settings.mdx
  docs/en/serverless/images/cases-add-connector.png
  docs/en/serverless/images/cases.png
  docs/en/serverless/images/observability-cases-add-connector.png
  docs/en/serverless/images/observability-cases-settings.png
  docs/en/serverless/images/observability-cases-templates.png
  docs/en/serverless/serverless-observability.docnav.json
Labels: backport-skip, Docset:Serverless, ci:doc-build

#4069 Restructure case settings page
  docs/en/observability/images/cases-settings.png
  docs/en/observability/index.asciidoc
  docs/en/observability/manage-cases-settings.asciidoc
  docs/en/observability/manage-cases.asciidoc
Labels: backport-8.15

#4071 Add note about Logs Stream
  docs/en/observability/logs-checklist.asciidoc
  docs/en/observability/monitor-logs.asciidoc
  docs/en/observability/tail-logs.asciidoc
Labels: backport-8.15

#4077 [DOCS] Remove obsolete section
  docs/en/observability/manage-cases.asciidoc
Labels: backport-skip

#4066 Add deprecation note for Uptime
  docs/en/observability/uptime-intro.asciidoc
Labels: backport-8.15

#4047 APM known issues: Too many small bulk requests
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.13, backport-8.14, backport-8.15

#4067 Add data set quality docs to stateful
  docs/en/observability/explore-logs.asciidoc
  docs/en/observability/images/green-dot-icon.png
  docs/en/observability/images/logs-dataset-overview.png
  docs/en/observability/images/red-dot-icon.png
  docs/en/observability/images/yellow-dot-icon.png
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-monitor-datasets.asciidoc
  docs/en/serverless/logging/monitor-datasets.mdx
  docs/en/serverless/logging/view-and-monitor-logs.mdx
Labels: ci:doc-build, backport-8.15

#4054 Create docs for adding the service name field to logs
  docs/en/serverless/images/add-field-processor.png
  docs/en/serverless/logging/add-logs-service-name.mdx
  docs/en/serverless/serverless-observability.docnav.json
Labels: backport-skip, ci:doc-build

#4062 Add docs about EEM and new Services inventory
  docs/en/serverless/apm/apm-ui-services.mdx
  docs/en/serverless/apm/new-experience-services.mdx
  docs/en/serverless/elastic-entity-model.mdx
  docs/en/serverless/images/entity-centric-services-inventory.png
  docs/en/serverless/serverless-observability.docnav.json
Labels: backport-skip, ci:doc-build

#4092 docs/otel-direct: add Python specific requirements
  docs/en/observability/apm/otel-direct.asciidoc
Labels: backport-skip

#4095 docs/otel-direct: fix code snippet rendering in table
  docs/en/observability/apm/otel-direct.asciidoc
Labels: backport-skip

#4098 docs/otel-direct: refine python specific paragraph
  docs/en/observability/apm/otel-direct.asciidoc
Labels: backport-skip
