Repository elastic/observability-docs, pull requests merged in 2024-04, with the labels that each got.

#3713 Add apm prefixed redirects
  docs/en/observability/redirects.asciidoc
Labels: backport-8.13

#3716 Clarify AI Assistant docs about model training
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.10, backport-8.11, backport-8.12, backport-8.13

#3684 AWS ingest and monitoring doc redesign
  docs/en/aws-firehose/aws-firehose-setup.asciidoc
  docs/en/observability/cloud-monitoring/aws/images/discover-destination-port.png
  docs/en/observability/cloud-monitoring/aws/images/discover-ip-addresses.png
  docs/en/observability/cloud-monitoring/aws/images/discover-visualize-chart.png
  docs/en/observability/cloud-monitoring/aws/images/flow-log-dashboard.png
  docs/en/observability/cloud-monitoring/aws/images/ingest-options-overview.png
  docs/en/observability/cloud-monitoring/aws/images/ml-anomalies-detection.png
  docs/en/observability/cloud-monitoring/aws/images/ml-anomalies-explorer.png
  docs/en/observability/cloud-monitoring/aws/images/ml-anomalies-results.png
  docs/en/observability/cloud-monitoring/aws/images/ml-spike.png
  docs/en/observability/cloud-monitoring/aws/ingest-aws-options.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-agent.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-beats.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-esf.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-vpc-flow-logs.asciidoc
  docs/en/observability/redirects.asciidoc
  docs/en/observability/tutorials.asciidoc
Labels: docs, Team:Docs, backport-skip

#3728 improve synthetics push command flow docs
  docs/en/observability/synthetics-command-reference.asciidoc
Labels: backport-8.13

#3731 Fix typos
  docs/en/observability/apm/api-events.asciidoc
  docs/en/observability/apm/sampling.asciidoc
Labels: backport-8.12, backport-8.13

#3725 profiling: improve self-managed section
  docs/en/observability/profiling-self-managed.asciidoc
Labels: Request:8.13, backport-8.13

#3676 Add rate and percentile aggregations to docs for custom threshold rule
  docs/en/observability/aggregation-options.asciidoc
  docs/en/observability/images/alerts-rate-aggregation.png
  docs/en/observability/index.asciidoc
  docs/en/observability/metrics-threshold-alert.asciidoc
  docs/en/observability/rate-aggregations.asciidoc
  docs/en/observability/threshold-alert.asciidoc
Labels: backport-8.13

#3738 Add limit for number of alerts per case
  docs/en/observability/view-observability-alerts.asciidoc
Labels: backport-8.13

#3740 QA fix: Update 'Add agent' screenshot
  docs/en/observability/images/kibana-agent-flyout.png
Labels: backport-skip

#3744 QA fix: Kibana home page screenshot
  docs/en/observability/images/kibana-home.png
Labels: backport-8.13

#3730 Add APM data stream rerouting docs
  docs/en/observability/apm/data-streams.asciidoc
  docs/en/observability/apm/ingest-pipelines.asciidoc
Labels: backport-8.12, backport-8.13

#3750 Add the Firehose troubleshooting section to the new AWS monitoring docs
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose-troubleshooting.asciidoc
Labels: docs, backport-8.13

#3758 Fix numbering in AWS monitoring docs
  docs/en/observability/cloud-monitoring/aws/monitor-aws-esf.asciidoc
Labels: backport-8.13

#3752 docs: remove false deprecation note for standalone apm-server
  docs/en/observability/apm/upgrading-to-8.x.asciidoc
Labels: backport-8.9, backport-8.1, backport-8.2, backport-8.0, backport-8.4, backport-8.5, backport-8.6, backport-8.7, backport-8.8, backport-8.3, backport-8.10, backport-8.11, backport-8.12, backport-8.13

#3757 Complete the explanation for the files in the integration field directory
  docs/en/integrations/build-integration.asciidoc
Labels: backport-8.13

#3795 Update logs navigation
  docs/en/observability/images/log-explorer.png
  docs/en/observability/logs-checklist.asciidoc
  docs/en/observability/monitor-logs.asciidoc
Labels: backport-8.13

#3798 Add APM anomaly rule known issue
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.13

#3799 Update logs-threshold-alert.asciidoc
  docs/en/observability/logs-threshold-alert.asciidoc
Labels: backport-8.12, backport-8.13

#3805 github-action(release automation): reviewers and use codeowners insteads
  .github/Makefile
Labels: backport-skip

#3753 dependabot: keep github actions up-to-date
  .github/dependabot.yml
Labels: backport-skip

#3810 Fixes known-issues: adds missing header, adds UI instructions
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.13

#3804 [Release] Add backport-8.14
  .mergify.yml
Labels: backport-skip

#3814 Add DeDe’s serverless suggestions
  docs/en/observability/synthetics-command-reference.asciidoc
Labels: backport-8.13, backport-8.14

#3803 profiling: add .Net to supported interpreters
  docs/en/observability/profiling-get-started.asciidoc
Labels: Request:8.14, backport-8.14

#3820 Add missing period
  docs/en/observability/monitor-k8s/monitor-k8s-explore-logs-and-metrics.asciidoc
Labels: backport-8.13, backport-8.14

#3797 Document workflow for uploading custom integrations and enabling agentless support
  docs/en/integrations/build-integration.asciidoc
  docs/en/integrations/elastic-package.asciidoc
  docs/en/integrations/index.asciidoc
  docs/en/integrations/upload-integration.asciidoc
Labels: backport-skip

#3818 AWS Tutorial - remove screenshots and adjust text accordingly
  docs/en/observability/cloud-monitoring/aws/monitor-aws-agent.asciidoc
  docs/en/observability/images/agent-tut-aws-credentials.png
  docs/en/observability/images/agent-tut-collect-billing-metrics.png
  docs/en/observability/images/agent-tut-collect-ec2-metrics.png
  docs/en/observability/images/agent-tut-config-vpc-logs.png
  docs/en/observability/images/agent-tut-configure-event-notification.png
  docs/en/observability/images/agent-tut-configure-notification-output.png
  docs/en/observability/images/agent-tut-create-s3-bucket.png
  docs/en/observability/images/agent-tut-creating-a-queue.png
  docs/en/observability/images/agent-tut-enable-server-access-logging.png
  docs/en/observability/images/agent-tut-s3access-logs.png
Labels: docs, backport-skip

#3827 Remove Claude 3.0 restriction
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.14

#3834 Add link to workaround about using custom CAs in private locations
  docs/en/observability/synthetics-private-location.asciidoc
Labels: backport-8.13, backport-8.14

#3832 Update slo-overview.asciidoc
  docs/en/observability/slo-overview.asciidoc
Labels: backport-8.13, backport-8.14
