Repository elastic/observability-docs, pull requests merged in 2024-01, with the labels that each got.

#3449 Update the Logs resource guide
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-checklist.asciidoc
  docs/en/observability/logs-overview.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: backport-8.12

#3504 [Cases] Add new sub feature privilege to prevent access to case settings
  docs/en/observability/grant-cases-access.asciidoc
Labels: backport-8.12

#3503 Add SLO dashboard panel docs
  docs/en/observability/images/slo-dashboard-panel.png
  docs/en/observability/slo-overview.asciidoc
Labels: backport-8.12

#3502 Promote Custom Threshold Rule to Beta
  docs/en/observability/images/custom-threshold-rule.png
  docs/en/observability/threshold-alert.asciidoc
Labels: backport-8.12

#3509 Sync Stateful SLO docs with Serverless
  docs/en/observability/slo-overview.asciidoc
Labels: backport-8.12

#3514 Explain how to upgrade SLOs out of beta
  docs/en/observability/slo-overview.asciidoc
Labels: backport-8.12

#3517 Hosts: Add service name filter to filter list
  docs/en/observability/images/hosts.png
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
Labels: backport-8.12

#3518 Modernise OpenTelemetry Collector example config
  docs/en/observability/apm/otel-direct.asciidoc
Labels: backport-8.12

#3523 [Cases] Copy file hashes
  docs/en/observability/images/case-files.png
  docs/en/observability/manage-cases.asciidoc
Labels: backport-8.12

#3532 [apm] Add more redirects
  docs/en/apm-server/redirects.asciidoc
Labels: backport-8.12

#3536 [apm docs consolidation] Copy recent /apm-server docs edits
  docs/en/observability/apm/apm-k8s-attacher.asciidoc
  docs/en/observability/apm/features.asciidoc
  docs/en/observability/apm/getting-started-apm-server.asciidoc
  docs/en/observability/apm/known-issues.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: backport-8.12

#3507 [apm] Update content related to mobile APM agents for GA
  docs/en/observability/apm/agent-server-compatibility.asciidoc
  docs/en/observability/apm/anonymous-auth.asciidoc
  docs/en/observability/apm/api-keys.asciidoc
  docs/en/observability/apm/apm-server-down.asciidoc
  docs/en/observability/apm/configure/anonymous-auth.asciidoc
  docs/en/observability/apm/data-model.asciidoc
  docs/en/observability/apm/getting-started-apm-server.asciidoc
  docs/en/observability/apm/release-notes.asciidoc
  docs/en/observability/apm/secret-token.asciidoc
  docs/en/observability/apm/tab-widgets/distributed-trace-receive-widget.asciidoc
  docs/en/observability/apm/tab-widgets/distributed-trace-receive.asciidoc
  docs/en/observability/apm/tab-widgets/distributed-trace-send-widget.asciidoc
  docs/en/observability/apm/tab-widgets/distributed-trace-send.asciidoc
  docs/en/observability/apm/tab-widgets/install-agents-widget.asciidoc
  docs/en/observability/apm/tab-widgets/install-agents.asciidoc
  docs/en/observability/apm/troubleshoot-apm.asciidoc
  docs/en/observability/apm/version.asciidoc
Labels: backport-8.12

#3531 [RUM] Remove FID and add INP
  docs/en/observability/exploratory-data-visualizations.asciidoc
  docs/en/observability/images/obs-overview-ue.png
  docs/en/observability/images/user-exp-metrics.png
  docs/en/observability/images/user-experience-tab.png
  docs/en/observability/images/web-dev-vitals.png
  docs/en/observability/user-experience.asciidoc
Labels: backport-8.12

#3535 automation: update reviewers and refactor
  .github/Makefile
  .github/workflows/run-minor-release.yml
Labels: backport-skip

#3512 [ai assistant] Update product status for 8.12, add known issues
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.12

#3547 Remove tech preview from K8s attacher
  docs/en/observability/apm/apm-k8s-attacher.asciidoc
Labels: backport-8.12

#3527 Add Universal Profiling to the Hosts docs
  docs/en/observability/explore-logs.asciidoc
  docs/en/observability/images/universal-profiling-overlay.png
  docs/en/observability/monitor-infra/host-details-partial.asciidoc
Labels: backport-8.12

#3529 Update whats-new.asciidoc
  docs/en/observability/whats-new.asciidoc
Labels: backport-skip

#3554 Remove unused APM attributes
  docs/en/observability/apm.asciidoc
  docs/en/observability/apm/version.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.10, backport-8.11, backport-8.12

#3568 Update getting-started-apm-server.asciidoc
  docs/en/observability/apm/getting-started-apm-server.asciidoc
Labels: backport-8.11, backport-8.12

#3379 profiling: introduce self-managed beta for 8.12
  docs/en/observability/images/profiling-self-managed-ingestion-architecture.png
  docs/en/observability/index.asciidoc
  docs/en/observability/profiling-self-managed-ops.asciidoc
  docs/en/observability/profiling-self-managed-troubleshooting.asciidoc
  docs/en/observability/profiling-self-managed.asciidoc
  docs/en/observability/profiling-troubleshooting.asciidoc
Labels: backport-skip, Request:8.13

#3574 Update stateful Obs docs to fix problems found during serverless testing
  docs/en/observability/apm/aws-lambda-extension.asciidoc
  docs/en/observability/apm/open-telemetry.asciidoc
  docs/en/observability/apm/otel-attrs.asciidoc
Labels: backport-8.12

#3579 [Logs] Update the location of the Elasticsearch host
  docs/en/observability/images/es-endpoint-cluster-id.png
  docs/en/observability/images/help-icon.png
  docs/en/observability/logs-ecs-application.asciidoc
  docs/en/observability/logs-plaintext.asciidoc
  docs/en/observability/logs-stream.asciidoc
  docs/en/observability/logs-troubleshooting.asciidoc
Labels: backport-8.12

#3583 github(action): enable CI/CD observability with Opentelemetry
  .github/workflows/opentelemetry.yml
Labels: backport-skip
