Repository elastic/observability-docs, pull requests merged in 2024-02, with the labels that each got.

#3592 A potpourri of enhancements
  docs/en/aws-firehose/aws-firehose-troubleshooting.asciidoc
  docs/en/observability/apm/configure/instrumentation.asciidoc
  docs/en/observability/apm/configure/outputs/logstash.asciidoc
  docs/en/observability/apm/configure/outputs/redis.asciidoc
  docs/en/observability/apm/data-streams.asciidoc
  docs/en/observability/apm/getting-started-apm-server.asciidoc
  docs/en/observability/apm/log-correlation.asciidoc
  docs/en/observability/apm/open-telemetry.asciidoc
  docs/en/observability/apm/otel-direct.asciidoc
  docs/en/observability/apm/release-notes.asciidoc
  docs/en/observability/apm/secret-token.asciidoc
  docs/en/observability/apm/secure-comms.asciidoc
  docs/en/observability/apm/shared-ssl-logstash-config.asciidoc
  docs/en/observability/apm/troubleshoot-apm.asciidoc
  docs/en/observability/apm/upgrading-to-8.x.asciidoc
  docs/en/observability/apm/version.asciidoc
  docs/en/observability/landing-page/data/recommended-data.json
  docs/en/observability/landing-page/data/related-docs-data.json
  docs/en/observability/landing-page/page.asciidoc
  docs/en/observability/monitor-azure-native.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/observability/redirects.asciidoc
  docs/en/observability/traces-get-started.asciidoc
  docs/en/observability/universal-profiling.asciidoc
  docs/en/observability/user-experience.asciidoc
  docs/en/shared/configure-apm-server/content.asciidoc
Labels: backport-8.12

#3597 apm: add 8.12.0 known issue about fleet ingest pipeline bug
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.12

#3591 [apm] Add docs on a known issue with APM Server + APM Java agent
  docs/en/observability/apm/agent-server-compatibility.asciidoc
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.11, backport-8.12

#3601 Update and rename doc-preview.yml to docs-preview.yml
  .github/workflows/doc-preview.yml
  .github/workflows/docs-preview.yml
Labels: backport-skip

#3588 Remove outdated log correlation docs
  docs/en/apm-server/redirects.asciidoc
  docs/en/observability/apm/log-correlation.asciidoc
  docs/en/observability/logs-plaintext.asciidoc
Labels: backport-8.12

#3607 Add allow_restricted_indices to agentcfg privileges
  docs/en/observability/apm/feature-roles.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.10, backport-8.11, backport-8.12

#3606 Fix OTLP header ApiKey casing
  docs/en/observability/apm/otel-direct.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.10, backport-8.11, backport-8.12

#3608 Make custom threshold rule GA in the docs
  docs/en/observability/threshold-alert.asciidoc
Labels: backport-skip

#3621 ci: grant permissions and set the secret to create the minor branch
  .github/workflows/run-minor-release.yml
Labels: backport-skip

#3605 Add missing ServiceNow connectors to list in alerting docs
  docs/en/observability/create-alerts.asciidoc
Labels: backport-8.12, backport-8.13

#3599 profiling: use Universal Profiling Agent consistently
  docs/en/observability/profiling-advanced-configuration.asciidoc
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-no-kernel-version-check.asciidoc
  docs/en/observability/profiling-self-managed-ops.asciidoc
  docs/en/observability/profiling-self-managed-troubleshooting.asciidoc
  docs/en/observability/profiling-self-managed.asciidoc
  docs/en/observability/profiling-tag-data-query.asciidoc
  docs/en/observability/profiling-troubleshooting.asciidoc
  docs/en/observability/profiling-upgrade.asciidoc
  docs/en/observability/profiling-use-a-proxy.asciidoc
Labels: Request:8.13, backport-8.13

#3625 mergify: add 8.13 backport automation
  .mergify.yml
Labels: backport-skip

#3593 Create a logs@custom index template reference
  docs/en/observability/index.asciidoc
  docs/en/observability/logs-checklist.asciidoc
  docs/en/observability/logs-index-template.asciidoc
Labels: backport-8.12

#3604 Add docs about timeslice SLI
  docs/en/observability/slo-create.asciidoc
Labels: v8.12.0, backport-8.12, backport-8.13

#3634 Update logs component templates in Parse logs docs
  docs/en/observability/logs-parse.asciidoc
Labels: backport-8.12, backport-8.13

#3641 Update the Logs Checklist headings
  docs/en/observability/logs-checklist.asciidoc
Labels: backport-8.12, backport-8.13
