Repository elastic/observability-docs, pull requests merged in 2024-09, with the labels that each got.

#4186 Update infrastructure monitoring docs about containers
  docs/en/observability/images/logs-overlay-containers.png
  docs/en/observability/images/metadata-overlay-containers.png
  docs/en/observability/images/metrics-overlay-containers.png
  docs/en/observability/images/overview-overlay-containers.png
  docs/en/observability/monitor-infra/container-details-partial.asciidoc
  docs/en/observability/monitor-infra/container-metrics.asciidoc
  docs/en/observability/monitor-infra/docker-container-metrics.asciidoc
  docs/en/observability/monitor-infra/metrics-reference.asciidoc
  docs/en/observability/monitor-infra/view-infrastructure-metrics.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: backport-8.15

#4187 [Host metrics] Add field calculation to serverless docs
  docs/en/serverless/infra-monitoring/host-metrics.mdx
Labels: docs, serverless-docs, backport-8.14, ci:doc-build, backport-8.15

#4210 [apm serverless] Add examples using `trace_continuation_strategy` to sampling docs
  docs/en/serverless/apm/apm-transaction-sampling.mdx
  docs/en/serverless/images/apm-dt-sampling-continuation-strategy-restart.png
  docs/en/serverless/images/apm-dt-sampling-continuation-strategy-restart_external.png
  docs/en/serverless/images/apm-dt-sampling-example-1.png
  docs/en/serverless/images/apm-dt-sampling-example-2.png
Labels: backport-skip, ci:doc-build

#4192 [apm/known_issues] Add known issues for ILM to DSL switch
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.15

#4220 [apm] Remove preview badge from EDOT Java
  docs/en/observability/apm/open-telemetry.asciidoc
Labels: backport-8.15

#4218 [apm] Add headings to APM known issues page
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.14, backport-8.15

#4134 Create new IA for observability docs
  docs/en/apm-server/redirects.asciidoc
  docs/en/observability/apm-ui/new-experience-services.asciidoc
  docs/en/observability/apm.asciidoc
  docs/en/observability/apm/apm-quick-start.asciidoc
  docs/en/observability/apm/getting-started-apm-server.asciidoc
  docs/en/observability/apm/setting-up-and-running.asciidoc
  docs/en/observability/application-and-service-monitoring.asciidoc
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/cloud-monitoring.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-ec2.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-kinesis.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-s3.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-amazon-sqs.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-agent.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudtrail-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudwatch-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firewall-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-vpc-flow-logs.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-waf-firehose.asciidoc
  docs/en/observability/cloud-monitoring/azure/monitor-azure-agent.asciidoc
  docs/en/observability/cloud-monitoring/azure/monitor-azure-intro.asciidoc
  docs/en/observability/cloud-monitoring/azure/monitor-azure-native.asciidoc
  docs/en/observability/fields-reference.asciidoc
  docs/en/observability/gcp-dataflow.asciidoc
  docs/en/observability/incident-management.asciidoc
  docs/en/observability/index.asciidoc
  docs/en/observability/landing-page/data/recommended-data.json
  docs/en/observability/landing-page/page.asciidoc
  docs/en/observability/logs-checklist.asciidoc
  docs/en/observability/logs-metrics-get-started.asciidoc
  docs/en/observability/monitor-gcp.asciidoc
  docs/en/observability/monitor-infra/infrastructure-and-host-monitoring-intro.asciidoc
  docs/en/observability/monitor-infra/monitor-infrastructure-and-hosts.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s.asciidoc
  docs/en/observability/monitor-nginx.asciidoc
  docs/en/observability/observability-get-started.asciidoc
  docs/en/observability/quickstarts/monitor-hosts-with-elastic-agent.asciidoc
  docs/en/observability/quickstarts/monitor-k8s-logs-metrics.asciidoc
  docs/en/observability/quickstarts/quickstarts-overview.asciidoc
  docs/en/observability/redirects.asciidoc
  docs/en/observability/splunk-get-started.asciidoc
  docs/en/observability/traces-get-started.asciidoc
  docs/en/observability/tutorials.asciidoc
  docs/en/observability/universal-profiling.asciidoc
  docs/en/observability/uptime-get-started-heartbeat.asciidoc
  docs/en/observability/uptime-intro.asciidoc
Labels: backport-skip

#4226 Fix formatting for APM known issues doc
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.15

#4225 Port #4186 to serverless
  docs/en/serverless/images/logs-overlay-containers.png
  docs/en/serverless/images/metadata-overlay-containers.png
  docs/en/serverless/images/metrics-overlay-containers.png
  docs/en/serverless/images/overview-overlay-containers.png
  docs/en/serverless/infra-monitoring/analyze-hosts.mdx
  docs/en/serverless/infra-monitoring/container-metrics.mdx
  docs/en/serverless/infra-monitoring/docker-container-metrics.mdx
  docs/en/serverless/infra-monitoring/metrics-reference.mdx
  docs/en/serverless/infra-monitoring/view-infrastructure-metrics.mdx
  docs/en/serverless/serverless-observability.docnav.json
  docs/en/serverless/transclusion/container-details.mdx
Labels: backport-skip, serverless-docs, ci:doc-build

#4228 Update 'hide_in_deployment_modes' example to use filestream
  docs/en/integrations/build-integration.asciidoc
Labels: backport-skip

#4240 Fix typo in reroute
  docs/en/observability/apm/ingest-pipelines.asciidoc
Labels: backport-8.13, backport-8.14, backport-8.15

#4247 Remove mention of new experience
  docs/en/observability/logs-add-service-name.asciidoc
  docs/en/serverless/logging/add-logs-service-name.mdx
Labels: ci:doc-build, backport-8.15

#4251 Update .mergify.yml
  .mergify.yml
Labels: backport-skip

#4252 Remove technical preview badge for otel java
  docs/en/serverless/apm-agents/apm-agents-opentelemetry.mdx
Labels: backport-skip, ci:doc-build

#4246 [Observability docs] Change 'beats' namespace to 'elastic-agent'
  docs/en/integrations/developer-workflow-fleet.asciidoc
  docs/en/observability/synthetics-private-location.asciidoc
  docs/en/serverless/synthetics/synthetics-private-location.mdx
Labels: backport-8.15, backport-8.x

#4211 [Observability AI Assistant] Add explicit text about function calling
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: docs, backport-8.15, backport-8.x

#4242 [APM] Remove limitation about host metrics in otel docs
  docs/en/observability/apm/otel-limitations.asciidoc
Labels: backport-8.15, backport-8.x

#4234 Update synthetics-private-location.asciidoc
  docs/en/observability/synthetics-private-location.asciidoc
Labels: docs, backport-main, backport-8.x

#4266 [Hosts documentation] Remove callout for beta
  docs/en/serverless/infra-monitoring/analyze-hosts.mdx
Labels: backport-skip, Docset:Serverless, ci:doc-build

#4268 Port #4211 to serverless
  docs/en/serverless/ai-assistant/ai-assistant.mdx
Labels: backport-skip, serverless-docs, ci:doc-build

#4270 [apm/otel] Remove limitation about host metrics in OTel docs
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-limitations.mdx
Labels: backport-skip, ci:doc-build

#4269 [apm/otel] Add links to Elastic Distribution of OpenTelemetry PHP
  docs/en/observability/apm/open-telemetry.asciidoc
  docs/en/serverless/apm-agents/apm-agents-opentelemetry.mdx
Labels: ci:doc-build, backport-8.15, backport-8.x

#4277 Add ESS to quickstart prereqs
  docs/en/observability/quickstarts/monitor-hosts-with-elastic-agent.asciidoc
  docs/en/observability/quickstarts/monitor-k8s-logs-metrics.asciidoc
Labels: backport-8.x

#4282 [serverless] Add preq to quickstarts
  docs/en/serverless/quickstarts/k8s-logs-metrics.mdx
  docs/en/serverless/quickstarts/monitor-hosts-with-elastic-agent.mdx
Labels: backport-skip, ci:doc-build

#4198 [APM] Document which fields are supported to create APM Service Groups
  docs/en/observability/apm-ui/services.asciidoc
Labels: backport-8.14, backport-8.15, backport-8.x

#4287 [serverless] Remove note, add list of dimensions
  docs/en/serverless/apm/apm-ui-services.mdx
Labels: backport-skip, ci:doc-build

#4281 Add limitations to EEM docs
  docs/en/observability/elastic-entity-model.asciidoc
  docs/en/serverless/elastic-entity-model.mdx
Labels: needs-writer-review, backport-8.x

#4290 Update status to assign to prs
  .github/workflows/add-pr-to-project.yml
Labels: backport-skip, needs-writer-review

#4288 [serverless] Add note about elastic-agent-complete
  docs/en/serverless/synthetics/synthetics-private-location.mdx
Labels: backport-skip, ci:doc-build

#4278 First draft of PR template
  .github/pull_request_template.md
Labels: backport-skip, needs-writer-review

#4298 Port #4130 to serverless
  docs/en/serverless/ai-assistant/ai-assistant.mdx
Labels: backport-skip, needs-writer-review, ci:doc-build

#4297 Port #4201 to serverless
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-opentelemetry-native-support.mdx
Labels: backport-skip, needs-writer-review, ci:doc-build

#4302 Update versions in our issue template
  .github/ISSUE_TEMPLATE/elastic-request.yaml
Labels: backport-skip, needs-writer-review

#4305 Fix invalid json in apm docs
  docs/en/observability/apm/custom-index-template.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14, backport-8.15, backport-8.x

#4318 Fix Logs Explorer naming in outdated docs
  docs/en/observability/logs-ecs-application.asciidoc
  docs/en/observability/logs-filter.asciidoc
  docs/en/observability/logs-plaintext.asciidoc
  docs/en/serverless/logging/view-and-monitor-logs.mdx
Labels: backport-skip, ci:doc-build

#4301 Update alert history chart screenshots
  docs/en/observability/images/log-threshold-breach-alert-history-chart.png
  docs/en/observability/images/log-threshold-breach-condition-chart.png
  docs/en/observability/images/log-threshold-breach-log-rate-analysis.png
  docs/en/observability/images/log-threshold-breach.png
  docs/en/observability/images/slo-burn-rate-breach.png
  docs/en/observability/triage-slo-burn-rate-breaches.asciidoc
  docs/en/observability/triage-threshold-breaches.asciidoc
Labels: backport-8.15, backport-8.x
