Repository elastic/observability-docs, pull requests merged in 2024-11, with the labels that each got.

#4462 Fix MDX syntax, broken links, and use of the `observability` variable
  docs/en/serverless/aiops/aiops-analyze-spikes.mdx
  docs/en/serverless/aiops/aiops-detect-anomalies.mdx
  docs/en/serverless/aiops/aiops-detect-change-points.mdx
  docs/en/serverless/aiops/aiops.mdx
  docs/en/serverless/alerting/create-elasticsearch-query-alert-rule.mdx
  docs/en/serverless/alerting/create-latency-threshold-alert-rule.mdx
  docs/en/serverless/alerting/synthetic-monitor-status-alert.mdx
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-opentelemetry-native-support.mdx
  docs/en/serverless/apm-agents/apm-agents-opentelemetry.mdx
  docs/en/serverless/infra-monitoring/get-started-with-metrics.mdx
  docs/en/serverless/infra-monitoring/host-metrics.mdx
  docs/en/serverless/infra-monitoring/infra-monitoring.mdx
  docs/en/serverless/inventory.mdx
  docs/en/serverless/logging/add-logs-service-name.mdx
  docs/en/serverless/logging/correlate-application-logs.mdx
  docs/en/serverless/logging/log-monitoring.mdx
  docs/en/serverless/logging/view-and-monitor-logs.mdx
  docs/en/serverless/observability-overview.mdx
  docs/en/serverless/projects/create-an-observability-project.mdx
  docs/en/serverless/quickstarts/k8s-logs-metrics.mdx
  docs/en/serverless/quickstarts/monitor-hosts-with-elastic-agent.mdx
  docs/en/serverless/synthetics/synthetics-analyze.mdx
  docs/en/serverless/synthetics/synthetics-command-reference.mdx
  docs/en/serverless/synthetics/synthetics-create-test.mdx
  docs/en/serverless/technical-preview-limitations.mdx
  docs/en/serverless/transclusion/apm/guide/install-agents/net.mdx
  docs/en/serverless/transclusion/synthetics/reference/lightweight-config/common.mdx
Labels: backport-skip, needs-writer-review, ci:doc-build

#4439 Port #4340 to stateful: Update EEM to reflect Inventory
  docs/en/observability/elastic-entity-model.asciidoc
Labels: needs-writer-review, Docset:Stateful, backport-8.x, needs-product-review, backport-8.16

#4440 Port #4342 to stateful docs: Remove services inventory
  docs/en/observability/apm/view-and-analyze/ui-overview/index.asciidoc
  docs/en/observability/apm/view-and-analyze/ui-overview/new-experience-services.asciidoc
  docs/en/observability/apm/view-and-analyze/ui-overview/services.asciidoc
Labels: needs-writer-review, Docset:Stateful, backport-8.x, needs-product-review, backport-8.16

#4444 add synthetics multi factor authentication docs
  docs/en/observability/index.asciidoc
  docs/en/observability/synthetics-command-reference.asciidoc
  docs/en/observability/synthetics-mfa.asciidoc
  docs/en/serverless/serverless-observability.docnav.json
  docs/en/serverless/synthetics/synthetics-command-reference.mdx
  docs/en/serverless/synthetics/synthetics-mfa.mdx
Labels: needs-writer-review, ci:doc-build, backport-8.15, backport-8.x, backport-8.16

#4473 Port #4442 to stateful
  docs/en/observability/images/kubernetes-filter.png
  docs/en/observability/images/metrics-app.png
  docs/en/observability/monitor-infra/view-infrastructure-metrics.asciidoc
Labels: needs-writer-review, Docset:Stateful, backport-8.x, backport-8.16

#4481 Trigger MDX build
  docs/en/serverless/ai-assistant/ai-assistant.mdx
Labels: backport-skip, needs-writer-review, ci:doc-build

#4349 Update threshold-alert.asciidoc
  docs/en/observability/threshold-alert.asciidoc
Labels: backport-main, backport-8.x, needs-serverless-port, backport-8.16

#4468 Update Logs Explorer docs with new summary column
  docs/en/observability/explore-logs.asciidoc
  docs/en/observability/images/log-explorer.png
  docs/en/observability/images/log-menu.png
  docs/en/serverless/images/log-explorer.png
  docs/en/serverless/images/log-menu.png
  docs/en/serverless/logging/view-and-monitor-logs.asciidoc
Labels: backport-8.x, backport-8.16

#4491 Fix 8.16 links
  docs/en/apm-server/redirects.asciidoc
  docs/en/observability/apm/api/apm-server/api-events.asciidoc
  docs/en/observability/apm/api/apm-server/api-metadata.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4494 Fix 8.16 redirects (part two)
  docs/en/apm-server/redirects.asciidoc
  docs/en/observability/redirects.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4507 [apm] Port apm-data plugin changes from stateful docs
  docs/en/serverless/apm/apm-troubleshooting/common-problems.asciidoc
Labels: backport-skip

#4503 [apm] Remove mentions of secret token in APM agent snippets in serverless docs
  docs/en/serverless/apm-agents/apm-agents-aws-lambda-functions.asciidoc
  docs/en/serverless/transclusion/apm/guide/install-agents/go.asciidoc
  docs/en/serverless/transclusion/apm/guide/install-agents/node.asciidoc
  docs/en/serverless/transclusion/apm/guide/install-agents/python.asciidoc
  docs/en/serverless/transclusion/apm/guide/install-agents/ruby.asciidoc
Labels: backport-skip, needs-writer-review, needs-dev-review

#4508 Universal Profiling: on-prem GA additions
  docs/en/observability/profiling-get-started.asciidoc
  docs/en/observability/profiling-self-managed-ops.asciidoc
  docs/en/observability/profiling-self-managed.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4505 Raise prefer_ilm configuration as a known issue
  docs/en/observability/apm/known-issues.asciidoc
Labels: needs-writer-review, backport-8.15, backport-8.x, backport-8.16

#4487 Fix stateful vs serverless attribute conflicts
  docs/en/serverless/ai-assistant/ai-assistant.asciidoc
  docs/en/serverless/aiops/aiops-analyze-spikes.asciidoc
  docs/en/serverless/aiops/aiops-detect-anomalies.asciidoc
  docs/en/serverless/aiops/aiops-detect-change-points.asciidoc
  docs/en/serverless/aiops/aiops-tune-anomaly-detection-job.asciidoc
  docs/en/serverless/aiops/aiops.asciidoc
  docs/en/serverless/alerting/aiops-generate-anomaly-alerts.asciidoc
  docs/en/serverless/alerting/alerting.asciidoc
  docs/en/serverless/alerting/create-anomaly-alert-rule.asciidoc
  docs/en/serverless/alerting/create-custom-threshold-alert-rule.asciidoc
  docs/en/serverless/alerting/create-error-count-threshold-alert-rule.asciidoc
  docs/en/serverless/alerting/create-failed-transaction-rate-threshold-alert-rule.asciidoc
  docs/en/serverless/alerting/create-latency-threshold-alert-rule.asciidoc
  docs/en/serverless/alerting/create-slo-burn-rate-alert-rule.asciidoc
  docs/en/serverless/alerting/triage-threshold-breaches.asciidoc
  docs/en/serverless/alerting/view-alerts.asciidoc
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-collect-metrics.asciidoc
  docs/en/serverless/apm-agents/apm-agents-opentelemetry-opentelemetry-native-support.asciidoc
  docs/en/serverless/apm/apm-find-transaction-latency-and-failure-correlations.asciidoc
  docs/en/serverless/apm/apm-get-started.asciidoc
  docs/en/serverless/apm/apm-integrate-with-machine-learning.asciidoc
  docs/en/serverless/apm/apm-keep-data-secure.asciidoc
  docs/en/serverless/apm/apm-ui-services.asciidoc
  docs/en/serverless/cases/create-manage-cases.asciidoc
  docs/en/serverless/cases/manage-cases-settings.asciidoc
  docs/en/serverless/index.asciidoc
  docs/en/serverless/infra-monitoring/analyze-hosts.asciidoc
  docs/en/serverless/infra-monitoring/configure-infra-settings.asciidoc
  docs/en/serverless/infra-monitoring/detect-metric-anomalies.asciidoc
  docs/en/serverless/infra-monitoring/get-started-with-metrics.asciidoc
  docs/en/serverless/infra-monitoring/handle-no-results-found-message.asciidoc
  docs/en/serverless/infra-monitoring/infra-monitoring.asciidoc
  docs/en/serverless/infra-monitoring/view-infrastructure-metrics.asciidoc
  docs/en/serverless/inventory.asciidoc
  docs/en/serverless/logging/ecs-application-logs.asciidoc
  docs/en/serverless/logging/get-started-with-logs.asciidoc
  docs/en/serverless/logging/plaintext-application-logs.asciidoc
  docs/en/serverless/logging/run-log-pattern-analysis.asciidoc
  docs/en/serverless/observability-overview.asciidoc
  docs/en/serverless/projects/create-an-observability-project.asciidoc
  docs/en/serverless/quickstarts/k8s-logs-metrics.asciidoc
  docs/en/serverless/quickstarts/monitor-hosts-with-elastic-agent.asciidoc
  docs/en/serverless/slos/create-an-slo.asciidoc
Labels: backport-skip, needs-writer-review

#4501 Add reference to prefer-ilm setting for apm lifeycle known bug
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#4517 [apm] Update Applications nav subsection from "Services" to "Service inventory"
  docs/en/observability/apm/view-and-analyze/ui-overview/services.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
  docs/en/serverless/apm/apm-find-transaction-latency-and-failure-correlations.asciidoc
  docs/en/serverless/apm/apm-get-started.asciidoc
  docs/en/serverless/apm/apm-ui-services.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4433 [Observability Onboarding] Add AWS Firehose quickstart
  docs/en/observability/images/quickstart-aws-firehose-dashboards.png
  docs/en/observability/images/quickstart-aws-firehose-entry-point.png
  docs/en/observability/images/quickstart-aws-firehose-vpc-flow.png
  docs/en/observability/index.asciidoc
  docs/en/observability/quickstarts/collect-data-with-aws-firehose.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4502 Update search connectors links
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-8.x, backport-8.16

#4551 [Synthetics]: fix lightweight http configuration
  docs/en/observability/synthetics-reference/lightweight-config/http.asciidoc
  docs/en/serverless/transclusion/synthetics/reference/lightweight-config/http.asciidoc
Labels: needs-writer-review, backport-8.13, backport-8.14, backport-8.15

#4545 [AWS Firehose quickstart] Port 4433 to serverless docs
  docs/en/serverless/images/quickstart-aws-firehose-dashboards.png
  docs/en/serverless/images/quickstart-aws-firehose-entry-point.png
  docs/en/serverless/images/quickstart-aws-firehose-vpc-flow.png
  docs/en/serverless/index.asciidoc
  docs/en/serverless/quickstarts/collect-data-with-aws-firehose.asciidoc
  docs/en/serverless/quickstarts/overview.asciidoc
Labels: backport-skip, needs-writer-review

#4561 Remove stray tech preview references
  docs/en/serverless/limitations.asciidoc
  docs/en/serverless/what-is-observability-serverless.asciidoc
Labels: backport-skip, needs-writer-review

#4555 mergify: 8.17 backports
  .mergify.yml
Labels: backport-skip, needs-writer-review

#4554 fix: force checkout from main
  .github/Makefile
Labels: backport-skip, needs-writer-review

#4546 Link to serverless docs from main obs guide
  docs/en/observability/landing-page/page.asciidoc
  docs/en/serverless/what-is-observability-serverless.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16

#4566 Update explore-logs.asciidoc missing permissions
  docs/en/observability/explore-logs.asciidoc
Labels: docs, Team:Docs, needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4532 Apply IA changes to serverless docs
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/slo-overview.asciidoc
  docs/en/serverless/ai-assistant/ai-assistant.asciidoc
  docs/en/serverless/application-and-service-monitoring.asciidoc
  docs/en/serverless/dashboards/dashboards-and-visualizations.asciidoc
  docs/en/serverless/images/get-started.svg
  docs/en/serverless/incident-management.asciidoc
  docs/en/serverless/index.asciidoc
  docs/en/serverless/infra-monitoring/infra-monitoring.asciidoc
  docs/en/serverless/infrastructure-and-host-monitoring-intro.asciidoc
  docs/en/serverless/logging/log-monitoring.asciidoc
  docs/en/serverless/machine-learning/aiops-analyze-spikes.asciidoc
  docs/en/serverless/machine-learning/aiops-detect-anomalies.asciidoc
  docs/en/serverless/machine-learning/aiops-detect-change-points.asciidoc
  docs/en/serverless/machine-learning/aiops-forecast-anomaly.asciidoc
  docs/en/serverless/machine-learning/aiops-tune-anomaly-detection-job.asciidoc
  docs/en/serverless/machine-learning/machine-learning.asciidoc
  docs/en/serverless/monitor-datasets.asciidoc
  docs/en/serverless/observability-get-started.asciidoc
  docs/en/serverless/observability-overview.asciidoc
  docs/en/serverless/quickstarts/collect-data-with-aws-firehose.asciidoc
  docs/en/serverless/quickstarts/k8s-logs-metrics.asciidoc
  docs/en/serverless/quickstarts/monitor-hosts-with-elastic-agent.asciidoc
  docs/en/serverless/quickstarts/overview.asciidoc
  docs/en/serverless/redirects.asciidoc
  docs/en/serverless/reference.asciidoc
  docs/en/serverless/reference/elastic-entity-model.asciidoc
  docs/en/serverless/reference/metrics-app-fields.asciidoc
  docs/en/serverless/slos/slos.asciidoc
  docs/en/serverless/what-is-observability-serverless.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4549 Update serverless logs pages with bug bash updates
  docs/en/serverless/logging/get-started-with-logs.asciidoc
  docs/en/serverless/logging/run-log-pattern-analysis.asciidoc
  docs/en/serverless/logging/stream-log-files.asciidoc
  docs/en/serverless/logging/troubleshoot-logs.asciidoc
Labels: backport-skip, needs-writer-review

#4579 Fix paths in serverless procedures
  docs/en/observability/monitor-infra/analyze-hosts.asciidoc
  docs/en/observability/monitor-infra/monitor-infrastructure-and-hosts.asciidoc
  docs/en/observability/monitor-k8s/monitor-k8s-explore-logs-and-metrics.asciidoc
  docs/en/serverless/alerting/aiops-generate-anomaly-alerts.asciidoc
  docs/en/serverless/alerting/create-inventory-threshold-alert-rule.asciidoc
  docs/en/serverless/apm/apm-integrate-with-machine-learning.asciidoc
  docs/en/serverless/infra-monitoring/analyze-hosts.asciidoc
  docs/en/serverless/infra-monitoring/configure-infra-settings.asciidoc
  docs/en/serverless/infra-monitoring/detect-metric-anomalies.asciidoc
  docs/en/serverless/infra-monitoring/get-started-with-metrics.asciidoc
  docs/en/serverless/infra-monitoring/view-infrastructure-metrics.asciidoc
  docs/en/serverless/machine-learning/aiops-analyze-spikes.asciidoc
  docs/en/serverless/machine-learning/aiops-detect-anomalies.asciidoc
  docs/en/serverless/machine-learning/aiops-detect-change-points.asciidoc
  docs/en/serverless/machine-learning/aiops-tune-anomaly-detection-job.asciidoc
  docs/en/serverless/observability-overview.asciidoc
  docs/en/serverless/reference/metrics-app-fields.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4582 Update quickstarts for 8.16
  docs/en/observability/images/quickstart-autodetection-command.png
  docs/en/observability/images/quickstart-aws-firehose-entry-point.png
  docs/en/observability/images/quickstart-k8s-entry-point.png
  docs/en/observability/images/quickstart-k8s-otel-entry-point.png
  docs/en/observability/images/quickstart-monitor-hosts-entry-point.png
  docs/en/observability/quickstarts/collect-data-with-aws-firehose.asciidoc
  docs/en/observability/quickstarts/monitor-hosts-with-elastic-agent.asciidoc
  docs/en/observability/quickstarts/monitor-k8s-logs-metrics.asciidoc
  docs/en/observability/quickstarts/monitor-k8s-otel.asciidoc
  docs/en/serverless/images/quickstart-autodetection-command.png
  docs/en/serverless/images/quickstart-aws-firehose-entry-point.png
  docs/en/serverless/images/quickstart-k8s-entry-point.png
  docs/en/serverless/images/quickstart-monitor-hosts-entry-point.png
  docs/en/serverless/quickstarts/collect-data-with-aws-firehose.asciidoc
  docs/en/serverless/quickstarts/k8s-logs-metrics.asciidoc
  docs/en/serverless/quickstarts/monitor-hosts-with-elastic-agent.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4581 [Synthetics]: fix MFA totp method for browser monitors
  docs/en/observability/synthetics-mfa.asciidoc
  docs/en/serverless/synthetics/synthetics-mfa.asciidoc
Labels: needs-writer-review, backport-8.15, backport-8.16

#4486 Adding SLOs troubleshooting document (attempt 2)
  docs/en/observability/index.asciidoc
  docs/en/observability/slo-create.asciidoc
  docs/en/observability/slo-overview.asciidoc
  docs/en/observability/slo-privileges.asciidoc
  docs/en/observability/slo-troubleshoot.asciidoc
Labels: backport-8.x, needs-product-review, backport-8.16, backport-8.17
