Repository elastic/observability-docs, pull requests merged in 2025-01, with the labels that each got.

#4714 [apm] Clarify requirements in the Fleet-managed APM Server guide
  docs/en/observability/apm/getting-started-apm/get-started-with-fleet-apm-server.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4729 Add 8.18 to issue template
  .github/ISSUE_TEMPLATE/elastic-request.yaml
Labels: backport-skip, needs-writer-review

#4728 [apm] Clarify doc on configuring APM agent central configuration
  docs/en/observability/apm/configure/agent-config.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4730 Remove list of supported generative AI providers
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: backport-skip, needs-writer-review

#4670 [apm] Clarify how to create/use API keys
  docs/en/observability/apm/configure/agent-config.asciidoc
  docs/en/observability/apm/configure/outputs/elasticsearch.asciidoc
  docs/en/observability/apm/https.asciidoc
  docs/en/observability/apm/images/apm-api-key-beats.png
  docs/en/observability/apm/security/elastic-stack/access-api-keys.asciidoc
Labels: needs-writer-review, backport-8.x, needs-dev-review, backport-8.16, backport-8.17

#4734 Clarify that tail-based sampling is only available for ES output
  docs/en/observability/apm/configure/sampling.asciidoc
  docs/en/observability/apm/data-model/transactions/sampling.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4709 Enhancements to alerting docs
  docs/en/observability/apm-anomaly-rule.asciidoc
  docs/en/observability/apm-error-count-threshold-rule.asciidoc
  docs/en/observability/apm-failed-transaction-rate-threshold-rule.asciidoc
  docs/en/observability/apm-latency-threshold-rule.asciidoc
  docs/en/observability/apm/view-and-analyze/machine-learning.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/inventory-threshold-alert.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/slo-burn-rate-alert.asciidoc
  docs/en/observability/threshold-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4441 Update APM Server throughput number for 8.16.0
  docs/en/observability/apm/troubleshooting/processing-performance.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4750 [synthetics] Update TLS certificate rule doc to include Synthetics
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/images/tls-certificate-alert-default-message.png
  docs/en/observability/images/tls-rule-synthetics-action-types-each-alert.png
  docs/en/observability/images/tls-rule-synthetics-action-types-more-options.png
  docs/en/observability/images/tls-rule-synthetics-action-types-summary.png
  docs/en/observability/images/tls-rule-synthetics-action-variables.png
  docs/en/observability/images/tls-rule-synthetics-conditions.png
  docs/en/observability/images/tls-rule-uptime-action-types-each-alert.png
  docs/en/observability/images/tls-rule-uptime-action-types-more-options.png
  docs/en/observability/images/tls-rule-uptime-action-types-summary.png
  docs/en/observability/images/tls-rule-uptime-conditions.png
  docs/en/observability/images/tls-rule-uptime-default-message.png
  docs/en/observability/synthetics-uptime-tls-alert.asciidoc
  docs/en/observability/uptime-tls-alert.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4763 fix: Add changes for upload sourcemaps snippet
  docs/en/observability/apm/collect-application-data/agents/source-map-how-to.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4769 Update apm-spaces.asciidoc
  docs/en/observability/apm/security/data-security/apm-spaces.asciidoc
Labels: backport-skip, needs-writer-review

#4761 Add deprecation warning to Jaeger API docs
  docs/en/observability/apm/api/apm-server/api-jaeger.asciidoc
Labels: backport-skip, needs-writer-review

#4719 SLOs troubleshoot added to serverless content (port #4486)
  docs/en/serverless/index.asciidoc
  docs/en/serverless/slos/slo-troubleshoot.asciidoc
  docs/en/serverless/slos/slos.asciidoc
Labels: backport-skip, needs-writer-review

#4770 add known issues section to profiling docs
  docs/en/observability/index.asciidoc
  docs/en/observability/profiling-known-issues.asciidoc
Labels: needs-writer-review, backport-8.16, backport-8.17

#4777 Add OTel quickstart to Get started page
  docs/en/observability/observability-get-started.asciidoc
  docs/en/serverless/observability-get-started.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4754 Obs AI Assistant supports other models than ELSER when field type semantic_text is used
  docs/en/observability/observability-ai-assistant.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.17

#4785 Universal Profiling: Update image of flamegraph
  docs/en/observability/images/profiling-flamegraph-view.png
Labels: backport-skip, needs-writer-review

#4778 github-actions(pre-commit): detect merge conflicts and shebangs
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: backport-7.17, needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4784 [AWS Firehose] Clarify where to find ES endpoint
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudtrail-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudwatch-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firewall-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-waf-firehose.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.17

#4693 Add common pipeline and mapping issues and mitigations
  docs/en/observability/logs-troubleshooting.asciidoc
  docs/en/serverless/logging/troubleshoot-logs.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4783 Simplify complex tables
  docs/en/observability/apm/act-on-data/alerts.asciidoc
  docs/en/observability/apm/agent-server-compatibility.asciidoc
  docs/en/observability/apm/collect-application-data/open-telemetry/otel-direct.asciidoc
  docs/en/observability/apm/configure/advanced-setup/command-reference.asciidoc
  docs/en/observability/apm/getting-started-apm/index.asciidoc
  docs/en/observability/apm/security/elastic-stack/feature-roles.asciidoc
  docs/en/observability/create-alerts.asciidoc
  docs/en/observability/grant-cases-access.asciidoc
  docs/en/observability/monitor-status-alert.asciidoc
  docs/en/observability/profiling-self-managed.asciidoc
  docs/en/observability/synthetics-create-test.asciidoc
  docs/en/observability/synthetics-migrate-integration.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/http.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/icmp.asciidoc
  docs/en/observability/synthetics-reference/lightweight-config/tcp.asciidoc
  docs/en/observability/synthetics-support-matrix.asciidoc
  docs/en/serverless/apm/act-on-data/alerts.asciidoc
  docs/en/serverless/apm/collect-application-data/open-telemetry/otel-direct.asciidoc
  docs/en/serverless/apm/getting-started-apm/index.asciidoc
  docs/en/serverless/logging/stream-log-files.asciidoc
  docs/en/serverless/synthetics/synthetics-create-test.asciidoc
  docs/en/serverless/synthetics/synthetics-feature-roles.asciidoc
  docs/en/serverless/transclusion/synthetics/configuration/monitor-config-options.asciidoc
  docs/en/serverless/transclusion/synthetics/reference/lightweight-config/common.asciidoc
  docs/en/serverless/transclusion/synthetics/reference/lightweight-config/http.asciidoc
  docs/en/serverless/transclusion/synthetics/reference/lightweight-config/icmp.asciidoc
  docs/en/serverless/transclusion/synthetics/reference/lightweight-config/tcp.asciidoc
Labels: backport-skip, needs-writer-review

#4779 Note features that are not supported in serverless
  docs/en/observability/apm/collect-application-data/agents/agent-configuration.asciidoc
  docs/en/observability/apm/data-model/transactions/sampling.asciidoc
  docs/en/observability/apm/security/elastic-stack/feature-roles.asciidoc
Labels: needs-writer-review, backport-8.x, backport-8.16, backport-8.17

#4795 github-action: Add AsciiDoc freeze warning
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: backport-skip, needs-writer-review

#4808 [DOCS] Remove links to master
  docs/en/serverless/cases/manage-cases-settings.asciidoc
Labels: backport-skip, needs-writer-review
