Repository elastic/observability-docs, pull requests merged in 2025-04, with the labels that each got.

#4869 [Synthetics] Fix step async declaration in snippets
  docs/en/observability/synthetics-create-test.asciidoc
Labels: backport-8.17, backport-8.18

#4872 Hide EEM and inventory pages
  docs/en/observability/apm/view-and-analyze/inventory.asciidoc
  docs/en/observability/elastic-entity-model.asciidoc
Labels: backport-8.x

#4868 [otel] Use GitHub pages links
  docs/en/observability/apm/collect-application-data/open-telemetry/index.asciidoc
  docs/en/observability/quickstarts/monitor-hosts-with-otel.asciidoc
  docs/en/observability/quickstarts/monitor-k8s-otel.asciidoc
Labels: needs-writer-review, needs-dev-review, backport-8.17, backport-8.18

#4887 New way of backporting
  .github/workflows/backport-active.yml
  .mergify.yml
Labels: enhancement, backport-skip, needs-writer-review

#4873 [synthetics] Document private locations space awareness
  docs/en/observability/synthetics-private-location.asciidoc
Labels: backport-8.x
