Repository elastic/observability-docs, pull requests merged in 2025-02, with the labels that each got.

#4813 [DOCS] Fix hard-coded links to master
  docs/en/ingest-management/elastic-agent/run-container-common/kibana-fleet-data.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/observability/whats-new.asciidoc
Labels: backport-skip

#4822 remove limitations
  docs/en/apm-server/redirects.asciidoc
  docs/en/serverless/index.asciidoc
  docs/en/serverless/limitations.asciidoc
  docs/en/serverless/redirects.asciidoc
Labels: backport-skip, needs-writer-review

#4825 Add note on APM Server Personal Data
  docs/en/observability/apm/security/data-security/filtering.asciidoc
Labels: needs-writer-review, backport-8.x

#4818 [AWS Firehose] Improve Firehose documentation
  docs/en/observability/cloud-monitoring/aws/ingest-aws-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudtrail-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudwatch-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-firewall-firehose.asciidoc
  docs/en/observability/cloud-monitoring/aws/monitor-aws-waf-firehose.asciidoc
Labels: needs-writer-review, backport-8.16, backport-8.17
