Repository elastic/observability-docs, pull requests merged in 2025-03, with the labels that each got.

#4831 [8.18](backport) Manual backport missing from previous PR
  docs/en/observability/apm/security/data-security/filtering.asciidoc
Labels: backport-8.13, backport-8.14, backport-8.15, backport-8.16, backport-8.17

#4844 Add known issue for APM Server version 8.6 and older with ES 8.15
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.x

#4850 [8.18] New sub-feature priv for case assignees
  docs/en/observability/grant-cases-access.asciidoc
Labels: backport-8.18

#4852 Manual backport of 4850 targeting 8.18
  docs/en/observability/grant-cases-access.asciidoc
Labels: backport-skip

#4855 Add docs for monitoring TBS
  docs/en/observability/apm/configure/sampling.asciidoc
Labels: backport-8.16, backport-8.17, backport-8.18

#4810 mergify: support 8.18 backports
  .mergify.yml
Labels: backport-skip, needs-writer-review
