Repository elastic/observability-docs, pull requests merged in 2025-08, with the labels that each got.

#4922 Emergency update to 8.19 known issues
  docs/en/observability/apm/known-issues.asciidoc
Labels: docs

#4926 [Observability Docs] Replace placeholder URLs
  docs/en/observability/apm/collect-application-data/open-telemetry/otel-direct.asciidoc
  docs/en/observability/apm/configure/advanced-setup/command-reference.asciidoc
  docs/en/observability/apm/configure/outputs/elasticsearch.asciidoc
  docs/en/observability/apm/https.asciidoc
  docs/en/observability/apm/monitor-apm-server/monitoring-internal-collection.asciidoc
  docs/en/observability/apm/shared-ssl-logstash-config.asciidoc
  docs/en/observability/apm/tab-widgets/install-agents.asciidoc
  docs/en/observability/ci-cd-observability.asciidoc
  docs/en/observability/logs-ecs-application.asciidoc
  docs/en/observability/logs-plaintext.asciidoc
  docs/en/observability/logs-stream.asciidoc
  docs/en/observability/logs-troubleshooting.asciidoc
  docs/en/observability/monitor-java-app.asciidoc
  docs/en/observability/profiling-self-managed-ops.asciidoc
  docs/en/observability/synthetics-configuration.asciidoc
Labels: backport-8.9, backport-8.1, backport-8.2, backport-8.0, backport-7.17, backport-8.4, backport-8.5, backport-8.6, backport-8.7, backport-8.8, backport-8.3, backport-8.10, backport-8.11, backport-8.12, backport-8.13, backport-8.14, backport-8.15, backport-8.16, backport-8.17, backport-8.18

#4950 Fix synthetics docs for read-only user
  docs/en/observability/synthetics-role-read.asciidoc
Labels: backport-8.18
