Repository elastic/observability-docs, pull requests merged in 2025-07, with the labels that each got.

#4821 [DOCS] Update kafka.asciidoc
  docs/en/observability/apm/configure/outputs/kafka.asciidoc
Labels: Team:Docs

#4862 Add APM Server known issue for TBS
  docs/en/observability/apm/known-issues.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16, backport-8.17, backport-8.18

#4908 [apm]: Document sampling.tail.discard_on_write_failure config
  docs/en/observability/apm/configure/sampling.asciidoc
Labels: backport-skip

#4915 ci: move from dependabot reviewers to CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: backport-skip, needs-writer-review
